### ISSUE TITLE
登陆后无法同步

### ISSUE THREAD

**Issue by Lijia-Li** [zhaohongxuan/obsidian-weread-plugin#102]
登陆微信读书后，sync失败，无报错
<img width="243" alt="Screen Shot 2022-09-27 at 1 18 41 PM" src="https://user-images.githubusercontent.com/22532108/192438400-d7a48a4f-a73e-4146-8421-d3ebbfe25b3b.png">

Obsidian 0.15.9 
Weread-Plugin 0.4.6

**Comment by Lijia-Li** [comment]
关上VPN后开始报错： 

<img width="551" alt="Screen Shot 2022-09-27 at 1 23 34 PM" src="https://user-images.githubusercontent.com/22532108/192439100-973e75b0-7e46-4814-a185-17985a33fc0e.png">

**Comment by Rnzi** [comment]
我跟你问题差不多，关了vpn后报错也是这样，后来自己实验解决了。系统是macos11，默认开了VPN，也不用关，只需要点击同步后什么操作都不要做，两根烟的功夫就同步成功了，我测试的是4w+条划线笔记。
同步时候OB后台并没有别的显示，但可以从mac的性能监视器里看到网络接收中的obsidian helper是有数据增加的。

**Comment by zhaohongxuan** [comment]
应该是网络问题。

**Comment by Loongphy** [comment]
CFW 开启了系统代理，关闭代理可以同步成功
