### ISSUE TITLE
可以设置按照原文顺序排列吗？

### ISSUE THREAD

**Issue by chipsflying** [zhaohongxuan/obsidian-weread-plugin#103]
就是不将“高亮划线”和“划线评论”分开排列，而是按照原文的顺序混合排列两种，这样方便重新阅读。
请问有没有这种设置？

**Comment by palwoo** [comment]
"高亮划线"和“划线评论”是两种不同品质的内容，后者是经过自己消化产生的输出，分开排列更加科学。如果你想在“高亮划线”部分不错过你曾“划线评论”而得到的“高亮”部分，可以在微信阅读中对该部分既“高亮划线”也“划线评论”。

但是无论在“高亮划线”还是“划线评论”部分，如果都能按照原文顺序排列，而非现在的按产生的时间顺序排列，就更加符合内容的逻辑。建议修改目前的排列顺序，或者在说明文档中把改变排列顺序的代码附上，毕竟使用插件的人有很多都不懂编程。

非常欣赏插件作者对下载下来的内容都加上了永久不变的Block ID, 这样在做引用时就更放心了，不至于因为重新下载而导致引用失效。

**Comment by palwoo** [comment]
赞同楼主的建议。现在觉得“高亮划线”和“划线评论”不分开排列自有它的好处。不过，这些是个人的偏好选择，可以通过不同的模板实现。插件作者在[他个人用的模板](https://github.com/zhaohongxuan/obsidian-weread-plugin/discussions/62#discussioncomment-3164134) 里就是这样做的。通过加标签的方式，可以单独把划线评论检索出来阅读。

但经再次实验，的确如楼主所言，在章节之内是按高亮划线时间顺序排列，而非按内容顺序。这个极其不爽。非程序员用户不知该如何解决。 @zhaohongxuan

**Comment by zhaohongxuan** [comment]
我找到了获取章节的API，这个功能应该可以实现了，只是需要代码重构需要时间。
