### ISSUE TITLE
登录超时

### ISSUE THREAD

**Issue by rien7** [zhaohongxuan/obsidian-weread-plugin#104]
![image](https://user-images.githubusercontent.com/47098554/194715491-f6047744-b15c-4abc-b039-d2f9283bcd1b.png)
在登录一段时间后再次同步笔记会出现该错误，将控制台的命令运行后得到的是“登录超时”的 json

但是在点击注销按钮弹出的页面中，帐号处于登录状态
![image](https://user-images.githubusercontent.com/47098554/194715581-212bb4da-c9b0-4451-a3ca-5f0ed637a531.png)

**Comment by palwoo** [comment]
我也遇到过这样的情况。然后发现浏览器有浏览微信读书的窗口，是登录状态。就把浏览器关掉，把obsidian也关掉，然后再重启obsidian，看weread插件的登录状态，已是未登录状态。再扫描登录，同步成功。

**Comment by zhaohongxuan** [comment]
这个已经fix了，超时的时候自动清理掉cookie，不需要再手动注销了。
