### ISSUE TITLE
如何下载完整的章节结构

### ISSUE THREAD

**Issue by palwoo** [zhaohongxuan/obsidian-weread-plugin#106]
[Higurashi-kagome/wereader](https://github.com/Higurashi-kagome/wereader)，这个微信读书笔记助手浏览器扩展在导出高亮笔记时可以把全书的章节结构（大章小节的标题）都下载下来，高亮笔记归属相应的位置。没有高亮的部分，也会有章节的题目出现。对把握全书的整体结构很有好处，对理解高亮内容所处的位置也有帮助。例如下图

![Snipaste_2022-10-20_14-42-16](https://user-images.githubusercontent.com/83803265/196875287-14f46d82-7ae4-40ed-a916-1639a0d24dfc.jpg)

不知道要做到这样的效果，目前通过在obsidian-weread-plugin的插件模板里设置可否做到？如果不能，可否在下个版本里实现？多谢。

**Comment by zhaohongxuan** [comment]
我找到了新的API可以做，但是我自己觉得这是画蛇添足的功能，而且需要额外调用接口，会有性能损耗，而且从主管上来说，如果什么都没留下，是不是可以证明这一章节并不重要？

**Comment by palwoo** [comment]
您说的有道理。^_^

**Comment by Rainvoo** [comment]
> 我找到了新的API可以做，但是我自己觉得这是画蛇添足的功能，而且需要额外调用接口，会有性能损耗，而且从主管上来说，如果什么都没留下，是不是可以证明这一章节并不重要？

你好，我觉得这个是我非常需要的功能，因为我现在是手动整理的微信读书的笔记，会特地用 chrome 的 wereader 插件，将完整目录结构导出。且会用 markdown 格式，来维护目录的层级。

这个功能对我的帮助有两个：

1. 回顾这本书时，可以通过目录结构（h1/h2 两层基本足够覆盖绝大多数书籍），快速回忆起书的大致有几部分（特别是偏科普的，这种逻辑严谨的书）
2. 当我做想法撰写时，我可以通过 [[文件名/章节名]] 来方便的引用、转跳

所以可以请问可以再评估下该需求吗？

**Comment by amelloly** [comment]
笔记模版看起来不错啊，可以分享一下吗？

**Comment by ColdOxygen** [comment]
> [Higurashi-kagome/wereader](https://github.com/Higurashi-kagome/wereader)，这个微信读书笔记助手浏览器扩展在导出高亮笔记时可以把全书的章节结构（大章小节的标题）都下载下来，高亮笔记归属相应的位置。没有高亮的部分，也会有章节的题目出现。对把握全书的整体结构很有好处，对理解高亮内容所处的位置也有帮助。例如下图
> 
> ![Snipaste_2022-10-20_14-42-16](https://user-images.githubusercontent.com/83803265/196875287-14f46d82-7ae4-40ed-a916-1639a0d24dfc.jpg)
> 
> 不知道要做到这样的效果，目前通过在obsidian-weread-plugin的插件模板里设置可否做到？如果不能，可否在下个版本里实现？多谢。

Hello
图片中的笔记形式非常心水。
请教下如何设置wereader可以达到图片的效果。
默认设置下，每一章的目录和高亮标注是分离的。
举个例子
item 7
item 7.1
item 7.2
item 7.2.1
item 7.3
标注1
标注2
标注3

**Comment by palwoo** [comment]
@amelloly @ColdOxygen  截图中的显示效果是通过https://github.com/Higurashi-kagome/wereader 浏览器插件导出的markdown格式文件，拷贝到logseq中得到的。不是我们现在正在讨论的Obsidian插件。

**Comment by palwoo** [comment]
@zhaohongxuan 虽然有人觉得下载完整的目录结构很有用处，但这个您说了算。不过还有另外一个建议，即使不下载整个完整的目录结构，可否对有高亮或评论的部分的目录结构下载的更完整一些，（大）章（小）节都包含在内？我非常赞同您说的为了提高读书效果，应该另外再做永久笔记，但如果下载下来的内容目录结构清晰，则更有利于复习阅读和下一步的加工。

**Comment by icyyyraven** [comment]
请问如何修改参数能恢复到原来不显示完整章节结构的状态呀..有的长篇书章节标题（三级）就是数字而已，现在这样就会拉出很多下面没有内容的数字
