### ISSUE TITLE
能否增加直接阅读书籍的功能？

### ISSUE THREAD

**Issue by scorpionxyz** [zhaohongxuan/obsidian-weread-plugin#108]
custome frames之类的插件，现在都没法扫码登录到微信读书，本插件点击注销按钮会有一个单独的窗口，可以进行书籍阅读，但是如果能实现在一个新建的tab页面阅读书籍就太谢谢作者了！

**Comment by milla** [comment]
我是直接使用canvas内嵌web page实现的，pin在sidebar很方便，体验比iframe丝滑太多。
<img width="2129" alt="image" src="https://user-images.githubusercontent.com/297531/215071925-1d85f698-1242-444b-80f4-d60f4ba875cb.png">

**Comment by zhaohongxuan** [comment]
Duplicate with: https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/122
