### ISSUE TITLE
展示阅读过的以及最近正在阅读的书籍

### ISSUE THREAD

**Issue by sivanWu0222** [zhaohongxuan/obsidian-weread-plugin#109]
您好，按照README.md中提示的，新建了一个文档，然后在文档中加入如下内容，没有按照预期结果展示卡片，是有什么格式或者内容不太对的地方么，求指教
<img width="919" alt="image" src="https://user-images.githubusercontent.com/24709251/200153048-5355a8e2-1b68-44bb-ac40-04c6a90224fe.png">

**Comment by hadwinn** [comment]
可以参考一下
![image](https://user-images.githubusercontent.com/73227570/205876850-e75beeb6-4eee-44db-9f07-ec0b3ae873ce.png)

再检查一下文件路径是否正确
