### ISSUE TITLE
请问我拖动到其他文件夹的单个笔记文件，还在插件更新范围内吗？

### ISSUE THREAD

**Issue by xieyingli** [zhaohongxuan/obsidian-weread-plugin#111]
如果不在的话，为啥再重新点击插件，那个设置的缓存文件夹并没有再刷新出来一次。

**Comment by zhaohongxuan** [comment]
目前只要在OB的vault内，都会索引，移出去的话要把front-matter上的元数据移出才行

**Comment by xieyingli** [comment]
> 目前只要在OB的vault内，都会索引，移出去的话要把front-matter上的元数据移出才行

难怪，我之前看到首页那个“覆盖式更新”糊涂了。

还有一个不知道不是bug的跟这个话题有点关系也在这里提一下：
我有一本自己上传的图书，然后做了一个划线，然后我专门去测试了一下删除划线（这个时候这本书已经完全没有划线了），但是在ob里反复好几天还是没能把这个页面自动给删除，划线的段落也还在。

**Comment by xieyingli** [comment]
@zhaohongxuan ⬆️

**Comment by zhaohongxuan** [comment]
划线全部删除之后，这本书就没发索引到了，本地不会自动删除，就像你自己上传一本书到书架，从书架移除，划线和评论都会自动删除，我不会删掉你在Obsidian中记录的这本书，除非你自己删除。
