### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by yibie** [zhaohongxuan/obsidian-weread-plugin#112]
每一次点击按钮，都无法同步微信读书里的划线内容。

经常显示「跳过更新0本没更新的书」。

请问是为什么？

**Comment by yibie** [comment]
我把控制台里报错的信息发上来，希望能够提供参考。

![image](https://user-images.githubusercontent.com/365484/208312325-135683bb-7e39-4b80-a214-f50d48d2ba43.png)
![image](https://user-images.githubusercontent.com/365484/208312330-9a2b34e8-868a-4fa6-bb6b-0e60a7c12d62.png)

**Comment by zhaohongxuan** [comment]
重新加载一下插件，然后登录试试
