### ISSUE TITLE
能不能将划线和划线评论放在一起，然后排序也按照页数或者文字的前后来排列？

### ISSUE THREAD

**Issue by Renjie1997** [zhaohongxuan/obsidian-weread-plugin#114]
划线和划线评论不知道能不能放一起，还有排序不知道微信有没有按照文章的顺序排序e若不是按照划线的时间排序。不知道有没有这样的功能？谢谢

**Comment by milla** [comment]
同问，我看了下chapterhighlights和chapterreviews等貌似是返回的两个数组，能不能关联起来按文章顺序合并？

**Comment by xjtu-blacksmith** [comment]
我目前是直接用 `chapterHighlights` 元素的 `reviewContent` 值来返回划线笔记的内容，这样可以跟对应的划线原文放在一起。不过这样的前提是：所有笔记都是通过**点击已有的划线内容**添加的，直接划线（没有高亮）添加的笔记不会包括在内。因为我自己都是先划线高亮、再写想法，所以这样可以把所有笔记都囊括进来；对其他人这个方案可能不适用。

我现在用的模板片段：
```mustache
# 划线笔记
{% for chapter in chapterHighlights %}
## {{chapter.chapterTitle}}
{% for highlight in chapter.highlights %}
- {{ highlight.markText |trim }}  *【{{highlight.createTime}}】*{% if highlight.reviewContent %}
  > {{ highlight.reviewContent |trim }}{% endif %}{% endfor %}
{% endfor %}
```

大概的效果：
![图片](https://user-images.githubusercontent.com/42454373/228997678-3ce9a6c0-c969-4796-a184-7d4f8138ebce.png)

**Comment by marsvet** [comment]
附议，不然感觉高亮和笔记太割裂了

**Comment by huiyouniude** [comment]
附议，遇到章节多的书籍，划线和笔记离得太远了……能不能按照章节来分类，一章里面高亮+笔记放到一起，这样感觉会更好

**Comment by zhaohongxuan** [comment]
> 我目前是直接用 `chapterHighlights` 元素的 `reviewContent` 值来返回划线笔记的内容，这样可以跟对应的划线原文放在一起。不过这样的前提是：所有笔记都是通过**点击已有的划线内容**添加的，直接划线（没有高亮）添加的笔记不会包括在内。因为我自己都是先划线高亮、再写想法，所以这样可以把所有笔记都囊括进来；对其他人这个方案可能不适用。
> 
> 我现在用的模板片段：
> 
> ```
> # 划线笔记
> {% for chapter in chapterHighlights %}
> ## {{chapter.chapterTitle}}
> {% for highlight in chapter.highlights %}
> - {{ highlight.markText |trim }}  *【{{highlight.createTime}}】*{% if highlight.reviewContent %}
>   > {{ highlight.reviewContent |trim }}{% endif %}{% endfor %}
> {% endfor %}
> ```
> 
> 大概的效果： ![图片](https://user-images.githubusercontent.com/42454373/228997678-3ce9a6c0-c969-4796-a184-7d4f8138ebce.png)
如果需要合并划线和评论的可以参考这段代码，引用`highlight.reviewContent`就可以了，如果大家都喜欢合并在一起的话，后面会把默认的模板改一下。
