### ISSUE TITLE
登录失败~ 

### ISSUE THREAD

**Issue by renlianfu** [zhaohongxuan/obsidian-weread-plugin#115]
不知为何obsidian读取不了cookies 
选择同步后提示过期清理cookies 再次点登录 不用扫码身份信息就出来了 但还是问题依旧
![image](https://user-images.githubusercontent.com/27400703/208903335-0e239b09-d306-4748-b873-d931eb13a9d1.png)

**Comment by zoniguan** [comment]
同样的问题。请问是如何解决的？
