### ISSUE TITLE
同步笔记时间顺序倒置

### ISSUE THREAD

**Issue by zkyken** [zhaohongxuan/obsidian-weread-plugin#120]
最近发现同步评论笔记时，新的笔记排在前面，而不是按文章的顺利或者阅读标注评论笔记的顺利排列。以前的笔记时间顺序是正常的。另外，高亮笔记倒是正常顺序。用的是官方模板。

**Comment by MiracleXYZ** [comment]
我也发现了这个问题，好像现在还没有解决。

**Comment by MiracleXYZ** [comment]
如果想要以时间顺序正序排列，可以在模板中把原来的 `{% for review in chapter.reviews %}` 改为

```
{% for review in chapter.reviews | sort(attribute='createTime') %}
```

但如果以标注笔记的顺序排列，模板中给了 `range` 这个属性，但是它是 `1234-5678` 这种字符串类型，不好排序。建议后面可以提供诸如 `startPosition` 和 `endPosition` 之类数字类型的属性，这样排序起来比较方便。

**Comment by zhaohongxuan** [comment]
和 https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/131 重复了，近期会发布新版本更新，按照range排序，这个issue就Close了
