### ISSUE TITLE
同步的时候能不能不重新生成笔记，直接把更新加在原来的内容后面

### ISSUE THREAD

**Issue by asmoxuan** [zhaohongxuan/obsidian-weread-plugin#123]
希望能同步的时候把新划线或是笔记直接加在原有条目后面，而不是重新生成一遍，因为之前同步后，加了豆瓣等的信息，如果重新生成笔记这些自己添加的信息就没了。

**Comment by zhaohongxuan** [comment]
可以查看之前的issues，作为同步服务，这肯定是没法做的，因为没法保障原有的条目不变化，最好是把变化的部分记录在外部，双链到笔记本身。
