### ISSUE TITLE
无法同步 499

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#124]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/297531/213775206-35022f51-594a-4fa9-81c5-532ee2da8218.png">

VPN 关闭后，重新登陆，错误如下
<img width="624" alt="image" src="https://user-images.githubusercontent.com/297531/213775890-3c104c4a-708d-44ca-a394-3ae72278e03d.png">

**Comment by zhaohongxuan** [comment]
网络问题，这里不能提供解决方案
