### ISSUE TITLE
增加微读网页url的变量

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#127]
目前有个 book id 变量（如下），不知道有何用，不能组装出上面的URL

```
doc_type: weread-highlights-reviews
bookId: "25410985"
title: "精进：如何成为一个很厉害的人（新版）"
```
这本书的在线阅读的url为 https://weread.qq.com/web/bookDetail/70032c707183bda97009bba

希望能增加URL id（如上`70032c707183bda97009bba`)的变量，不知道weread目前是否支持。

**Comment by zhaohongxuan** [comment]
> 目前有个 book id 变量（如下），不知道有何用，不能组装出上面的URL
> 
> ```
> doc_type: weread-highlights-reviews
> bookId: "25410985"
> title: "精进：如何成为一个很厉害的人（新版）"
> ```
> 
> 这本书的在线阅读的url为 https://weread.qq.com/web/bookDetail/70032c707183bda97009bba
> 
> 希望能增加URL id（如上`70032c707183bda97009bba`)的变量，不知道weread目前是否支持。

不支持，现在接口没有返回网页版的id，这个id应该是一个私有算法生成的，现在也没法破解
