### ISSUE TITLE
能否增加个人对图书的评级？

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#128]

**Comment by zhaohongxuan** [comment]
可以的，在顶部的frontmatter里按照ymal语法设置即可。

**Comment by milla** [comment]
> 可以的，在顶部的frontmatter里按照ymal语法设置即可。

https://github.com/zhaohongxuan/obsidian-weread-plugin/wiki/Weread-obsidian-plugin-markdown-template-usage
貌似没有评级？
