### ISSUE TITLE
请教：奇怪的换行问题

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#133]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/297531/215302562-f0f87850-f000-440c-bb79-fb6c62234b59.png">

未解之谜，为什么有些有无故的换行，谁有遇到过吗？

**Comment by zhaohongxuan** [comment]
学习一下https://mozilla.github.io/nunjucks/templating.html的语法，自制模板需要注意，模板里的换行就是真的换行。
