### ISSUE TITLE
yaml不能自定义字段？

### ISSUE THREAD

**Issue by WuShaogui** [zhaohongxuan/obsidian-weread-plugin#134]
您好，我想在yaml区域自定义“是否读完”、“是否做笔记”，但是文件更新依据应该是“最后一次复习时间”，每次我修改原始笔记，点击同步，我自定义的yaml字典内容会被重置，能不能设置以下规则：

- 如果yaml区域内，对于那些使用metaData对象内容的字段，可以更新
- 如果没有使用metaData对象，则使用上一次内容，而不是设置为null

**Comment by zhaohongxuan** [comment]
你好，我自己测试了一下不会覆盖呀，像下面这样的
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/8613196/215381419-81bf1757-85c4-4201-80d5-42ad5afa1fd3.png">

**Comment by WuShaogui** [comment]
> 你好，我自己测试了一下不会覆盖呀，像下面这样的 <img alt="image" width="1116" src="https://user-images.githubusercontent.com/8613196/215381419-81bf1757-85c4-4201-80d5-42ad5afa1fd3.png">

你加的这个字段在模板里面吗？我再详细描述下我的使用过程：模板加上自定义字段"is_finished:"，值没填就是null。第一次同步，我拿到某本书的内容，此时is_finished=null，然后我手动将其改为true。后续我阅读书籍，又有新的笔记，此时我点击同步，is_finished变为null了，不再是我手动修改的true。

**Comment by zhaohongxuan** [comment]
> is_finished:

模板里不要加：is_finished，加了会覆盖
