### ISSUE TITLE
读书笔记同步至Daily Notes，划线评论部分的链接是错误的，显示“Unable to find section ... in xxx”

### ISSUE THREAD

**Issue by lleej** [zhaohongxuan/obsidian-weread-plugin#136]

**Comment by silentsky2billten** [comment]
同样的问题， 发现同步到Daily notes里面的ID 多了{{bookid}}，希望能修改。

**Comment by mmdzt** [comment]
发到Daily notes不成功，设置为## 标题1 至 ## 标题2时，目前只有Daily notes这两个标题内容中间不空行点击同步才有反应，而且反应是把我标题二给吞了。其他情况无反应

**Comment by lzsq520** [comment]
同样的问题

**Comment by Asura-one** [comment]
这个是因为有两个相同名称的文件，所以找不到链接部分。把文件路径实例就可以了

**Comment by zhaohongxuan** [comment]
评论目前还没添加到DailyNotes呢

**Comment by zhaohongxuan** [comment]
Duplicate with ： https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/117
