### ISSUE TITLE
能不能对同一段话的评论放在同一个三级标题下，而不是有一个评论就重新开一个三级标题。

### ISSUE THREAD

**Issue by Fenghaibo-git** [zhaohongxuan/obsidian-weread-plugin#137]
![image](https://user-images.githubusercontent.com/94052278/217206082-4243aada-db88-4343-950e-47c903fc1192.png)

**Comment by Fenghaibo-git** [comment]
还有一个问题就是：如果我在插件生成的文件下修改一些东西后，在下一次同步笔记时，修改的东西将被删除。

**Comment by Fenghaibo-git** [comment]
第一个问题是否可以通过给评论附上时间来判断这个是否要被修改。
第二个问题是否可以将自己补充的内容与被评论的这段话的id绑定起来，以避免误删除。
总的来说，是否可以修改同步笔记逻辑来达到这一点。

这个项目对于做笔记的帮助很大，我可以尝试加入一起完善这个项目吗？

**Comment by zhaohongxuan** [comment]
> 还有一个问题就是：如果我在插件生成的文件下修改一些东西后，在下一次同步笔记时，修改的东西将被删除。

不要在这个文档里修改除了顶部yaml文件数据以外的内容，会被覆盖掉，可以在外部引用这个blockId

**Comment by zhaohongxuan** [comment]
> 能不能对同一段话的评论放在同一个三级标题下，而不是有一个评论就重新开一个三级标题。
这个修改模板就行，默认的模板我也会修改一下
