### ISSUE TITLE
希望能支持图片同步；增量同步

### ISSUE THREAD

**Issue by Donge-wx** [zhaohongxuan/obsidian-weread-plugin#138]
有时候书中会有一些插图比较重要，需要同步下来，现在的话，同步过来只有“图片”两个字，希望后续能有这个功能。

或者希望能够增添一个选项，同步的时候，可以选择增量同步，覆盖同步的话，如果需要在之前笔记里面改动的话，就没法操作。

希望后续能加上。

**Comment by emmoblin** [comment]
确实，图片更新的功能非常重要，目前总是同步完后，还要手动截取图片把内容补齐。

不过微信读书app的导出功能本身就无法导出图片，技术上应该是无法做到现在。

**Comment by zhaohongxuan** [comment]
> 确实，图片更新的功能非常重要，目前总是同步完后，还要手动截取图片把内容补齐。
> 
> 不过微信读书app的导出功能本身就无法导出图片，技术上应该是无法做到现在。

通过API是无法做到了，看后面微信读书API的更新情况了
