### ISSUE TITLE
yaml链接产生多余的换行，bug情况和模板配置如图

### ISSUE THREAD

**Issue by KristineWatson** [zhaohongxuan/obsidian-weread-plugin#139]
在yaml插入了三次链接，三个key分别是cover、banner、gallery，目前看来是用语法 ![[]] 包裹链接就会出现多余换行，重复链接最后一小段
![87d8d460a64a2723445d7e0eb32e4b0](https://user-images.githubusercontent.com/92555979/221201677-f8d8c7bd-cdf8-47c7-83b9-1124b8efadb3.png)

![7503c5daacbb26cf3024bc6310c164f](https://user-images.githubusercontent.com/92555979/221202021-c0a45fff-e17d-4d9b-a9dc-777fd42c9bb6.png)

**Comment by zhaohongxuan** [comment]
这是obsidian自己的机制导致的
