### ISSUE TITLE
有个想法仅供参考：多种模式同步

### ISSUE THREAD

**Issue by kuangxi2017** [zhaohongxuan/obsidian-weread-plugin#140]
目前的同步笔记是每一本书一个笔记直接同步。
是否可以增加一种同步笔记的模式，即每一条划线或者评论为一个笔记，然后有一个书籍信息的主页链接所有其他划线笔记和评论笔记。这样就可以结合卡片笔记法来引用和复用同步的所有笔记。

**Comment by zhaohongxuan** [comment]
> 目前的同步笔记是每一本书一个笔记直接同步。 是否可以增加一种同步笔记的模式，即每一条划线或者评论为一个笔记，然后有一个书籍信息的主页链接所有其他划线笔记和评论笔记。这样就可以结合卡片笔记法来引用和复用同步的所有笔记。

可以，但是没有必要，个人认为笔记的联系一定要自己建立才是有效的，否则就是无效的联系。

**Comment by kuangxi2017** [comment]
> > 目前的同步笔记是每一本书一个笔记直接同步。 是否可以增加一种同步笔记的模式，即每一条划线或者评论为一个笔记，然后有一个书籍信息的主页链接所有其他划线笔记和评论笔记。这样就可以结合卡片笔记法来引用和复用同步的所有笔记。
> 
> 可以，但是没有必要，个人认为笔记的联系一定要自己建立才是有效的，否则就是无效的联系。

我同意，不过，我个人理解的同步只是一个汇总的过程，和整理建立联系是两个不同的步骤，我的想法是能更快的完成汇总的过程并为整理和建立联系提供更多的便利。另外，有一些联系可能是无意识地涌现出来的，并不是我们特意能组织出来的。

**Comment by milla** [comment]
没什么必要吧，增量管理好处是可以自己修改笔记，坏处当然不言自明，可以使用块插件来另外创建笔记。
