### ISSUE TITLE
我也想要增量同步/或者每次都彻底刷新

### ISSUE THREAD

**Issue by xieyingli** [zhaohongxuan/obsidian-weread-plugin#141]
当前的机制，删除的划线并不会在ob里也跟着删除

我有一本自己上传的图书，然后做了一个划线，然后我专门去测试了一下删除划线（这个时候这本书已经完全没有划线了），但是在ob里反复好几天还是没能把这个页面自动给删除，划线的段落也还在。

**Comment by zhaohongxuan** [comment]
> 当前的机制，删除的划线并不会在ob里也跟着删除
> 
> 我有一本自己上传的图书，然后做了一个划线，然后我专门去测试了一下删除划线（这个时候这本书已经完全没有划线了），但是在ob里反复好几天还是没能把这个页面自动给删除，划线的段落也还在。

现在的机制是根据划线数量和评论数量覆盖是更新的，如果原文中删除了，这里一定会删除的
