### ISSUE TITLE
如果将书籍从书架上删去是否也会导致obsidian中笔记删除呢？

### ISSUE THREAD

**Issue by 76563** [zhaohongxuan/obsidian-weread-plugin#148]
没太明白覆盖式更新，微信读书现在书架只有500的数量限制，如果书多了就需要将其删去，那这是否会影响obsidian中的笔记呢？

**Comment by 76563** [comment]
> > 没太明白覆盖式更新，微信读书现在书架只有500的数量限制，如果书多了就需要将其删去，那这是否会影响obsidian中的笔记呢？
> 
> 不是根据书架上的书来同步的，很多人的书都没在书架上的，不在书架上也不影响同步的。

感谢，那如果将微信读书中本地上传的图书删去后，是否会影响obsidian中的笔记呢？

**Comment by zhaohongxuan** [comment]
> > > 没太明白覆盖式更新，微信读书现在书架只有500的数量限制，如果书多了就需要将其删去，那这是否会影响obsidian中的笔记呢？
> > 
> > 
> > 不是根据书架上的书来同步的，很多人的书都没在书架上的，不在书架上也不影响同步的。
> 
> 感谢，那如果将微信读书中本地上传的图书删去后，是否会影响obsidian中的笔记呢？

按照微信读书的说明，本地上传的图书从书架删除之后，笔记也会清除，但是已经保存到Obsidian的笔记不受影响，除非自己删除。
