### ISSUE TITLE
Weread插件使用中的几个小需求

### ISSUE THREAD

**Issue by mengtanx** [zhaohongxuan/obsidian-weread-plugin#15]
首先非常感谢开发插件，使用非常方便，打通了我微信读书和Obsidian的通路。下面是两个我初步使用时的两个问题：

1. 希望支持自定义选择需要同步的书籍

我首次安装配置好后，一下同步进来几百本书有点吓人。过滤方式可以有以下几种：按照划线笔记的数量同步，比如设置一个阈值，只同步超过阈值数量的书，主要是有些随便翻翻没深入读的书。更进一步的话，支持按照 bookId 或 isbn 号来配置需要同步的书籍。不然就会同步过来如下图所示这样的无效笔记文件：

<img width="665" alt="image" src="https://user-images.githubusercontent.com/9440993/168515863-29ca92cc-cf45-44ad-ad28-e677d7560083.png">

2. 增加一些可配置化设置导入笔记样式的功能

比如，对我而言，每条高亮和笔记的创建时间其实没多大意义的，希望可以配置不导入。我反而会更关心我读这本书花了多久，什么时候读完的这类信息。

这块可以参考结合「微信读书笔记助手」这个 Chrome 插件，支持更多自定义笔记模板。

**Comment by zhaohongxuan** [comment]
@mengtanx  
1. 同步过滤功能未来会做，现在我这边也有很多无效的笔记，同时也会做分组功能，分类管理已读完的书籍和未读完的书
2. frontmatter元数据也会假如更多，方便使用dataviewjs进行归类整理
3. 笔记模板未来会开放出来，可以自己根据元数据生成自己的笔记
4. 书籍阅读时间这个元数据目前web端的API无法获取的，只有完成阅读的时间，没有开始时间

**Comment by mengtanx** [comment]
> @mengtanx
> 
> 1. 同步过滤功能未来会做，现在我这边也有很多无效的笔记，同时也会做分组功能，分类管理已读完的书籍和未读完的书
> 2. frontmatter元数据也会假如更多，方便使用dataviewjs进行归类整理
> 3. 笔记模板未来会开放出来，可以自己根据元数据生成自己的笔记
> 4. 书籍阅读时间这个元数据目前web端的API无法获取的，只有完成阅读的时间，没有开始时间

好的，期待新版本 😚
