### ISSUE TITLE
微信登录成功后，点击同步信息，报错token失效，重复登陆还是报错

### ISSUE THREAD

**Issue by hewking** [zhaohongxuan/obsidian-weread-plugin#151]
![image](https://user-images.githubusercontent.com/8760577/227754836-6dc3f46e-4b55-457a-a5a0-eaa60eaf38b5.png)

**Comment by zhaohongxuan** [comment]
重新扫码登录也不行吗？是在不行的话就把插件卸载了重新登录试试，我自己在macOS上测试，过了几个星期Cookie都会自动刷新的。

**Comment by georgeJzzz** [comment]
同样的报错

**Comment by he-cocefae** [comment]
一开始我也这样，然后我把登录的界面挂在
![image](https://user-images.githubusercontent.com/74971244/236098477-5ae8e746-ad0d-44fe-826a-a8e3e25dad4c.png)
这样没有显示头像，点进书架
![image](https://user-images.githubusercontent.com/74971244/236098550-51fcbc66-8fe6-4952-af58-9037adbec6ef.png)
显示了头像后，点击同步的图标，然后就解决了

**Comment by georgeJzzz** [comment]
> 一开始我也这样，然后我把登录的界面挂在 ![image](https://user-images.githubusercontent.com/74971244/236098477-5ae8e746-ad0d-44fe-826a-a8e3e25dad4c.png) 这样没有显示头像，点进书架 ![image](https://user-images.githubusercontent.com/74971244/236098550-51fcbc66-8fe6-4952-af58-9037adbec6ef.png) 显示了头像后，点击同步的图标，然后就解决了。 之后就直接可以同步了

试了呢  没用 还是报错

**Comment by he-cocefae** [comment]
你试试不要关闭窗口，最小化。我是这样解决的.....

**Comment by he-cocefae** [comment]
> > 一开始我也这样，然后我把登录的界面挂在 ![image](https://user-images.githubusercontent.com/74971244/236098477-5ae8e746-ad0d-44fe-826a-a8e3e25dad4c.png) 这样没有显示头像，点进书架 ![image](https://user-images.githubusercontent.com/74971244/236098550-51fcbc66-8fe6-4952-af58-9037adbec6ef.png) 显示了头像后，点击同步的图标，然后就解决了。 之后就直接可以同步了
> 
> 试了呢 没用 还是报错

我现在复现出了，但是我是没有把这个窗口关闭的，要不你试试。不然我也不知道怎么办.......
