### ISSUE TITLE
问题：我的书架书籍分组框不能点击

### ISSUE THREAD

**Issue by Twenru-zzh** [zhaohongxuan/obsidian-weread-plugin#152]
win10
ob：v1.1.16
weread-plugin：0.4.10

微信读书首页有登陆图标，下方书籍可以正常跳转点击
![image](https://user-images.githubusercontent.com/84758016/228486031-d7ed1620-bed7-453f-81c5-2d00dadf7098.png)

我的书架页面无登录图标，下方书籍可以正常点击，但是分组不能正常点击跳转
![image](https://user-images.githubusercontent.com/84758016/228486392-08352445-c008-45a7-a1fa-a12530b48f19.png)

**Comment by Twenru-zzh** [comment]
刚又去试了一下，ob和插件都是最新

就是下图1中红色部分单独书籍是可以正常点击打开的，但是黄色部分分组书籍不能正常点击进入如图二的分组页面

![屏幕截图 2023-04-12 121849](https://user-images.githubusercontent.com/84758016/231348692-476e8256-36e0-4f60-bc80-d9dbbe01c898.png)

![屏幕截图 2023-04-12 122010](https://user-images.githubusercontent.com/84758016/231348868-4bd0db96-6605-4237-812f-951bcee23ca2.png)

**Comment by Twenru-zzh** [comment]
另外在插件中我的书架界面，头像没有显示，且点击头像没有对应选项弹出；在首页是界面是正常的

**Comment by zhaohongxuan** [comment]
> 另外在插件中我的书架界面，头像没有显示，且点击头像没有对应选项弹出；在首页是界面是正常的

是无法登录吗？这个插件没有在线阅读的功能

**Comment by Twenru-zzh** [comment]
选项设置里可以登录，和在线阅读应该没有关系。我应该表述的应该很清楚啊，我想可能是我自己插件冲突引起的点击失效吧，对使用的影响并不大。
