### ISSUE TITLE
反馈：同步成功了，但只生成了文件夹，没有md文件

### ISSUE THREAD

**Issue by hormoyo** [zhaohongxuan/obsidian-weread-plugin#157]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/13670918/232446137-a393a71f-027a-4baf-b101-24a5e401df39.png">
如图。
已经卸载过一次重新安装，还是这样。不知道大佬这个怎么解决呢？

**Comment by mmdzt** [comment]
+1

**Comment by mmdzt** [comment]
报错如图：
<img width="534" alt="image" src="https://user-images.githubusercontent.com/90957271/234319031-a9a2aee9-4fa8-43a7-9956-91a0fa288069.png">

**Comment by mmdzt** [comment]
@zhaohongxuan

**Comment by zhaohongxuan** [comment]
是不是都是自己上传的书？我本地没法重现。

**Comment by mmdzt** [comment]
> 是不是都是自己上传的书？我本地没法重现。

是自己上传的书，但是当时好像给文件夹分类按照书名分类出现了这个问题。另外当时的metadata里加入了`cover: >- ![ {{metaData.title}}|200]({{metaData.cover}})`。后来删掉了之后，问题就解决了。
