### ISSUE TITLE
0.1.12版本，cookie存储的长度不够，导致丢失部分cookie信息

### ISSUE THREAD

**Issue by johnsonzx** [zhaohongxuan/obsidian-weread-plugin#16]
![image](https://user-images.githubusercontent.com/14848815/168580211-ba64ede9-7add-42f4-8df4-d476728032b7.png)
cookie的字符较多时，会截断并丢弃部分内容

**Comment by zhaohongxuan** [comment]
@johnsonzx 截断只是一个显示问题，我这边测试功能没问题 ![iShot_2022-05-16_19 26 33](https://user-images.githubusercontent.com/8613196/168582829-92fb991e-2f20-4ff3-94fb-755f37ee08e0.gif)

**Comment by johnsonzx** [comment]
是的  跟ob的theme也有关系  功能本身是没有问题的
