### ISSUE TITLE
请问如何区别「高亮划线」里的「书签」和「划线」？

### ISSUE THREAD

**Issue by colakuma** [zhaohongxuan/obsidian-weread-plugin#160]
现在插件的「高亮划线」应该是对应着微信读书里的「笔记」，但是微信的「笔记」是包含「书签」和「划线」两类的。
就我个人的情况来说，书签没有什么意义，而划线是有意义的。有没有办法只筛选出划线的内容？

**Comment by zhaohongxuan** [comment]
> 现在插件的「高亮划线」应该是对应着微信读书里的「笔记」，但是微信的「笔记」是包含「书签」和「划线」两类的。 就我个人的情况来说，书签没有什么意义，而划线是有意义的。有没有办法只筛选出划线的内容？

API中高亮划线中不包含「书签」数据的，并不会被同步到Ob中
