### ISSUE TITLE
文件夹分类或者metadata能否添加读书的进度？

### ISSUE THREAD

**Issue by mmdzt** [zhaohongxuan/obsidian-weread-plugin#161]
导入微信读书里“进度”一栏：尚未开始、刚开始读、正在阅读、已读完。

因为想在主页显示自己正在读的书

**Comment by mmdzt** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/90957271/235412210-c577edaa-2f75-4b88-936e-5be1b72b8ceb.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/90957271/235412227-6c6c1e73-f7b9-4a5f-88da-214a867e1536.png">
目前，reviewCount、noteCount、finish都是null。阅读的是自己上传的书。

**Comment by mmdzt** [comment]
@zhaohongxuan 谢谢

**Comment by zhaohongxuan** [comment]
官方API没有返回阅读状态，状态可以手动添加到顶部的frontmatter中
