### ISSUE TITLE
可否支持高亮类型？

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#162]
目前weread支持更多颜色的高亮，不同高亮笔记有不同含义，希望能够支持label的形式来标注高亮，类似 #green , #red, #yellow 等，最好能够支持自定义的mapping, 比如 #milla_green, #milla_red ：）

Thanks

**Comment by Moyf** [comment]
（0.5.5 更新后)[https://github.com/zhaohongxuan/obsidian-weread-plugin/releases/tag/0.5.5] 已经支持了！

用法：
在模板的高亮位置插入 `highlight.colorStyle` （会得到代表不同颜色的数字）并按需替换成其他文本。

比如这段：
```css
{{highlight.colorStyle | replace("5", "🟨" ) | replace("1", "🟥" ) | replace("2", "🟪" ) | replace("3", "🟦" ) | replace("4", "🟩" ) }} 
```

会把颜色显示成不同颜色的方块，你把方块 Emoji 换成自己的 #colorLabel 就可以啦。
