### ISSUE TITLE
可否修改category为嵌套标签

### ISSUE THREAD

**Issue by moleve** [zhaohongxuan/obsidian-weread-plugin#163]
将原先获取的 `{{category}}` 分类
```
tag:
  - 历史-历史读物
```
修改为 
```
tag:
 - 历史/历史读物
 ```

以便更好的利用obsidian的嵌套标签功能

**Comment by palwoo** [comment]
不能同意更多。^_^

**Comment by zhaohongxuan** [comment]
这个功能可以使用nunjucks的语法来实现，
`tags: {{ "metaData.category | replace("-", "/") }}`
或者如果你想要tag前面再加上微信读书的总分类也可以实现：
`tags: {{ "微信读书/" ~ metaData.category | replace("-", "/") }}`

详细的使用方法可以参考：https://mozilla.github.io/nunjucks/templating.html
