### ISSUE TITLE
功能期望：希望分组功能有根据自定义分组（书架页上的自定义分组名）

### ISSUE THREAD

**Issue by chenbihao** [zhaohongxuan/obsidian-weread-plugin#165]
RT，希望分组功能有根据自定义分组（书架页上的自定义分组名）

例如：
希望能根据自定义分组名称进行分组，感激不尽！
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/21167262/ccabeae6-0057-4f19-b406-87a937b7ad91)

**Comment by zhaohongxuan** [comment]
书架的属性是可变的，书可以不放在书架上的，而且每次都要把数据全部扫一遍，这样不符合同步的场景。
