### ISSUE TITLE
无法同步到Daily Note

### ISSUE THREAD

**Issue by SnakeHit** [zhaohongxuan/obsidian-weread-plugin#169]
<img width="904" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/45898625/5e3da857-5d99-4a1e-9791-b18822ff3b4a">
<img width="820" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/45898625/8cd114bf-00ca-4b74-a50a-a5f104f11ce9">
<img width="1456" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/45898625/3ce0afad-3ef9-45c5-b3d4-3e65e8e9e4b2">

**Comment by zhaohongxuan** [comment]
把控制台的log贴出来吧，不然也看不出什么问题

**Comment by SnakeHit** [comment]
<img width="756" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/45898625/8f759783-c50d-4bbc-b37e-f4a6b75fe10c">

**Comment by zhaohongxuan** [comment]
区间改成别的试试，我自己用你的配置实验是可以的。

**Comment by chenlee1990** [comment]
同样遇到这个问题，请问楼主解决了么？

**Comment by snipersteve** [comment]
我进一步测试后发现，微信自带书籍可以同步到daily里，而自己传的书则不行。

**Comment by snipersteve** [comment]
另外我发现daily里只能同步划线内容，而不能同步笔记。显示Unable to find section。

**Comment by chenlee1990** [comment]
这个问题可以结合dataview插件来解决。在作者没有优化的前提下，可以用来替换使用
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/38813436/6c0884e0-55f9-42a1-b94f-9cb58c8a7c36)

**Comment by snipersteve** [comment]
> 这个问题可以结合dataview插件来解决。在作者没有优化的前提下，可以用来替换使用 ![image](https://user-images.githubusercontent.com/38813436/257761965-6c0884e0-55f9-42a1-b94f-9cb58c8a7c36.png)

感谢，dataviewjs的方案挺不错的。

**Comment by peanut996** [comment]
> 

测试了一下 只有书架上公开的书才能同步到daily note， 自己上传的不行。这个算bug吗 🤣

**Comment by peanut996** [comment]
最新版修复了这个问题， 可以试试看
