### ISSUE TITLE
同步异常！求助求助！

### ISSUE THREAD

**Issue by Zouz-code** [zhaohongxuan/obsidian-weread-plugin#172]
obsidian版本 1.3.5
插件版本 0.5.1
cooke成功授权
微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'replace')
    at eval (plugin:obsidian-weread-plugin:2:316063)
    at Array.map (<anonymous>)
    at eval (plugin:obsidian-weread-plugin:2:315637)
    at x.eval (plugin:obsidian-weread-plugin:2:316103)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-weread-plugin:2:303926)
e

@zhaohongxuan

**Comment by zhaohongxuan** [comment]
能提供是哪一本书报错的吗？

**Comment by Zouz-code** [comment]
怎么看是那本书报错呀？我是第一次使用这个插件，然后试了很多次，都没有成功同步过。一本都没有同步成功

**Comment by bulletRush** [comment]
+1

**Comment by Zouz-code** [comment]
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79613113/14c5d117-e0b6-4137-8c21-0555a9ecdcac)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79613113/c5458ec9-5d48-4dc6-b13d-17e225880e30)

**Comment by bulletRush** [comment]
@Zouz-code 可以在release页面下载老版，安装方式见：https://www.cnblogs.com/zd2021/articles/15410243.html

**Comment by Zouz-code** [comment]
@bulletRush 我刚刚试了，用0.4.10，还是不行。。
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79613113/63acb814-91b2-4149-bafc-68d5c6f09c3c)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79613113/057abe28-2aa7-4fc5-8094-42c2bb1bd505)
会不会是插件冲突吖。
我用了这些插件
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79613113/8b48555b-4457-43f6-b8d7-ae5ada7f4ee0)
@zhaohongxuan  大佬，有时间帮忙看看吗？

**Comment by MaxYu2** [comment]
我这边也复现了同样的问题

**Comment by zhaohongxuan** [comment]
大概率是自己上传书籍的问题，这两天抽空fix一下
