### ISSUE TITLE
同步的白名单功能

### ISSUE THREAD

**Issue by KevinLiangX** [zhaohongxuan/obsidian-weread-plugin#173]
设置里面 有没有 白名单功能，假如最近再读一本书，只同步这本书的信息， 其他的不进行同步。

**Comment by zhaohongxuan** [comment]
如果只读了一本书，的确只会同步这一本书呀，不明白白名单存在的意义是什么，目前只有黑名单的功能，因为只要同步就会调用接口查询所有的书，白名单对性能没有提升。
