### ISSUE TITLE
笔记保存到DaliyNotes时，引用的ID与实践的ID不一致，多了一个图书的ID，导致无法正常展示。

### ISSUE THREAD

**Issue by musicleaf** [zhaohongxuan/obsidian-weread-plugin#177]
笔记保存到DaliyNotes时，引用的ID与实践的ID不一致，多了一个图书的ID，导致无法正常展示。

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/056f918a-7cd5-4f71-8278-aa40ebf274b8)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/daddcc76-068a-4f23-878f-411c87922b6e)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/279e0f04-8c2d-412e-a102-5654be04dd5a)
去掉书名ID后可以正常展示，希望修复。
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/c9609363-79f6-4cf0-995a-ebd98ad2597e)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/eb55f8c8-467f-4ed1-a540-acdc577f6a50)

遇到通用的问题，参考地址：https://github.com/zhaohongxuan/obsidian-weread-plugin/discussions/175

采用的是书名-作者的模板

**Comment by zhaohongxuan** [comment]
DailyNote功能适用于默认模板，修改了模板就不能用了，因为代码不会知道，blockId到底是什么

**Comment by mal5338** [comment]
> DailyNote功能适用于默认模板，修改了模板就不能用了，因为代码不会知道，blockId到底是什么

请问您说的模版是指DaliyNote模版还是微信读书笔记的模版？

**Comment by zhaohongxuan** [comment]
和  https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/177  重复了
