### ISSUE TITLE
笔记 ID 显示的Bug

### ISSUE THREAD

**Issue by xxhk-org** [zhaohongxuan/obsidian-weread-plugin#179]
如下图所示，在同步完成后，笔记后面由倒三角引导的ID（{{bookReview.reviewId}} 和 {{review.reviewId}} ），有时候显示成上标，有时候显示成普通字符。

卸载重装后，使用默认的模板也会这样。

作为微信读书的重度用户，非常感谢你能开发这么好用的插件，谢谢~

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/9914772/24eb7aeb-14da-4353-8a0c-f33f1583bbda)

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/9914772/91205474-bd0b-40fc-9b4b-80f00dbe4548)

**Comment by zhaohongxuan** [comment]
BlockId是符合Obsidian规范的，看上去应该是Obsidian自己的Bug，这里不能重现，升级Obsidian试一试
<img width="1465" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/8704e6b3-9528-4a76-ac73-97d89b4ae8b7">
