### ISSUE TITLE
0.1.13  failed to load 

### ISSUE THREAD

**Issue by johnsonzx** [zhaohongxuan/obsidian-weread-plugin#18]
感谢更新，我这里发现该版本的插件无法被obsidian启用
![image](https://user-images.githubusercontent.com/14848815/168728698-5ebec91b-20fe-4c5d-8461-f597a1dc364e.png)

macOS： 12.3.1；
obsidian：0.14.6

**Comment by zhaohongxuan** [comment]
express打包没打进去，重新打了~再试一下

**Comment by johnsonzx** [comment]
ok啦 感谢fix
