### ISSUE TITLE
关于笔记模板变量需求highlight.createTime希望有个highlight.createData

### ISSUE THREAD

**Issue by jaycamu** [zhaohongxuan/obsidian-weread-plugin#180]
我只希望有个关联用[[highlight.createData]]，日记那边只要看到今天做了哪些笔记就可以了

**Comment by zhaohongxuan** [comment]
这个功能已经有了的，是反向引用笔记中的内容
<img width="1156" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/218f0c2a-646e-4814-9b98-e00eed29d9d5">
<img width="1159" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/67490852-f95e-48c5-a639-71b49a641688">
