### ISSUE TITLE
功能期望：将笔记同步至DailyNotes时，可以自定义模板

### ISSUE THREAD

**Issue by Nemo137-Liang** [zhaohongxuan/obsidian-weread-plugin#184]
目前同步至DailyNotes的笔记，书名标题默认为三级标题，无法自定义修改。希望可以支持自定义的功能。

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/60751406/797db9df-8286-405f-ba1b-3225e7cc90aa)

**Comment by jaycamu** [comment]
<img width="255" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/44602682/c245c63f-fb34-4440-ac6a-9f6f08c3dbe5">
这个部分的模板是怎么写的？我想要日期，但是不要时间

**Comment by zhaohongxuan** [comment]
这个功能上模板就太重了，应该不会做
