### ISSUE TITLE
同步异常

### ISSUE THREAD

**Issue by juvey** [zhaohongxuan/obsidian-weread-plugin#186]
<img width="584" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4383344/8b71ab14-dd07-404e-8da5-9799ca004fae">

更新后出现的

**Comment by ichigomikako** [comment]
控制台在哪调出来的

**Comment by ichigomikako** [comment]
我也是

**Comment by benjam1nryan** [comment]
最新版本报错+1，希望作者大大关注一下

**Comment by MaxYu2** [comment]
我也是啊啊啊啊啊

**Comment by zhaohongxuan** [comment]
bug已经在修了，最近会发布新版

**Comment by zhaohongxuan** [comment]
新版已经发布了，有空可以测试一下，有问题可以在这里反馈。

**Comment by IOSure** [comment]
> 新版已经发布了，有空可以测试一下，有问题可以在这里反馈。

刚刚更新，同步了一下，没有任务问题，非常快速同步完成。谢谢！！！

**Comment by llinfeng** [comment]
请问出现如下情况，是否需要想办法手动清空 Obsidian 自带浏览器的 Cookie？已经尝试了删除plugin并重装，以及退出微信登录，再重新登陆。

PS: 我的Obsidian Vault是通过Dropbox同步，当前问题在两台 Windows 设备上均出现，具体情况如下：

1. 在点击同步之后，会有这一串通知：
![image](https://github.com/user-attachments/assets/2e558409-e092-4fb4-bbed-cb9564bb9fe1)


2. 在console里面，会看到下面的报错内容。

![image](https://github.com/user-attachments/assets/77a2b3df-4dc3-4ea6-960b-933e37bda63d)
