### ISSUE TITLE
功能期望：文件名模板希望增加“最后阅读时间—文件名—作者”的方式

### ISSUE THREAD

**Issue by Cenho** [zhaohongxuan/obsidian-weread-plugin#187]
希望在文件名上增加最后阅读时间字段用于辨识书籍的阅读时间

**Comment by zhaohongxuan** [comment]
这个使用Dataview 应该可以完成吧，不明白添加到文件名上的意义。。

**Comment by seyeeL** [comment]
希望文件名模版可以像内容模版一样定义，因为我想 《书名》，即加上书名号

**Comment by Cenho** [comment]
> 这个使用Dataview 应该可以完成吧，不明白添加到文件名上的意义。。

主要是希望用在文件排序管理上呢，有点类似Obsidian卡片日志命名方式
