### ISSUE TITLE
同步不完整

### ISSUE THREAD

**Issue by jackyouee** [zhaohongxuan/obsidian-weread-plugin#190]
有些书同步不完整, 看obsidian 部分书籍缺少元数据, 同步就直接跳掉高亮划线, 划线评论同步也不完整, 其它有元数据的书则同步正常.
MAC OS12.6.5
Obsidian 1.3.7
Weread Plugin 0.5.0

![截屏2023-08-17 13 41 30](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/59171390/6628d874-fcde-4c8f-8a97-7b4a87f24654)
![截屏2023-08-17 13 41 43](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/59171390/6f5ebfb7-9eaa-43ff-8b45-ac69a998815b)

**Comment by zhaohongxuan** [comment]
这个bug我不能复现，建议更新到0.5.3之后试一下

**Comment by jackyouee** [comment]
把weread 版本退回到 0.4.4, 终于同步完整了. 只是后面的新功能用不上了

**Comment by zhaohongxuan** [comment]
定位到原因了，如果评论中出现`---` 字符就会导致不完整，将会在下个版本修复，https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/213
