### ISSUE TITLE
在设置中增加白名单设置，只同步指定的书籍

### ISSUE THREAD

**Issue by IOSure** [zhaohongxuan/obsidian-weread-plugin#191]
在设置中增加白名单设置，只同步指定的书籍。或者只同步在“书架”上的书籍。

微信读书不仅仅作为阅读平台，而且作为搜索平台，平常搜索指定的知识点，也会到找到的书籍中做画线或者高亮。必然微信读书中的需要同步的内容很多，而需要做读书笔记的，一般就是“书架”上的书籍，或者精读的书籍。

如果需要同步的内容很多的情况下，当前我使用Weread插件同步内容就没有成功，出现了 #186 和 #132 的问题。

所以希望增加白名单设置，只同步指定的书籍。或者只同步在“书架”上的书籍。

谢谢！！！

**Comment by zhaohongxuan** [comment]
https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/186 和 https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/132 已经修复
