### ISSUE TITLE
同步异常

### ISSUE THREAD

**Issue by MaxYu2** [zhaohongxuan/obsidian-weread-plugin#192]
plugin:obsidian-weread-plugin:2 同步微信读书笔记异常 Error: get weread note book error after retry
    at _.eval (plugin:obsidian-weread-plugin:2:321044)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-weread-plugin:2:303926)e

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/101554488/d3cdd15e-01c9-471e-8ab7-9ccf55dfefe7)

**Comment by zhaohongxuan** [comment]
<img width="752" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/4481c766-31b2-4481-9786-452e3f6390d1">
force reload一下试试
