### ISSUE TITLE
出现了同步不完整的情况

### ISSUE THREAD

**Issue by sean25xiao** [zhaohongxuan/obsidian-weread-plugin#196]
书库里的第四本书，出现了同步不完整的情况，只有划线评论过的笔记被同步，划线未同步的笔记没有同步过来
![Screenshot 2023-08-27 005322](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/31372975/5d41dadf-422e-44bd-a626-2d84ff2073cd)

**Comment by sean25xiao** [comment]
Windows 10 Home, version: 22H2
Obsidian: v1.4.4
Weread: 0.5.3

**Comment by jackyouee** [comment]
我也出现同样情况, 困扰我好久, 把weread 版本退回到 0.4.4, 终于可以同步完整了.

**Comment by zhaohongxuan** [comment]
issue重复，参考这个issue：https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/213
