### ISSUE TITLE
从8月22日起同步失败

### ISSUE THREAD

**Issue by jht897** [zhaohongxuan/obsidian-weread-plugin#197]
从8月22日起更新/同步不了新阅读+划线书籍。提示有更新，但实际没有更新出来
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/50199088/601e1c08-cb3b-4181-8d74-2ba1b6e5ac63)

**Comment by stellalong** [comment]
我刚刚更新插件后就同步成功了

**Comment by jht897** [comment]
今天同步成功了。
