### ISSUE TITLE
批注格式问题

### ISSUE THREAD

**Issue by SeyeeL** [zhaohongxuan/obsidian-weread-plugin#20]
![image](https://user-images.githubusercontent.com/71479570/168949303-2e361f8b-1ee6-4a69-bbb2-50521bde8521.png)
1. 因为微信读书可以针对整个页面或者某个章节写评论，这种情况可能就没有高亮，可以做个判断如果正文为空去掉上面那个节点嘛？
2. 我把标签写在想法里，同步后点击tag，ob搜索结果不展示，但是我手动复制一遍，就可以搜到了，不知道是ob的问题还是插件的问题

**Comment by zhaohongxuan** [comment]
刚刚release了 0.1.14，优化了默认模板，还支持了自定义模板，可以看这里的release说明下载使用 [https://github.com/zhaohongxuan/obsidian-weread-plugin/releases/tag/0.1.14](https://github.com/zhaohongxuan/obsidian-weread-plugin/releases/tag/0.1.14)

**Comment by SeyeeL** [comment]
太棒了，晚点试一下，那第二点呢，你试一下看能不能复现

**Comment by SeyeeL** [comment]
我的阅读记录那个tag是在微信读书里写了然后同步过来的

**Comment by zhaohongxuan** [comment]
@SeyeeL 
1. 整个页面的评论和整本书的评论目前还没加进来，下一个版本会加进来，现在只有划线评论
2. 微信读书里的写 tag，我在obsidian使用是正常的，点击就会正常显示。
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/8613196/168961288-1cec883a-231d-4218-a8ac-0818bbf7fe5e.png">

**Comment by SeyeeL** [comment]
不是啊，我这条就是从微信读书同步过来的，已经支持了。

**Comment by SeyeeL** [comment]
最新版的章节评论确实没有了。。期待更新

**Comment by SeyeeL** [comment]
速度也太快了吧，明天更新，感谢感谢

**Comment by SeyeeL** [comment]
![image](https://user-images.githubusercontent.com/71479570/169185019-bac8ccf6-03ea-4a9f-a073-c22aaf85c216.png)
更新到0.1.15了，还是没有出现以前那个版本的数据诶

**Comment by zhaohongxuan** [comment]
> ![image](https://user-images.githubusercontent.com/71479570/169185019-bac8ccf6-03ea-4a9f-a073-c22aaf85c216.png) 更新到0.1.15了，还是没有出现以前那个版本的数据诶

@SeyeeL  你是指针对页面，没有划线的的评论吗？我这边测试显示正常的，无划线评论默认会显示页面的摘要。
<img width="991" alt="image" src="https://user-images.githubusercontent.com/8613196/169222356-545b0dbe-117c-46e9-899f-5747a429ab4d.png">

**Comment by SeyeeL** [comment]
我用了另外一个issue的模板有了

**Comment by SeyeeL** [comment]
之前那个tag问题也好了

**Comment by SeyeeL** [comment]
不知道是不是我今天调模板同步太多了，现在同步本书不全了。原本以为是限制了3有问题，但是改成无限制也回不去了。
