### ISSUE TITLE
希望能自定义同步到日记里面的模板

### ISSUE THREAD

**Issue by hymnly133** [zhaohongxuan/obsidian-weread-plugin#201]
希望能自定义同步到日记里面的模板，并且日记同步中出现的Unable to find section #^** in ** 问题，是因为日记中的引用有书籍id，而书籍笔记里的字段没有，可通过自定义解决。

另有自己上传的图书无法同步在日记中的问题，可能也与id或者模板有关。
希望可以添加该功能。

**Comment by zhaohongxuan** [comment]
这个违背了Obsidian的初衷了，应该不会开发
