### ISSUE TITLE
文件夹分类希望能加上按照年份分类

### ISSUE THREAD

**Issue by littleyz** [zhaohongxuan/obsidian-weread-plugin#203]
如题，现在的文件夹分类主要是按照书名和图书分类，希望能加上按照时间，比如阅读完时间（年度）分类的功能。这样就能比较好的在左侧文件夹列表里展示这一年阅读的所有书籍。这个展示效果比用Dataview展示要好。

**Comment by zhaohongxuan** [comment]
阅读完成时间这个可能会变，阅读状态可以手动标记，因此作为分类不太稳定，所以应该不会支持。

**Comment by littleyz** [comment]
> 阅读完成时间这个可能会变，阅读状态可以手动标记，因此作为分类不太稳定，所以应该不会支持。

明白了，感谢回复！

**Comment by zhaohongxuan** [comment]
阅读进度数据已经添加到frontmatter，可以自己使用dataview来搭建自己的读书主页了

<img width="865" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/2773b808-7d44-46ea-ac8a-635e16b3b610">

**Comment by littleyz** [comment]
Good!
