### ISSUE TITLE
评论的引用

### ISSUE THREAD

**Issue by qianxun321** [zhaohongxuan/obsidian-weread-plugin#204]
想问一下可以给评论加一个id吗，如果可以的话这里应该怎么写呢？
<img width="334" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/62331870/09d09f58-ff71-4b34-b176-897c2d751b22">

**Comment by zhaohongxuan** [comment]
最好不要自己拼接ID，因为是覆盖式更新
