### ISSUE TITLE
ob最新版本v1.4.12 更新之后，无法安装微信阅读插件

### ISSUE THREAD

**Issue by wyz2gh** [zhaohongxuan/obsidian-weread-plugin#205]
如下图所示：
obsidian更新到 v1.4.12 之后，大批插件无法使用，其他插件卸载重装之后正常。
但微信阅读插件无法安装，仅提示“无法安装”，没有其他错误提示。

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/32699254/12e67ba8-eb3d-4f4a-b395-1a27b7fca53a)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/32699254/57be5e6a-7b53-4841-add4-241b5923b04c)

**Comment by balabalabalading** [comment]
我是首次安装，也遇到了这样的问题

**Comment by zhaohongxuan** [comment]
应该是昨天晚上更新了版本，忘记打release包了，现在新的0.5.4 release包已经发布了，重新重装试一下。

**Comment by wyz2gh** [comment]
> 应该是昨天晚上更新了版本，忘记打release包了，现在新的0.5.4 release包已经发布了，重新重装试一下。

已经可以正常安装使用，问题已经解决，谢谢！
