### ISSUE TITLE
划线高亮之后存在bookid

### ISSUE THREAD

**Issue by Luciushy** [zhaohongxuan/obsidian-weread-plugin#209]
每个划线高亮之后都有一段bookid，导出任何格式都依然存在，我使用的是[这位](https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/116)的模版配置。
[Obsidian](https://photos.google.com/lr/photo/AHuQZ2RoJIONkwsJqcTRNxPP4pOB07CvubO2gibDVFUJuBWRaKITuLw3jb1LE8SjJwlJesl7ozZm-KZVcZq_LVyBGfJ3TFFVpQ)
[导出MD文件](https://photos.google.com/lr/photo/AHuQZ2RNTxe1Y1uMiSS0D5PhpHbM4-2ncw_f6KxJ5l6kZGhol81HLqmhC4XRpebSUYP1T6m7q89vXqzpenrW2LktdMlSYinwHA)
请问，这个问题能解决吗？如何解决？

**Comment by zhaohongxuan** [comment]
看不到图片。。

**Comment by zkyken** [comment]
![1696587719514](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/36683743/e936a1d8-54de-4e83-847e-f44cae902eeb)
![1696587759425](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/36683743/afe23064-7b5b-4eb7-922d-9f50659305db)
![1696587797995](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/36683743/12c7f96b-ab5d-4e83-8099-8f280572c679)

**Comment by zhaohongxuan** [comment]
作为blockid，bookid是必须的，因为要从别的地方链接过来，图片中标注的是自己上传的书籍id，不能删掉
