### ISSUE TITLE
目录抓取不完整

### ISSUE THREAD

**Issue by PupupupuTong** [zhaohongxuan/obsidian-weread-plugin#210]
只有最低的一层目录，缺失上级目录。

https://github.com/sancijun/weread-toolbox#readme

用过这个插件，能抓取到完整目录以及图片笔记，提供给大佬参考

**Comment by PupupupuTong** [comment]
才发现好像之前已经提过一次了。。。抱歉抱歉，没有催促的意思，只是因为我经常读大部头书籍，下方的低级目录往往会出现重复，目录树看起来就成了这样

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/69069739/d80ceb53-ec22-4f95-a188-02de46c12b45)

实在难以起到定位作用……

**Comment by zhaohongxuan** [comment]
现有设计里没有调用章节API，是以highlight和annotations为核心的，如果要补全章节信息，可能改动的地方有点大，花费的时间比较多，所以迟迟没有动手写。。

**Comment by zhaohongxuan** [comment]
这个PR里增加了开关，可以现实所有的章节信息了，参考：https://github.com/zhaohongxuan/obsidian-weread-plugin/pull/245
