### ISSUE TITLE
[FR] 是否可以考虑增加高亮的颜色信息？

### ISSUE THREAD

**Issue by Moyf** [zhaohongxuan/obsidian-weread-plugin#211]
## Feature Request 说明
是从隔壁[五彩](https://www.dotalk.cn/product/wucai?utm_source=3C)插件得到的灵感，那边的高亮颜色在导入 Obsidian 作为笔记的时候会用一个小方块来表示原来的颜色：
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4013062/65198906-d2bc-4937-9c1e-d5a9f27e989c)

同理，是不是也可以把微信读书的颜色给映射成几种不同颜色的 Emoji？
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4013062/09906172-1ddc-4806-8314-73ae13fbd0c9)

将这个「颜色字符」作为新的模板参数加入的话，就可以做到同样的效果了！

比如用  `{{ highlight.colorEmoji }}` 来代表这个「颜色字符」，只需要用户修改模板把原来的 📌 Emoji 换掉就可以实现：
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4013062/95488369-a975-4da5-92d0-e746098ef01e)

---

尝试做了一些探索，发现微信的 highlight 是带有这个信息的：
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4013062/b00de723-930c-4d2c-8ddb-7a61f9df2ff0)

这个参数从1~5就代表5种不同的颜色，都能找到对应的 Emoji 字符：
* 1 红色 🟥
* 2 紫色 🟪
* 3 蓝色 🟦
* 4 绿色 🟩
* 5 黄色 🟨

可惜我还不会 Obsidian 的插件编程，暂时只能提 FR 了，希望能得到开发 ❤️️

**Comment by zhaohongxuan** [comment]
添加颜色倒是不难，就是markdown原生不支持颜色，需要用HTML标签才能支持，比如把字体标注成绿色
`<font color = "#00ff00"> test</font>`, 有侵入性，会破环原生的划线文本。
不过，后面会把color字段透出来，如果需要的话可以修改模板实现这个功能。

**Comment by Moyf** [comment]
> 添加颜色倒是不难，就是markdown原生不支持颜色，需要用HTML标签才能支持，比如把字体标注成绿色 `<font color = "#00ff00"> test</font>`, 有侵入性，会破环原生的划线文本。 不过，后面会把color字段透出来，如果需要的话可以修改模板实现这个功能。

嗯嗯，我也不喜欢那种侵入式的修改颜色……感觉 *太不 markdown* 了。

所以希望的是把颜色数据映射成一个 emoji 字符，放进模板里，这样用户可以把这个**代表颜色的字符**放在任意位置——来提示「这段引用是啥颜色的」，嘿嘿，同时也不会破坏文本原来的内容。

（感觉就把 color 作为 1~5 的数字传出来然后用模板的替换功能也可以？那样自由度好像更高一些）

期待！

**Comment by Moyf** [comment]
OHHHHH 太棒了！感谢开发！ 🌹
