### ISSUE TITLE
划线评论过长就会出bug

### ISSUE THREAD

**Issue by MaudGuan** [zhaohongxuan/obsidian-weread-plugin#213]
有一本书的一个划线评论很长，这本书导入出现了bug，笔记不全，而且元数据也没有了，这个评论放到任意一本书里面都会出现同步错误

==================下面是出bug的评论=================

对这本《穷查理宝典》的大名早有耳闻，但内心一直有一个疑团：为什么是“穷查理”？查理-芒格的名字中也没有“穷”字的前缀啊！明明很有钱，为什么要叫“穷”查理？

原来这个书名是源自一名粉丝对偶像的致敬。

作为万人仰慕的偶像，查理-芒格也是有自己偶像的，他的1号爱豆便是美国最杰出的总统本杰明-富兰克林（也就是美元百元大钞上的那个头像），他写过一本书叫《穷查理年鉴》，富兰克林在这本书里引用“穷查理”这个人物形象，通过描写他的个人奋斗史，来介绍底层人士应该拥有哪些优秀品质，最终变得富有。

作为富兰克林的超级粉丝，查理-芒格的“宝典”取名时就借鉴了《穷查理年鉴》，一来是表达对偶像的敬仰和怀念，二来也是一种自谦，表达一种富而不骄的态度，这也符合他一惯低调无闻的作风。

当然，个人认为“穷”字也可以作为动词来理解，意为穷尽探索、不断学习的意思。

因为芒格一直比较低调，没想着要正儿八经地著书立说来名扬四海、流传千古，所以他的智慧只能是其他人通过其公开演讲、媒体访谈等途径的“只言片语”中收集整理而得，所以这本书更像是一锅大杂烩，在排版上显得有些杂糅混乱，阅读体验欠佳，但对于想从芒格的思想中攫取真经的读者来说，这一点倒无伤大雅。

接下来，就让我们一起来学习查理的宝贵智慧吧。

一、给年轻人的建议

在南加州大学GOULD法学院毕业典礼的演讲中，芒格罗列了使他受益终身的道理与态度。

1.要得到你想要的某样东西，最可靠的方法是让你自己配得起它。

2.正确的爱应该以仰慕为基础。你不必强迫自己追随不崇拜、不认可的领导，因为那是非常危险的。而要正确地对付这种危险，必须同时拥有才华和决心才行。

3.获得智慧是一种道德责任，为此你必须坚持终身学习。因为光靠已有的知识，你在生活中走不了多远。唯有像巴菲特他们一样，“每天夜里睡觉时都比那天早晨聪明一点点”，才能使人满意。

4.逆向思考。“要是知道我会死在哪里就好啦，那我将永远不去那个地方。”这句话听起来荒唐，但却蕴含着深刻的真理：对于复杂适应系统以及人类大脑而言，如果采用逆向思考，问题往往会变得更容易解决。

5.避免极端强烈的意识形态。年轻人特别容易陷入强烈而愚蠢的意识形态当中，而且永远走不出来。对此，芒格有一条“铁律”：“我觉得我没有资格拥有一种观点，除非我能比我的对手更好地反驳我的立场。我认为我只有在达到这个境界时才有资格发表意见。”

6.如果你想说服别人，要诉诸利益，而非诉诸理性。

7.如果你真的想要在某个领域做得很出色，那么你必须对它有强烈的兴趣。

8.节俭是责任的仆人。查理·芒格从他爷爷芒格法官那儿学到了这一条。

二、多元思维模型：培养跨学科能力，建立并经常实践多元思维模型

“在手里拿着铁锤的人看来，每个问题都像钉子”。——谚语

在本书中，查理·芒格孜孜不倦强调得最多的，莫过于“多元思维模型”。在他的一生中，多元思维模型贯彻始终，无论是阅读学习，还是投资选股中都能发现它的影子。他的多元思维模型（据他估计，大概有100种）为他提供了一个背景，使他拥有了看清生活本质和目标的非凡洞察力，也是他“普世智慧”的源泉。

什么是多元思维模型？

研究人性的心理学表明，如果你只能使用一两种思维模型，将会扭曲现实，直到它符合你的思维模型，或者至少到你认为它符合你的模型为止。

为了解决这个问题，你必须涉猎各个不同的学科，拥有横跨许多领域的知识框架，即多元思维模型。它借用并完美地糅合了许多来自各个传统学科的分析工具、方法和公式。

LOLLAPALOOZA效应

一种思维模型的力量是有限的，甚至连一场考试都不能应付；而100种思维模型往往能够带来非凡的力量。当几个模型联合起来，你就能得到lollapalooza效应。这就像物理学里面的临界质量，当你达到一定程度的质量，你就能引发核爆炸。

几种重要的思维模型

你或许会觉得，掌握100种思维模型也太困难了，芒格花了93年才完成。而你希望用尽量短的时间，达到尽量可观的效果。

那就从以下几种思维模型开始吧：

1.数学模型：复利原理、排列组合原理、决策树理论

2.会计学：复式簿记与局限

3.工程思维：费马和帕斯卡的概率论、后备系统、断裂点理论、临界质量概念

4.统计学：高斯分布

5.心理学：25种误判心理

6.微观经济学：规模优势、品牌认同、专利商标特许经营、竞争性毁灭、能力圈

7.癌症手术法：以政府职员保险公司为例，它将某些不健康的业务砍掉，剩下的健康业务得以保留下来

五种超级简单的普遍观念

在漫长的职业生涯中，芒格掌握了五种超级简单的普遍观念，它们对解决问题很有帮助，也能让你把已掌握的思维模型用得更顺手。

1.简化任务的最佳方法一般是先解决那些答案显而易见的大问题。

2.惟有数学才能揭示科学的真实面貌。如果缺乏数学运算能力，我们大多数人将会像参加踢屁股比赛的独腿人。

3.光是正面思考问题是不够的，你必须进行反面思考。

4.基本的学术智慧是最好的智慧，但有一个重要前提：你必须以跨学科的方式来思考。

5.真正的大效应，也就是lollapalooza效应，通常在几种因素的共同作用下才会出现。

三、选股的艺术

毫无疑问，芒格最让人心醉之处，在于明智的投资决策。这不仅帮芒格实现了财务自由，更为伯克希尔·哈撒韦公司创造了非凡价值。芒格明智的决策是如何诞生的？

在能力圈内进行投资

芒格将投资对象分为三种：可以投资、不能投资、太难理解。

他与巴菲特，都只针对能力圈内（即可以投资的）的对象进行投资。为了确定“可以投资”的潜在项目，芒格通常会先选定一个容易理解的、有发展空间的、能够在任何市场环境下生存的主流行业。

综合考虑各种相关因素

在整个详尽的评估过程中，芒格会将各种相关因素都考虑在内，包括企业的内部因素和外部因素，以及它所处的行业情况，即使这些因素很难被识别、测量或者还原为数字。

购买价格公道的伟大企业

“（购买）股价公道的伟大企业比（购买）股价超低的普通企业好。”

选股时，芒格会计算整个企业的真正价值，并在考虑到未来股权稀释的情况下，去确定和市场的价格相比，每股的价值大约是多少。

注意企业的安全边际

关于安全边际，芒格经常说，投资者能够从工程学的“冗余思维模型”中获益。工程师设计桥梁时，会给它一个后备支撑系统以及额外的保护性力量，以防倒塌——投资策略也应该如此。

使用投资原则检查清单

在正确地评估股票的价值之后，芒格还会进行更精确的筛选，此时他会使用非常有效的检查清单，作一次快速而全面的评估。

（参考“投资和决策检查清单”）

在“黄金时机”果断出击

经过以上繁琐的工作后，芒格会耐心等待“黄金时机”的来临，而当所有条件都刚刚好，芒格决定要投资时，他很可能会决心下很大的赌注。他的投资行为结合了极度的耐心和极度的决心，这是成功必不可少的品质。

“最重要的观念是把股票当成企业的所有权，并根据它的竞争优势来判断该企业的持有价值。如果该企业未来的贴现现金流比你现�购买的股票价格要高，那么这个企业就具有投资价值。当你占据优势的时候才采取行动，这是非常基本的。你必须了解赔率，要训练你自己，在赔率有利于你时才下赌注。我们只是低下头，尽最大努力去对付顺风和逆风，每隔几年就摘取结果而已。”

四、芒格的检查清单

“聪明人怎么会经常犯错呢？他们并没有做到我让你们做的事情：使用一张检查清单，确保你们掌握了所有的主要模型，并以一种多元的方式使用它们。”——查理·芒格

双轨分析

1.理性地看，哪些因素真正控制了牵涉的利益？（例如：宏观的和微观的经济因素。）

2.当大脑处于潜意识状态时，有哪些潜意识因素会自动以各种方式形成虽然有用但往往失灵的结论？（本能、情绪、贪婪等等的影响，造成人类作出错误判断。）

超级简单的普遍观念

1.先解决那些答案显而易见的问题

2.利用数学运算能力

3.逆向思考（反过来考虑问题）

4.应用基本的跨学科智慧，永远不要完全依赖他人

5.注意多种因素的共同作用----也就是lollapalooza效应

基于心理学的倾向

人类误判的25个标准原因（参见第“五”点）

投资和决策检查清单

（芒格的非正式清单，详细地列出了各种值得考虑的因素。）

1.风险——投资评估应该从测量风险（尤其是信用的风险）开始

● 测算合适的安全边际

● 避免和道德品质有问题的人交易

● 坚持为预定的风险要求合适的补偿

● 永远记住通货膨胀和利率的风险

● 避免犯下大错；避免资本金持续亏损

2.独立——“惟有在童话中，皇帝才会被告知自己没穿衣服。”

● 客观和理性的态度需要独立思考

● 记住，你是对是错，并不取决于别人同意你还是反对你——唯一重要的是你的分析和判断是否正确

● 随大流只会让你往平均值靠近（只能获得中等的业绩）

3.准备——“唯一的获胜方法是不断工作，并希望拥有一点洞察力。”

● 通过广泛的阅读把自己培养成一个终生自学者；培养好奇心，每天努力使自己聪明一点点

● 比求胜的意愿更重要的是做好准备的意愿

● 熟练地掌握各大学科的思维模型

● 如果你想要变得聪明，你必须不停追问的问题是“为什么”

4.谦虚——承认自己的无知是智慧的开端

● 只在自己明确界定的能力圈内行事

● 辨认和核查否定性的证据

● 克制自己，不去追求虚假的精确、错误的确定性

● 最重要的是，别愚弄你自己，而且要记住，你是最容易被自己愚弄的人

5.严格分析——使用科学方法和有效的检验清单能够最大限度地减少错误和疏忽

● 区分价值和价格、过程和行动、财富和规模

● 记住浅显的，好过掌握深奥的

● 成为一名商业分析家，而不是市场、宏观经济或者证券分析家

● 考虑总体的风险和效益，永远关注潜在的二阶效应和更高层次的影响

● 要朝前想、往后看——反过来想，总是反过来想

6.配置——正确地配置资本是投资者最重要的工作

● 记住，最好的用途总是由次好的用途衡量出来的（机会成本）

● 好主意特别少——当时机对你有利时，狠狠地下赌注吧（配置资本）

● 别“爱上”投资项目——即使你投入巨大心血，也要依情况而定，照机会而行

7.耐心——克制人类天生爱行动的偏好

● “复利是世界第八大奇迹”，不到必要的时候，别去打断它

● 避免多余的交易税和摩擦成本，永远别为了行动而行动

● 幸运来临时要保持头脑清醒

● 享受结果，也享受过程，因为你活在过程当中

8.决心——当合适的时机出现时，要坚决地采取行动

● 当别人贪婪时，要害怕；当别人害怕时，要贪婪

● 机会来临的次数不多，所以当它来临时，抓住它

● 机会只眷顾有准备的人：投资就是这样的游戏

9.改变——在生活中要学会改变和接受无法消除的复杂性

● 认识和适应你身边的世界的真实本质，别指望它来适应你

● 不断地挑战和主动地修正你“最爱的观念”

● 正视现实，即使你并不喜欢它——尤其当你不喜欢它的时候

10.专注——别把事情搞复杂，记住你原来要做的事

● 记住，声誉和正直是你最有价值的财产——而且能够在瞬间化为乌有

● 避免妄自尊大和厌倦无聊的情绪

● 别因为过度关心细节而忽略了显而易见的东西

● 千万要排除不需要的信息：“千里之堤，溃于蚁穴”

● 直面你的大问题，别把它们藏起来

五、人类误判心理学

“我们老得太快，聪明得太迟。”——查理·芒格

为配合《穷查理宝典》的出版，芒格专门整理出25条误判心理学，可谓是本书中最精彩、干货最多的部分。

为了更好地阐释误判心理学，芒格先举了一个蚂蚁的案例作为铺垫。

有一种蚂蚁，当它在巢穴里嗅到蚂蚁尸体散发出的外激素时，它就会和其它蚂蚁合作把尸体运出巢穴。

对此，哈佛大学教授E.O.威尔逊做过一个有趣的心理学实验，他将死蚂蚁分泌的外激素涂在活蚂蚁身上。其他蚂蚁闻到了味道，就把这只活蚂蚁拖出了巢穴。尽管它在整个过程中不断地踢腿和挣扎，它的同伴们却无动于衷。

这就是蚂蚁的大脑，它拥有的反应程序特别简单，平时运转没有问题，但在许多意外发生时，它们就只会生搬硬套地根据这个程序作出机械反应。

和蚂蚁一样，由于存在许多过度简化的思维程序，人类大脑的运转也常常出现问题。下面的25条内容就是经常误导人的心理倾向。

1.奖励和惩罚超级反应倾向

有的人因为受过教育而变得道德高尚，但在激励机制的驱动之下，他可能会有意或者无意地做出一些不道德的行为，以便得到他想要的东西，而且他还会为自己的糟糕行为寻找借口。

2.喜欢/热爱倾向

一种心理调节工具，促使人们：忽略其热爱的对象的缺点；偏爱那些能够让自己联想起热爱对象的人、物品、行为；为了爱而扭曲其他事实。

3.讨厌/憎恨倾向

和上一条一样，讨厌/憎恨也是心理调节工具，它能促使深陷其中的人们：忽略讨厌对象的优点；讨厌那些能够让自己联想起讨厌对象的人、物品和行动；为了仇恨而扭曲其他事实。

4.避免怀疑倾向

人类的大脑天生就有一种尽快作出决定，以此消除怀疑的倾向。

对策：在做决定之前，必须让自己习惯于戴上一个客观的“面具”。

5.避免不一致性倾向

为了节省运算空间，人类的大脑不愿意作出改变。人们倾向于积累大量僵化的结论和态度，而且并不经常会检查，更不会去改变，即便有大量的证据表明它们是错误的。

对策：防止一种习惯的养成要比改变它容易得多。

6.好奇心倾向

增强好奇心，能帮助人们防止或减少其他心理倾向造成的糟糕后果。

7.康德式公平倾向

人们期待公平分配，一旦没有得到，就会表现出不满的情绪。

8.艳羡/嫉妒倾向

这一条普遍存在于各种神话、宗教和文学作品中，在现实生活中也无所不在。巴菲特明智地指出，“驱动这个世界的不是贪婪，而是妒忌。”

9.回馈倾向

和猿类、猴类、犬类等认知能力较为低下的动物一样，人类身上也有以德报德、以牙还牙的极端倾向。

回馈倾向主要有两种表现形式：以德报德、以牙还牙；回馈式让步。

对策：延迟自己的反应。

10.受简单联想影响的倾向

人们会因为看到虚无缥缈的关联，而作出不理性的决策。

11.简单的、避免痛苦的心理否认

当现实太过痛苦，令人无法承受时，人们会扭曲各种事实，直到它们变得�以承受。这种倾向造成的最极端的后果经常跟爱情、死亡和对化学物质（毒品、酒精等）的依赖有关。

对此，有些人的办法是什么呢？他们相信一条铁律：“未必要有希望才能够活下去。”

12.自视过高的倾向

生活中，自视过高的人比比皆是，他们通常会表现为：

（1）禀赋效应：人们作出决定之后，就会觉得自己的决定很好，甚至比没作出这种决定之前所认为的还要好。

（2）托尔斯泰效应：恶贯满盈的罪犯并不认为他们自己有那么坏。他们或者认为他们从来没有犯过罪；或者考虑到他们在生活中遭遇的压力和种种不幸，做出这样的事、变成这样的人，是完全可以理解和值得原谅的。

当然，有时候高度的自我赞扬，也是一种不错的积极心理品格。

13.过度乐观倾向

最典型的例子是，人们兴高采烈地购买彩票。正如古希腊著名的演说家德摩斯梯尼说的那样：“一个人想要什么，就会相信什么。”

对策：学习费马和帕斯卡的概率论，能帮你觉察过度的乐观。

14.被剥夺超级反应倾向

人们在失去——或者有可能失去——财产、爱情、友谊、势力范围、机会、身份或者其他任何有价值的东西时，通常会做出不理性的激烈反应，哪怕只失去一点点时也是如此。

15.社会认同倾向

社会认同倾向是一种自动根据他看到的周边人们的思考和行为方式去思考和行动的倾向，即从众、有样学样。

常以下面两种形式出现：

（1）谢皮科综合征：“社会认同倾向”和“激励机制引起的偏见”共同导致的现象，即不同流合污者就会受到团体排挤，甚至杀害。

（2）旁观者效应：看客，所有人的不作为。

对策：学会在其他人犯错的时候，别以他们为榜样。

16.对比错误反应倾向

因为人类的神经系统并不是精密的科学仪器，所以它必须依赖某些更为简单的东西，比如对比。更重要的是，不但感知如此，认知也是如此。结果就造成了人类的对比错误反应倾向。

17.压力影响倾向

轻度的压力能够轻微地改善人们的表现，比如说在考试中；而沉重的压力则会引发彻底失调，比如邪教、审讯、面试。

18.错误衡量易得性倾向

人类的大脑是有限和不完美的，它很容易满足于容易得到的东西。

对策：别只是因为一样事实或者一种观念容易得到，就觉得它更为重要。

19.不用就忘倾向

所有技能都会因为不用而退化。人们只要勤奋就能降低这种倾向的影响。如果人们能够熟练地掌握一种技能，而不是草草学习来应付考试，那么这种技能将会较难以丢失。

20.化学物质错误影响倾向

为改变自己的情绪以及感官体验，使用酒精、毒品等化学物质麻痹自己。

21.衰老—错误影响倾向

年龄的增长自然会造成认知衰退，而每个人认知衰退的时间早晚和速度快慢却不尽相同。从某种程度上说，带着快乐不断地思考和学习能够延缓不可避免的衰退过程。

22.权威—错误影响倾向

人类社会被组织成等级分明的权力结构，这种文化增强了我们追随领袖的倾向。而当领袖犯错的时候，或者当领袖的想法并没有得到很好的传达、被大众所误解的时候，跟随领袖的人就难免会遭受极大的痛苦。

23.废话倾向

作为一种拥有语言天赋的社会动物，人类天生就有本事啰里啰嗦，说出一大堆会给正在专心做正经事的人造成许多麻烦的废话。

24.重视理由倾向

人，尤其是生活在发达文化中的人，天生就热爱准确的认知，以及获取准确认知过程中得到的快乐。大多数人都认为有理由的事情是很重要的。

我们可以充分利用这一点，将直接和间接经验悬挂在一个解释“为什么”的理论框架之上，那么他们对知识的吸收和使用就会变得更加容易。

25.lollapalooza倾向

即数种心理倾向共同作用造成极端后果的倾向，这一点是芒格原创的，在他的言谈中无数次提及。

以上基本就本书的精华，当然，大佬近百年的人生智慧又岂是一本书可以穷尽的？但是，我们哪怕能真正掌握其中几条，也已受用不尽。

最后，我想用芒格说的我最喜欢的一段话来结尾：

“我这辈子遇到的聪明人（来自各行各业的聪明人）没有不每天阅读的——没有，一个都没有。沃伦读书之多，我读书之多，可能会让你感到吃惊。我的孩子们都笑话我，他们觉得我是一本长了两条腿的书。”

**Comment by zhaohongxuan** [comment]
感谢反馈，我这边已经定位到问题了，将会在下个版本修复
