### ISSUE TITLE
能否实现想法中的#标签转化为 [[标签]]

### ISSUE THREAD

**Issue by weqoocu** [zhaohongxuan/obsidian-weread-plugin#215]
双链基本代替了自己的标签,在微信读书上写想法,用#方便输入,但是导入到ob,希望能转换为双链[[标签]],这样方便,增加类似五彩的一个配置项.

<img width="1021" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/2abfbc13-2c9e-4ff2-8547-b28df4a7d948">

**Comment by musicleaf** [comment]
- {% set replacedString = review.content | replace(r/#(.*?)[\s\b]/g, "[[\\1]]")%}  {{replacedString}}


试验了正则表达式,不生效

**Comment by musicleaf** [comment]
求支持
