### ISSUE TITLE
似乎没有在同步高亮中添加block标记

### ISSUE THREAD

**Issue by Maxinsomnia** [zhaohongxuan/obsidian-weread-plugin#216]
<img width="833" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/26018159/65026b98-2ff2-44a3-b81c-5bed563f7564">
上图所示为daily notes中的同步内容，尝试在笔记中加入block number，内容可以同步过来；但是目前全部都是这种格式，请问可能是什么原因导致的呢？尝试了好几次都是这样

**Comment by zhaohongxuan** [comment]
duplicate https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/117
