### ISSUE TITLE
近期的一次更新后同步读书报错信息，查了其他 Issues 没有看到类似的问题

### ISSUE THREAD

**Issue by vennetong** [zhaohongxuan/obsidian-weread-plugin#219]
同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'chapterIdx')

尝试了卸载插件后，重新安装登录，均同步失败
此情况仅在前两天更新完插件后出现，Obisidian 版本 1.4.14. 系统 Sonoma 14.1, m1 芯片

另外出现的一个情况是在处理这个插件的登录注销过程中，会调用 Obisidian 里的界面 (不是跳到浏览器)，然后 Obisidna 的界面就消失了，无法调出，只能退出后重新启动。

**Comment by zhaohongxuan** [comment]
能看控制台是哪一本书报错的吗？

**Comment by vennetong** [comment]
我之前正好刚看完一本书，是开始阅读新的一本《创造：用非传统的方式做有价值的事》开始出现这个问题的。(刚完成的书是语言本能)
![SCR-20231012-lovg](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/5475395/5ccecd40-74a2-444b-80d6-95d83cbaa59e)
附上控制台截图，没有看到其他调用的参数，但是是在弹出了同步了多少本，跳过未更新的多少本后出现的。如果需要进一步的高度，请告诉我应当如何 Debug，我可以尝试能不能获得更多数据。

**Comment by lzlalpha** [comment]
出现同样的错误

**Comment by zeroYlin** [comment]
我也遇到了同样的报错。
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/49401247/5c34c7d0-6069-47cf-a137-49e83d5cbe6a)

**Comment by WangShuoCode** [comment]
刚刚遇到了同样的报错

**Comment by wuxiongliu1** [comment]
遇到同样的报错+1

**Comment by Lawliet46** [comment]
同样的报错
