### ISSUE TITLE
能使用微信读书默认的格式吗？分成两层，笔记读起来比较割裂~

### ISSUE THREAD

**Issue by Peingxious** [zhaohongxuan/obsidian-weread-plugin#22]
就是导出笔记的时候，会有到剪贴板的内容，然后粘贴就可以了。
这个高亮部分和标记部分分开了，只能看完上面看下面，这样好割裂。能让他们按顺序的在一起吗，不行就只能用手动办法，我把所有的格式删掉，去微信读书复制粘贴过来。

主要是这边还会覆盖，就挺麻烦的。

**Comment by SeyeeL** [comment]
同意

**Comment by zhaohongxuan** [comment]
> 就是导出笔记的时候，会有到剪贴板的内容，然后粘贴就可以了。 这个高亮部分和标记部分分开了，只能看完上面看下面，这样好割裂。能让他们按顺序的在一起吗，不行就只能用手动办法，我把所有的格式删掉，去微信读书复制粘贴过来。
> 
> 主要是这边还会覆盖，就挺麻烦的。
这个只需要改模板就可以了，默认模板里，为了不让笔记部分和划线部分重复，就在划线里面把注释隐藏掉了，你可以在模板里加回来。

我这里给你个模板，你试试看

```markdown
---
isbn: {{metaData.isbn}}
category: {{metaData.category}}
---

# 元数据
> [!abstract] {{metaData.title}}
> - ![ {{metaData.title}}|200]({{metaData.cover}})
> - 书名： {{metaData.title}}
> - 作者： {{metaData.author}}
> - 出版时间 {{metaData.publishTime}}
> - ISBN： {{metaData.isbn}}
> - 分类： {{metaData.category}}
> - 出版社： {{metaData.publisher}}

# 高亮划线
{% for chapter in chapterHighlights %}
## {{chapter.chapterTitle}}
{% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
- 📌 {{ highlight.markText |trim }} ^{{highlight.chapterUid}}-{{highlight.range}}
    - 💭 {{highlight.reviewContent}}
    - ⏱ {{highlight.createTime}}
{% else %}
- 📌 {{ highlight.markText |trim }} ^{{highlight.chapterUid}}-{{highlight.range}}
    - ⏱ {{highlight.createTime}}
{% endif %} {% endfor %}{% endfor %}

# 读书笔记
{% for chapter in bookReview.chapterReviews %}
{% if chapter.reviews or chapter.chapterReview %}
## {{chapter.chapterTitle}}
{% if  chapter.chapterReview %}
### 章节评论
- {{chapter.chapterReview.content}}{%endif %}
{% if chapter.reviews %}{%for review in chapter.reviews %}
### 划线评论
- 📌 {{review.abstract |trim }}  ^{{review.reviewId}}
    - 💭 {{review.content}}
    - ⏱ {{review.createTime}}
 {% endfor %} {%endif %} {% endif %} {% endfor %}
# 本书评论
{% if bookReview.bookReview %}
{{bookReview.bookReview.mdContent}} ^{{bookReview.bookReview.reviewId}}
{% endif %}```

**Comment by SeyeeL** [comment]
不过我用了这个还是会分成高亮和划线评论两种啊，就是想划线评论插在划线里，按文中顺序一起。

**Comment by Peingxious** [comment]
![image](https://user-images.githubusercontent.com/79826986/169234736-edda4e52-3342-46e7-aace-63faf3c2770f.png)

微信笔记里面会有划线和评论会产生重复，就改了习惯不高亮直接评论。按照你这样，我就只能把之前的非高亮的全部高亮一下。
并且刚刚看了一下， 高亮划线是正常的，读书笔记顺序是反的。对我而言没什么需求，我后面会删掉读书笔记和评论内容。我是把划线和思考记录下来，再在微信中进行整理。
很多reviewID我都没什么用，因为没有跳转需求。多的内容太杂了。视觉看📌看的太花了。

**Comment by Peingxious** [comment]
> > 就是导出笔记的时候，会有到剪贴板的内容，然后粘贴就可以了。 这个高亮部分和标记部分分开了，只能看完上面看下面，这样好割裂。能让他们按顺序的在一起吗，不行就只能用手动办法，我把所有的格式删掉，去微信读书复制粘贴过来。
> > 主要是这边还会覆盖，就挺麻烦的。
> > 这个只需要改模板就可以了，默认模板里，为了不让笔记部分和划线部分重复，就在划线里面把注释隐藏掉了，你可以在模板里加回来。
> 
> 我这里给你个模板，你试试看
> 
> ```gfm
> ---
> isbn: {{metaData.isbn}}
> category: {{metaData.category}}
> ---
> 
> # 元数据
> > [!abstract] {{metaData.title}}
> > - ![ {{metaData.title}}|200]({{metaData.cover}})
> > - 书名： {{metaData.title}}
> > - 作者： {{metaData.author}}
> > - 出版时间 {{metaData.publishTime}}
> > - ISBN： {{metaData.isbn}}
> > - 分类： {{metaData.category}}
> > - 出版社： {{metaData.publisher}}
> 
> # 高亮划线
> {% for chapter in chapterHighlights %}
> ## {{chapter.chapterTitle}}
> {% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
> - 📌 {{ highlight.markText |trim }} ^{{highlight.chapterUid}}-{{highlight.range}}
>     - 💭 {{highlight.reviewContent}}
>     - ⏱ {{highlight.createTime}}
> {% else %}
> - 📌 {{ highlight.markText |trim }} ^{{highlight.chapterUid}}-{{highlight.range}}
>     - ⏱ {{highlight.createTime}}
> {% endif %} {% endfor %}{% endfor %}
> 
> # 读书笔记
> {% for chapter in bookReview.chapterReviews %}
> {% if chapter.reviews or chapter.chapterReview %}
> ## {{chapter.chapterTitle}}
> {% if  chapter.chapterReview %}
> ### 章节评论
> - {{chapter.chapterReview.content}}{%endif %}
> {% if chapter.reviews %}{%for review in chapter.reviews %}
> ### 划线评论
> - 📌 {{review.abstract |trim }}  ^{{review.reviewId}}
>     - 💭 {{review.content}}
>     - ⏱ {{review.createTime}}
>  {% endfor %} {%endif %} {% endif %} {% endfor %}
> # 本书评论
> {% if bookReview.bookReview %}
> {{bookReview.bookReview.mdContent}} ^{{bookReview.bookReview.reviewId}}
> {% endif %}```
> ```

我改了一下
---
banner: "{{metaData.cover}}"
category: {{metaData.category}}
Status: 待整理
---

> [!abstract] Book_Info
> - 书名： {{metaData.title}}
> - 作者： {{metaData.author}}
> - 出版时间 {{metaData.publishTime}}
> - ISBN： {{metaData.isbn}}
> - 分类： {{metaData.category}}
> - 出版社： {{metaData.publisher}}

{% for chapter in chapterHighlights %}
# {{chapter.chapterTitle}}
{% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
 {{ highlight.markText |trim }} 
> {{highlight.reviewContent}}
{% else %}
{{ highlight.markText |trim }} 
{% endif %} {% endfor %}{% endfor %}

# 本书评论
{% if bookReview.bookReview %}
{{bookReview.bookReview.mdContent}} 
{% endif %}

![image](https://user-images.githubusercontent.com/79826986/169237441-3c19ab90-a267-4630-b4ae-ec7886a20acf.png)
好多了，就是banner上面有多一行。不过影响用就是了。就可以拉成这样的效果。
![image](https://user-images.githubusercontent.com/79826986/169237631-041b3db9-bc1a-4532-8868-d655b8ee43a3.png)

**Comment by zhaohongxuan** [comment]
@Peingxious 这是什么插件？😍

**Comment by Peingxious** [comment]
这就是dataview，配合minimal主题的css:cards片段做出来的样式。
挺像notion的相册模式，配合hover可以浮动窗口编辑，配合superlinked，可以反键超级yaml区的自定义片段。
蛮多玩法的😁😁😂

**Comment by SeyeeL** [comment]
我也贴个我的，主要是在日期加了双链，这样可以在日记反链里看到

```
---
isbn: {{metaData.isbn}}
category: {{metaData.category}}
---

## Meta
> [!abstract] {{metaData.title}}
> - ![ {{metaData.title}}|200]({{metaData.cover}})
> - 书名： {{metaData.title}}
> - 作者： {{metaData.author}}
> - 出版时间 {{metaData.publishTime}}
> - ISBN： {{metaData.isbn}}
> - 分类： {{metaData.category}}
> - 出版社： {{metaData.publisher}}

## highlights
{% for chapter in chapterHighlights %}
### {{chapter.chapterTitle}}
{% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
- {{ highlight.markText |trim }}  — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}} ^{{highlight.chapterUid}}-{{highlight.range}}
 {{highlight.reviewContent}}
{% else %}
- {{ highlight.markText |trim }}  — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}} ^{{highlight.chapterUid}}-{{highlight.range}}
{% endif %} {% endfor %}{% endfor %}

{% for chapter in bookReview.chapterReviews %}
{% if chapter.reviews or chapter.chapterReview %}
{% if  chapter.chapterReview %}
### Notes
- {{chapter.chapterReview.content}}{%endif %}
{% if chapter.reviews %}{%for review in chapter.reviews %}

 {% endfor %} {%endif %} {% endif %} {% endfor %}

{% if bookReview.bookReview %}
### 本书评论
{{bookReview.bookReview.mdContent}} ^{{bookReview.bookReview.reviewId}}
{% endif %}
```

**Comment by SeyeeL** [comment]
对了那些自己传的图书同步不了，我看控制台有报错，大概猜是原数据的原因，请问可以通过改模板同步过来么

**Comment by zhaohongxuan** [comment]
> 对了那些自己传的图书同步不了，我看控制台有报错，大概猜是元数据的原因，请问可以通过改模板同步过来么

自己上传的书获取那应该是元数据报错了，等下个版本修复。

**Comment by mengtanx** [comment]
> 

感谢提供模板，我也试试这个，觉得默认模板结构有点复杂～

**Comment by liheyuting** [comment]
请问怎么修改模板啊，我修改了template里的微信读书模板，删掉之前同步的微信读书笔记，再重新同步，但默认模板还是之前的那个模板

**Comment by marsvet** [comment]
> 

这个想法太棒了

**Comment by marsvet** [comment]
> 我也贴个我的，主要是在日期加了双链，这样可以在日记反链里看到
> 
> ```
> ---
> isbn: {{metaData.isbn}}
> category: {{metaData.category}}
> ---
> 
> ## Meta
> > [!abstract] {{metaData.title}}
> > - ![ {{metaData.title}}|200]({{metaData.cover}})
> > - 书名： {{metaData.title}}
> > - 作者： {{metaData.author}}
> > - 出版时间 {{metaData.publishTime}}
> > - ISBN： {{metaData.isbn}}
> > - 分类： {{metaData.category}}
> > - 出版社： {{metaData.publisher}}
> 
> ## highlights
> {% for chapter in chapterHighlights %}
> ### {{chapter.chapterTitle}}
> {% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
> - {{ highlight.markText |trim }}  — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}} ^{{highlight.chapterUid}}-{{highlight.range}}
>  {{highlight.reviewContent}}
> {% else %}
> - {{ highlight.markText |trim }}  — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}} ^{{highlight.chapterUid}}-{{highlight.range}}
> {% endif %} {% endfor %}{% endfor %}
> 
> {% for chapter in bookReview.chapterReviews %}
> {% if chapter.reviews or chapter.chapterReview %}
> {% if  chapter.chapterReview %}
> ### Notes
> - {{chapter.chapterReview.content}}{%endif %}
> {% if chapter.reviews %}{%for review in chapter.reviews %}
> 
>  {% endfor %} {%endif %} {% endif %} {% endfor %}
> 
> {% if bookReview.bookReview %}
> ### 本书评论
> {{bookReview.bookReview.mdContent}} ^{{bookReview.bookReview.reviewId}}
> {% endif %}
> ```

这个想法太棒了
