### ISSUE TITLE
能否同步通过微信读书打开的公众号?

### ISSUE THREAD

**Issue by cgcel** [zhaohongxuan/obsidian-weread-plugin#220]
我注意到 README 的截图中有公众号一栏的分类, 然后我尝试点开一篇推送然后用微信读书打开, 在微信读书中对一个段落进行划线, 但是该文章无法同步到 obsidian 中, 请问如果可以的话要怎么操作?

**Comment by zhaohongxuan** [comment]
> 我注意到 README 的截图中有公众号一栏的分类, 然后我尝试点开一篇推送然后用微信读书打开, 在微信读书中对一个段落进行划线, 但是该文章无法同步到 obsidian 中, 请问如果可以的话要怎么操作?
之前的版本支持，上个版本中已经取消了
