### ISSUE TITLE
同步微信读书笔记异常

### ISSUE THREAD

**Issue by Lawliet46** [zhaohongxuan/obsidian-weread-plugin#222]
![企业微信截图_16976140498540](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/148194907/5ab5c6e7-2385-42e7-8c22-eccd60bf1a04)

使用10.17的最新版本0.5.6，提示同步微信读书笔记异常，报错如图

**Comment by zhaohongxuan** [comment]
昨天包有点问题，重新打包了，你更新一下试试

**Comment by isyngo** [comment]
更新0.5.6后出现同样的报错

**Comment by yangscar** [comment]
使用新包还是存在这个问题

<img width="486" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/2883764/0ae33c1d-0b3e-4a09-bacb-b397031a9650">

**Comment by beaglewer** [comment]
0.5.6和0.5.5和0.5.4都是报错，同步不了
<img width="324" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/148428679/b7e63352-529a-441e-9f0b-881230fd2478">

**Comment by beaglewer** [comment]
你好，已收到你的邮件，谢谢

**Comment by wuxiongliu1** [comment]
<img width="689" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/5119063/c3bf98b6-e714-4e6a-b99d-ba1e497b21ca">
<img width="788" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/5119063/90345fab-2d22-4696-8302-c4819b83ae86">
还是会报错误

**Comment by lzlalpha** [comment]
更新到0.5.6，还是出现同样的错误

**Comment by Ricarda007** [comment]
同更新到0.5.6，还是会出现同步异常问题
<img width="538" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/60726066/9684baec-b3d6-4ea5-bd7d-47ffc228afdf">

**Comment by FLIER001** [comment]
第一次安装，无法使用，相同的问题

**Comment by viowy** [comment]
同样的异常，有解决方案吗？没有书签

**Comment by viowy** [comment]
> 同样的异常，有解决方案吗？没有书签

取消所有的图片笔记，就好了，之前好像没有这个问题，好奇怪。

**Comment by FLIER001** [comment]
> > 同样的异常，有解决方案吗？没有书签
> 
> 取消所有的图片笔记，就好了，之前好像没有这个问题，好奇怪。

怎么取消图片笔记？几百本书的笔记，我也不知道什么时候做了图片笔记，难找哇

**Comment by zhaohongxuan** [comment]
我尝试一下看能复现不？我好几百本书也没出现这个问题
