### ISSUE TITLE
有没有办法获取到阅读时长呀？ 

### ISSUE THREAD

**Issue by hxzhouh** [zhaohongxuan/obsidian-weread-plugin#223]
微信读书app 里面有这个数据，但是网页版好像没看到，不知能否抓出来
![](https://images.hxzhouh.com/blog-images/2023/10/4dbbf0ea64b1e23e5e9267882da15564.jpg)

**Comment by zhaohongxuan** [comment]
666，这个功能以后可以添加，数据添加到metadata中

**Comment by zhaohongxuan** [comment]
https://github.com/zhaohongxuan/obsidian-weread-plugin/pull/245
