### ISSUE TITLE
更新到0.5.7 升级之后同步数据失败

### ISSUE THREAD

**Issue by wuxiongliu1** [zhaohongxuan/obsidian-weread-plugin#227]
<img width="788" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/5119063/82284d38-61a0-4fcd-87fa-a50fcbabc389">
<img width="1439" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/5119063/90bb9302-09e3-4124-93a2-4412ff8057a8">

obsidian版本：1.4.16
操作系统：mac os

**Comment by FLIER001** [comment]
一样的问题，作者更新的很快，我升级的也很及时，但还是不能用（作者大大辛苦了）

**Comment by isyngo** [comment]
同问题，麻烦作者了

**Comment by zhaohongxuan** [comment]
0.5.8更新了，可以试一下，增加了undefined的判断，你们可以看看哪一本书会有未知章节的数据，贴到这个issue里，我本地debug一下。
<img width="768" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/b7ca8ed4-7260-406f-b72b-7b5d7634f3aa">

**Comment by isyngo** [comment]
同步成功了，谢谢~

**Comment by wuxiongliu1** [comment]
感谢大佬，已经同步成功了。
