### ISSUE TITLE
公众号文章在微信阅读的笔记无法同步

### ISSUE THREAD

**Issue by Sleepleeps** [zhaohongxuan/obsidian-weread-plugin#229]
如题，我习惯把公众号文章发到微信阅读，但是更新后不能同步文章高亮和笔记，之前是可以的；
同步微信读书自带的书籍以及我自己导入微信读书的本地文件的笔记都没有此问题。
不知道出了什么问题，好心人望告知一声🌷

**Comment by zhaohongxuan** [comment]
新版本移除了这个功能，公众号和正常书籍数据格式相差比较大，兼容起来比较麻烦，影响正常书籍的更新。

**Comment by irisfish531** [comment]
是啊，这个功能很好，一直在用，最近发现会报错。。。我是在DAILY NOTE里面插入的，然后DAILY NOTE里面提示有引用，但实际上对应的笔记内容没有创建，所以报错。

**Comment by shiquda** [comment]
比较想要有这个功能，希望作者能兼容一下
