### ISSUE TITLE
Failed to fetch weread book detail. Please check your Cookies and try again.

### ISSUE THREAD

**Issue by gongkaizh** [zhaohongxuan/obsidian-weread-plugin#23]
以下是console log
VM254:2 [HPM] Proxy created: /  -> https://weread.qq.com
VM254:2 [HPM] Proxy rewrite rule created: "^/refresh" ~> "/"
VM254:2 [HPM] Proxy created: /  -> https://i.weread.qq.com
VM254:2 Start syncing Weread note...
VM254:2 GET http://localhost:12011/book/info?bookId=MP_WXS_3860160953 499 (ERR)
eval @ VM254:2
e.exports @ VM254:2
e.exports @ VM254:2
p.request @ VM254:2
r.forEach.p.<computed> @ VM254:2
eval @ VM254:2
eval @ VM254:2
eval @ VM254:2
e @ VM254:2
getBook @ VM254:2
eval @ VM254:2
s @ VM254:2

Promise.then (async)
c @ VM254:2
eval @ VM254:2
e @ VM254:2
startSync @ VM254:2
eval @ VM254:2
Promise.then (async)
eval @ VM254:2
Promise.then (async)
eval @ VM254:2
eval @ VM254:2
e @ VM254:2
startSync @ VM254:2
eval @ VM254:2
VM254:2 i {message: "Request failed with status code 499", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, …}
eval @ VM254:2
o @ VM254:2
Promise.then (async)
c @ VM254:2
eval @ VM254:2
e @ VM254:2
getBook @ VM254:2
eval @ VM254:2
s @ VM254:2

Promise.then (async)
c @ VM254:2
eval @ VM254:2
e @ VM254:2
startSync @ VM254:2
eval @ VM254:2
Promise.then (async)
eval @ VM254:2
Promise.then (async)
eval @ VM254:2
eval @ VM254:2
e @ VM254:2
startSync @ VM254:2
eval @ VM254:2
VM254:2 TypeError: Cannot read property 'category' of undefined
    at L.eval (eval at <anonymous> (app.js:1), <anonymous>:2:1323479)
    at Generator.next (<anonymous>)
    at s (eval at <anonymous> (app.js:1), <anonymous>:2:1314440)
VM254:2 HTTP server closed

**Comment by zhaohongxuan** [comment]
这是公众号，不是书查询书籍接口报错了，下个版本fix下
