### ISSUE TITLE
daily notes同步unable to find 怎么解决啊？

### ISSUE THREAD

**Issue by 1563803099** [zhaohongxuan/obsidian-weread-plugin#230]
<img width="718" alt="iShot_2023-10-30_21 32 58" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/52308108/a022c8be-d76b-461c-89ad-38c05e024609">

**Comment by zhaohongxuan** [comment]
> <img alt="iShot_2023-10-30_21 32 58" width="718" src="https://user-images.githubusercontent.com/52308108/279073848-a022c8be-d76b-461c-89ad-38c05e024609.png">

检查一下是否开启了下面的开关
<img width="898" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/1f800a0b-db98-412b-8f4a-dd7218c0a65e">

**Comment by irisfish531** [comment]
也可能因为这是一条公众号文章的划线？这种情况也会有类似的报错。

**Comment by xxhk-org** [comment]
@zhaohongxuan 你好，我也遇到了同样的问题。

检查发现是 Daily Notes 里的引用和导入的笔记里的 ID 不同，前者像这样“CB-4N19Ux9VkAfJ6TB6U5-12-48434-48498”，后者像这样“12-48434-48498”。

模板用的是默认的，对象是书库里的书，不是公众号文章，也不是导入的书，也没开启“笔记划线数量最小值”的限制。
