### ISSUE TITLE
移动端从未成功，无效报错

### ISSUE THREAD

**Issue by alanodididi** [zhaohongxuan/obsidian-weread-plugin#231]
移动段 手机，安卓平板，ipad，。安装插件提示未登录，在电脑上登录后采用官方同步或者数据线拷贝插件至移动端，移动端显示已登录，点击同步按钮仍然无法同步，提示如图。 注意这个问题在半年前已经存在，到现在没有解决。是否有人成功的移动端同步的案例。
![Screenshot_20231109_005136](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/64760894/93b01eb5-d391-4537-8e8d-9290b154be7f)

**Comment by zhaohongxuan** [comment]
我vault放在iCloud上的，一般使用mac客户端，在使用iPad 和iphone都可以正常使用的，一年了都没重新登录过...

**Comment by zhaohongxuan** [comment]
Duplicate  https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/176

**Comment by 18745085274** [comment]
我也出现了和他一模一样的问题，电脑端已经登录了微信读书，但是移动端仍然无法刷新。还提示要电脑端登录。

**Comment by 18745085274** [comment]
我的设备是oppo的安卓手机。
