### ISSUE TITLE
【需求】把当前笔记上的标题按结构列出，而不是只给出紧邻的一级标题

### ISSUE THREAD

**Issue by VictoireWood** [zhaohongxuan/obsidian-weread-plugin#233]
# 新需求
## 问题
很喜欢您的插件，但是有个问题，就是我发现在插入章节的时候，只能插入当前笔记以上紧邻的一个章节标题。举个例子，我在阅读《阿加莎·克里斯蒂侦探小说大全集（全85册）》这本书中的《死亡约会》的第一部分下的第二章，我做出的标注上的标题只标注到了当前的`## 第二章`，且不是在`## 第一部分`的标题的下一级，但是实际的标题结构应该是：
```
死亡约会
  |_  第一部分
      |_  第二章
```
## 需求
由于作者在不同的书（因为我买的这本是85本书的合订本）中有很多一模一样的标题，在看笔记的时候就容易发生混淆，不知道作者能否把当前笔记上的标题按结构列出？
比如我这里的笔记，我希望的效果是：
```
# 高亮划线
## 第一部分
……（这里是在第一部分以下第一章以上做的标注）
### 第二章

- 📌 🟦 医学学士莎拉·金小姐  ^3300071652-535-370-380
    - ⏱ 2023-11-23 11:23:41 
……（这里是在第一部分以下的第二章以下第三章以上做的标注）
```
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79731222/4853fd52-dc95-4d0a-8d2e-9b1601e509d7)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/79731222/37225886-2bc1-425d-9e9a-a3cd43abffcf)

参考
              @zhaohongxuan 虽然有人觉得下载完整的目录结构很有用处，但这个您说了算。不过还有另外一个建议，即使不下载整个完整的目录结构，可否对有高亮或评论的部分的目录结构下载的更完整一些，（大）章（小）节都包含在内，二级、三级甚至四级标题都下载下来并标识清楚？我非常赞同您说的为了提高读书效果，应该另外再做永久笔记，但如果下载下来的内容目录结构清晰，则更有利于复习阅读和下一步的加工。

_Originally posted by @palwoo in https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/106#issuecomment-1598354236_

**Comment by zhaohongxuan** [comment]
这个很多人都提过，我也认为是必要的，只是改动会很大，还需要一段时间
