### ISSUE TITLE
bug report：有metadata项时顶部会生成一条多余的分隔线

### ISSUE THREAD

**Issue by PupupupuTong** [zhaohongxuan/obsidian-weread-plugin#238]
源码是这样

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/69069739/4f6a7796-17b5-4d28-9c8d-9cb788d5e776)

用的默认模板，删除下方的`---`metadata就要出问题了

**Comment by zhaohongxuan** [comment]
所有的笔记都有这样的问题吗？

**Comment by PupupupuTong** [comment]
是的，所有都是这样
