### ISSUE TITLE
[BUG] 书名过长时无法创建笔记

### ISSUE THREAD

**Issue by cgcel** [zhaohongxuan/obsidian-weread-plugin#239]
你好，我习惯从 zlib 下书然后导入微信读书阅读并做笔记，有一段时间没用插件了，最近更新插件后发现有一本书书名过长导致笔记无法创建，控制台报错信息如下：

```
Error: ENAMETOOLONG: name too long, lstat '/home/cgc/Obsidian/我的OB/读书笔记/从零开始的女性主义（日本女性主义理论人、《厌女》作者上野千鹤子 面向普通读者的女性主义普及课 女性为何如此艰难？女性如何奋斗至今？又该如何奋斗？ 结婚、恋爱、育儿，该如何以女.md'
```

能否加一个限制，使这些不规范的书名也能同步？或者预设一个规则识别书名和作者，我的想法是或许可以仿照电影电视剧集文件名自动识别：

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/23419678/eb2cf280-f36c-4921-8897-e35cf90e1c79)

**Comment by zhaohongxuan** [comment]
我看了下，应该是zlib下载的书名把简介也放进去了，文件名太长是操作系统底层报的错，修改原始书籍的元数据就好了。

**Comment by cgcel** [comment]
> 我看了下，应该是zlib下载的书名把简介也放进去了，文件名太长是操作系统底层报的错，修改原始书籍的元数据就好了。

修改元数据是不是要用到 calibre? 用的比较少请指教一下, 谢谢!

**Comment by zhaohongxuan** [comment]
是的，Calibre很优秀，还是开源的

> > 我看了下，应该是zlib下载的书名把简介也放进去了，文件名太长是操作系统底层报的错，修改原始书籍的元数据就好了。
> 
> 修改元数据是不是要用到 calibre? 用的比较少请指教一下, 谢谢!
