### ISSUE TITLE
是否可以考虑增加高亮的划线类型？

### ISSUE THREAD

**Issue by Aleczohar** [zhaohongxuan/obsidian-weread-plugin#242]
非常感谢您做的如此有用的插件！！
不知是否可以参照颜色的设置，
1 红色 🟥
2 紫色 🟪
3 蓝色 🟦
4 绿色 🟩
5 黄色 🟨
对不同类型的划线也进行区分，例如将：
   〰️🟥表示红色波浪线
  💡🟥表示红色直线
  ⭐🟥表示红色荧光笔

**Comment by zhaohongxuan** [comment]
已经支持了，可以自己改模板实现，参考这个issue：https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/211 
以及这个PR: https://github.com/zhaohongxuan/obsidian-weread-plugin/pull/212
