### ISSUE TITLE
四个功能需求，请问作者大大能否实现呢？

### ISSUE THREAD

**Issue by wopanda** [zhaohongxuan/obsidian-weread-plugin#25]
感谢作者开发出这个插件，非常实用，下面想再提出四点功能需求：
1. 能否在高亮读书笔记处新增跳转回微信读书的定位链接？
2. 有选择的让用户设置书本笔记的存放方式：一本书，创建一个文件夹，文件夹内部放置一个对应的md文件；
3. 在OB界面，新增直接打开微信读书的界面按钮功能。目前似乎仅能用微信读书插件的设置注销处打开这个界面；
4. 对于同一本书的笔记，能否采用追加的方式，而不是覆写的方式，去新增笔记？这样能够使得用户直接在书籍笔记页面做相应的笔记。

**Comment by zhaohongxuan** [comment]
> 感谢作者开发出这个插件，非常实用，下面想再提出四点功能需求：
> 
> 1. 能否在高亮读书笔记处新增跳转回微信读书的定位链接？
> 2. 有选择的让用户设置书本笔记的存放方式：一本书，创建一个文件夹，文件夹内部放置一个对应的md文件；
> 3. 在OB界面，新增直接打开微信读书的界面按钮功能。目前似乎仅能用微信读书插件的设置注销处打开这个界面；
> 4. 对于同一本书的笔记，能否采用追加的方式，而不是覆写的方式，去新增笔记？这样能够使得用户直接在书籍笔记页面做相应的笔记。

1. 存在两个问题，一个是web版的微信读书书籍是加密的不好定位，二是划线位置无法锚定，所以暂时无法实现。
2. 每一本书存放一个文件夹在我看来太重了，在我看来，文件夹只适合粗分，不适合细分，多使用双向链接，建立自己的MOC。后面可以考虑按照书籍分类来粗划定文件夹。管理书籍可以使用dataview插件<img width="1255" alt="image" src="https://user-images.githubusercontent.com/8613196/169259258-88fc3534-f46b-4b2e-bf64-3bf26e2bfb96.png">，

下面👇🏻是代码：

```dataviewjs
const groups =  dv.pages('"Hypothesis/weread"').groupBy(p => p.category.split('-')[0])
for (let group of groups) {
	dv.header(3, group.key);
	dv.table(["Name","author","publisher", "NoteCount"],
		group.rows
			.sort(k => k.noteCount, 'desc')
			.map(k => [k.file.link,k.author,k.publisher, k.noteCount]))
}

```
写读书笔记的笔记，可以使用Block引用的方式，参考 [Link to Block](https://help.obsidian.md/How+to/Link+to+blocks) 可以在的外部笔记引用读书笔记中的高亮划线或者划线评论以及书评，下面就是我在Daily Notes里面引用了《中国哲学史》里面的一个划线Block，因为BlockId是唯一的，所以就保证就算未来有更新也不影响它。
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8613196/169260683-8084b22e-815a-4a62-b488-341f47c9e91f.png">

3. 后续可以考虑添加功能，这个实现起来很简单。但是可能不是放在界面上，而是使用Command Palette的方式，我自己觉得在Obsidian里读书体验不好，更喜欢用电纸书或者ipad看。
4. 这是一个好问题，你的需求是要做读书笔记的笔记，这个在我看来肯定是需要的，因为读书的目的不是为了划线，而是为了吸收书的知识，但是一定要在原来的笔记上做吗，我认为最好不要：
	1. 首先思考一下做笔记的目的，目的肯定不是为了做笔记本身，而是为了消化知识，形成自己的思想，所以在我看来，这里同步的微信读书的笔记只是一个粗粒度的**文献笔记**，它只是我们做**永久笔记**的中间产物，什么？你说你不打算做**永久笔记**？那读书就是个无用功（消遣类的小说不算），推荐读一下 [卡片笔记写作法](https://book.douban.com/subject/35503571/)可能会有很大收获。
	2. 追加的方式太笨拙了，假如你在微信读书里修改了评论，或者增加了注释和现有的有冲突如何同步是个不得不解决的问题。所以追加的方式不是不能做，而是没有必要做，就像写代码不会修改Generator生成的代码一样。

这是我的一些小的建议，要利用Obsidian的超能力，双向链接还有块引用，它可以帮你更加高效的组织内容构建自己的数字花园。

**Comment by gongkaizh** [comment]
> > 感谢作者开发出这个插件，非常实用，下面想再提出四点功能需求：
> > 
> > 1. 能否在高亮读书笔记处新增跳转回微信读书的定位链接？
> > 2. 有选择的让用户设置书本笔记的存放方式：一本书，创建一个文件夹，文件夹内部放置一个对应的md文件；
> > 3. 在OB界面，新增直接打开微信读书的界面按钮功能。目前似乎仅能用微信读书插件的设置注销处打开这个界面；
> > 4. 对于同一本书的笔记，能否采用追加的方式，而不是覆写的方式，去新增笔记？这样能够使得用户直接在书籍笔记页面做相应的笔记。
> 
> 1. 存在两个问题，一个是web版的微信读书书籍是加密的不好定位，二是划线位置无法锚定，所以暂时无法实现。
> 2. 每一本书存放一个文件夹在我看来太重了，在我看来，文件夹只适合粗分，不适合细分，多使用双向链接，建立自己的MOC。后面可以考虑按照书籍分类来粗划定文件夹。管理书籍可以使用dataview插件<img alt="image" width="1255" src="https://user-images.githubusercontent.com/8613196/169259258-88fc3534-f46b-4b2e-bf64-3bf26e2bfb96.png">，
> 
> 下面👇🏻是代码：
> 
> ```
> const groups =  dv.pages('"Hypothesis/weread"').groupBy(p => p.category.split('-')[0])
> for (let group of groups) {
> 	dv.header(3, group.key);
> 	dv.table(["Name","author","publisher", "NoteCount"],
> 		group.rows
> 			.sort(k => k.noteCount, 'desc')
> 			.map(k => [k.file.link,k.author,k.publisher, k.noteCount]))
> }
> ```
> 
> 写读书笔记的笔记，可以使用Block引用的方式，参考 [Link to Block](https://help.obsidian.md/How+to/Link+to+blocks) 可以在的外部笔记引用读书笔记中的高亮划线或者划线评论以及书评，下面就是我在Daily Notes里面引用了《中国哲学史》里面的一个划线Block，因为BlockId是唯一的，所以就保证就算未来有更新也不影响它。 <img alt="image" width="699" src="https://user-images.githubusercontent.com/8613196/169260683-8084b22e-815a-4a62-b488-341f47c9e91f.png">
> 
> 3. 后续可以考虑添加功能，这个实现起来很简单。但是可能不是放在界面上，而是使用Command Palette的方式，我自己觉得在Obsidian里读书体验不好，更喜欢用电纸书或者ipad看。
> 4. 这是一个好问题，你的需求是要做读书笔记的笔记，这个在我看来肯定是需要的，因为读书的目的不是为了划线，而是为了吸收书的知识，但是一定要在原来的笔记上做吗，我认为最好不要：
>    
>    1. 首先思考一下做笔记的目的，目的肯定不是为了做笔记本身，而是为了消化知识，形成自己的思想，所以在我看来，这里同步的微信读书的笔记只是一个粗粒度的**文献笔记**，它只是我们做**永久笔记**的中间产物，什么？你说你不打算做**永久笔记**？那读书就是个无用功（消遣类的小说不算），推荐读一下 [卡片笔记写作法](https://book.douban.com/subject/35503571/)可能会有很大收获。
>    2. 追加的方式太笨拙了，假如你在微信读书里修改了评论，或者增加了注释和现有的有冲突如何同步是个不得不解决的问题。所以追加的方式不是不能做，而是没有必要做，就像写代码不会修改Generator生成的代码一样。
> 
> 这是我的一些小的建议，要利用Obsidian的超能力，双向链接还有块引用，它可以帮你更加高效的组织内容构建自己的数字花园。

这个dataviewjs的代码怎么提示错误：
Evaluation Error: TypeError: Cannot read property 'split' of undefined

**Comment by zhaohongxuan** [comment]
是不是有数据的category是空的

**Comment by zhaohongxuan** [comment]
@wopanda 
```
const groups =  dv.pages('"Hypothesis/weread"').filter(p=>p.category).groupBy(p => p.category.split('-')[0])
for (let group of groups) {
	dv.header(3, group.key);
	dv.table(["Name","author","publisher", "NoteCount"],
		group.rows
			.sort(k => k.noteCount, 'desc')
			.map(k => [k.file.link,k.author,k.publisher, k.noteCount]))
}
```
