### ISSUE TITLE
如何获取笔记或者摘抄内容的超链接

### ISSUE THREAD

**Issue by math-feng** [zhaohongxuan/obsidian-weread-plugin#251]
即点一下某个链接，就可以打开浏览器的微信读书网页端跳到对应的书中的内容，在导入模板中有个{{metaData.pcurl}}，可以打开网页端的微信读书，但是不是我想要的效果，请我有人知道怎么操作吗

**Comment by zhaohongxuan** [comment]
网页端的浏览器是基于Javascript的，不是超链接，目前是做不到的。
