### ISSUE TITLE
cookies问题

### ISSUE THREAD

**Issue by anschein** [zhaohongxuan/obsidian-weread-plugin#252]
刚开始用插件，昨天正常工作，今天发现无法同步，重装插件，注销重新登陆，更换设备都不行
插件版本0.7.1
obsidian版本1.5.3
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/49552476/376d01bc-d2e9-4fb1-9de1-dec1c84fed08)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/49552476/c6b662cf-6fe1-43c0-8194-ec50b726c5f3)

**Comment by anschein** [comment]
请问哪里能彻底清除cookies？我怀疑跟之前保存的cookies有关

**Comment by anschein** [comment]
更新：更换其他微信号可以登录并同步，换回自己的账号还是不行

**Comment by anschein** [comment]
更新：怀疑和 #75 有关，今天在网页端登录过微信读书，请问插件储存的cookies在什么位置？我想全部删了试试

**Comment by zhaohongxuan** [comment]
应该和cookie没关系，你可以重新建立一个vault试试，或者删除插件文件夹

**Comment by anschein** [comment]
> 应该和cookie没关系，你可以重新建立一个vault试试，或者删除插件文件夹

新开了一个库，只安装了weread，点击登录不用扫码直接就登录了，然后点击同步是同样的情况，同步失败

**Comment by anschein** [comment]
> > 应该和cookie没关系，你可以重新建立一个vault试试，或者删除插件文件夹
> 
> 新开了一个库，只安装了weread，点击登录不用扫码直接就登录了，然后点击同步是同样的情况，同步失败

我想试试清除本地的cookies，可能是本地的cookies有问题？

**Comment by anschein** [comment]
把obsidian卸载并清除残留重装了，还是不行🤣

**Comment by zhaohongxuan** [comment]
这个报错从来没见过。。除非我能复现，否则没发解决。

**Comment by anschein** [comment]
> 这个报错从来没见过。。除非我能复现，否则没发解决。

我的整个过程就是头一天安装了插件，正常登录同步，然后登录了一下网页端和手机端，第二天起来就发现插件不能同步了🤣

**Comment by anschein** [comment]
有一个细节不知道有没有帮助，当登录后去同步会同步失败，然后插件自动清除cookies，再点击登录会弹出网页，网页里面是登录好的，然后obsidian会提示‘加载微信读书登录页面失败’

**Comment by zhaohongxuan** [comment]
弹出的页面可以正常注销吗？

**Comment by anschein** [comment]
> 弹出的页面可以正常注销吗？

弹出的页面里面的头像无法点击，需要点击微信读书后回到首页然后再点头像能够正常注销，注销后也能够正常扫码登录

**Comment by inscripoem** [comment]
@anschein 你登录的微信读书账号中是否有任何标注或笔记内容？我今天第一次安装时完全复现（？）了与你相同情况的错误日志与注销问题，在app中添加了一段标注后成功导入  
此前我也尝试了卸载插件后重装的操作，不过在我于账号中添加内容之前报错问题并没有改善，所以我推测大概率是因为账号中没有笔记内容导致某些方法调用出错，而不是因为cookies

**Comment by anschein** [comment]
> @anschein 你登录的微信读书账号中是否有任何标注或笔记内容？我今天第一次安装时完全复现（？）了与你相同情况的错误日志与注销问题，在微信读书中添加了一段标注后成功导入  
> 
> 此前我也尝试了卸载插件后重装的操作，不过在我于账号中添加内容之前报错问题并没有改善，所以我推测大概率是因为账号中没有笔记内容导致某些方法调用出错，而不是因为cookies

我今天回去再测试一下看今天好没好，当时测试的时候有笔记并且有划线，为了测试同步后的样式我添加了两本书和笔记

**Comment by anschein** [comment]
没有找到原因，但是今天又成功同步了，先关闭问题观察观察

**Comment by watchpoints** [comment]
我遇到同样问题 如何删除cookies
