### ISSUE TITLE
重新导入后大量错误 app.js:1 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by milla** [zhaohongxuan/obsidian-weread-plugin#254]
<img width="1364" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/297531/e3261ded-596c-4faa-9344-61c2f0624675">

OB：最新版本
插件：最新版本

**Comment by zhaohongxuan** [comment]
建议卸载重装插件，看是否能稳定复现

**Comment by milla** [comment]
> 建议卸载重装插件，看是否能稳定复现

替换template为自带后正常，貌似是我在properties中加了{{metaData.category}}
