### ISSUE TITLE
章节标题没有说明第几章

### ISSUE THREAD

**Issue by Leiyi548** [zhaohongxuan/obsidian-weread-plugin#255]
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/76139422/65b2862b-eb62-4761-a8a6-10a1417951c1)
这个只有章节名，并没有章节数。我看了下 issue，也没有看到别人怎么实现

**Comment by zhaohongxuan** [comment]
可以使用chapterIdx属性获取章节序号
<img width="317" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/bde5c752-dd31-46eb-8298-9da3b87f1c7c">

**Comment by Leiyi548** [comment]
> 可以使用chapterIdx属性获取章节序号 <img alt="image" width="317" src="https://private-user-images.githubusercontent.com/8613196/293829333-bde5c752-dd31-46eb-8298-9da3b87f1c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTY3NjMsIm5iZiI6MTcwNDI1NjQ2MywicGF0aCI6Ii84NjEzMTk2LzI5MzgyOTMzMy1iZGU1Yzc1Mi1kZDMxLTQ2ZWItODI5OC05ZGEzYjg3ZjFjN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDQzNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA4MjY2YTEyY2RmMjk1ZmUwM2IxZjk5OTE3YzAyZTc3MTNlMjQzOGYwNDY5ODdkNzhmMWNmYTJmZWQ3ZTBiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MyBfvsI9HrbvG3Mtqa5LeMaCw3WDXoAuC8xiITjtjLI">

好的，我还想再问一下，我每次修改了下模板，都要删除全部文件再sync一下才生效，能不能不删除文件然后就直接就同步模板。

**Comment by zhaohongxuan** [comment]
> > 可以使用chapterIdx属性获取章节序号 <img alt="image" width="317" src="https://private-user-images.githubusercontent.com/8613196/293829333-bde5c752-dd31-46eb-8298-9da3b87f1c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTY3NjMsIm5iZiI6MTcwNDI1NjQ2MywicGF0aCI6Ii84NjEzMTk2LzI5MzgyOTMzMy1iZGU1Yzc1Mi1kZDMxLTQ2ZWItODI5OC05ZGEzYjg3ZjFjN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDQzNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA4MjY2YTEyY2RmMjk1ZmUwM2IxZjk5OTE3YzAyZTc3MTNlMjQzOGYwNDY5ODdkNzhmMWNmYTJmZWQ3ZTBiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MyBfvsI9HrbvG3Mtqa5LeMaCw3WDXoAuC8xiITjtjLI">
> 
> 好的，我还想再问一下，我每次修改了下模板，都要删除全部文件再sync一下才生效，能不能不删除文件然后就直接就同步模板。

下个版本会增加右键菜单，刷新当前笔记

**Comment by Leiyi548** [comment]
> > > 可以使用chapterIdx属性获取章节序号 <img alt="image" width="317" src="https://private-user-images.githubusercontent.com/8613196/293829333-bde5c752-dd31-46eb-8298-9da3b87f1c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTY3NjMsIm5iZiI6MTcwNDI1NjQ2MywicGF0aCI6Ii84NjEzMTk2LzI5MzgyOTMzMy1iZGU1Yzc1Mi1kZDMxLTQ2ZWItODI5OC05ZGEzYjg3ZjFjN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDQzNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA4MjY2YTEyY2RmMjk1ZmUwM2IxZjk5OTE3YzAyZTc3MTNlMjQzOGYwNDY5ODdkNzhmMWNmYTJmZWQ3ZTBiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MyBfvsI9HrbvG3Mtqa5LeMaCw3WDXoAuC8xiITjtjLI">
> > 
> > 
> > 好的，我还想再问一下，我每次修改了下模板，都要删除全部文件再sync一下才生效，能不能不删除文件然后就直接就同步模板。
> 
> 下个版本会增加右键菜单，刷新当前笔记

好的，非常感谢，我十分期侍，感谢你这么好的插件。
