### ISSUE TITLE
[BUG]右键点击按钮时会被同时识别为左键点击

### ISSUE THREAD

**Issue by PupupupuTong** [zhaohongxuan/obsidian-weread-plugin#257]
**描述bug**

https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/69069739/d8f01a4e-b4bb-43e8-b194-583cdfb61e80

**重现步骤**
重现错误的步骤：
1.  右击插件按钮
2.  弹窗提示正在更新
3.  左击强制更新命令
4.  提示正在更新中请勿重复点击

**预期行为**

右击就是右击

**桌面（请填写以下信息）:**
 - 操作系统：win11
 - Obsidian版本： 1.5.3
 - 插件版本：0.8.0

**Comment by zhaohongxuan** [comment]
鼠标事件在windows上和macOS上不太一样，我这边可能需要适配一下
