### ISSUE TITLE
[BUG]`同步当前读书笔记`报错不能运行

### ISSUE THREAD

**Issue by PupupupuTong** [zhaohongxuan/obsidian-weread-plugin#258]
**描述bug**

控制台报错信息如下：

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/69069739/0aafb161-f654-4637-894e-e26cd70df812)

**重现步骤**
重现错误的步骤：
1.  在编辑区域右键打开菜单
2.  点击“同步当前读书笔记”。
3.  笔记无任何变化
4.  打开控制台查看报错内容

**预期行为**

正常更新当前笔记

**截图**

上附

**桌面（请填写以下信息）:**
 
- 操作系统：win11
 - Obsidian版本：1.5.3
 - 插件版本：0.8.0

**补充信息**

预设的模板有小瑕疵，`描述bug`和`**`中间多了个空格，重现步骤中的“4.”后方比前几条少了一个空格，“插件版本”后面缺了冒号，强迫症每次都要手动改。

另，更新到这个版本之后我已有文件的新笔记就无法直接同步了，必须删除文件重新同步才行。。。控制台显示：

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/69069739/9af11944-8cb3-450e-8173-80e50d10eb9d)

总之bug一堆，用着非常心累。。。。

**Comment by zhaohongxuan** [comment]
我测试的可能不是很全面，知道macOS上测试完没问题就发布了，这两个Bug我这边都不能reproduce，我今天晚上找个windows电脑测试一下。

ISSUE Template 你有意的话，可以提个PR改一下~ ，在.github文件夹下面。
