### ISSUE TITLE
有些笔记生成不了，console报错了

### ISSUE THREAD

**Issue by gongkaizh** [zhaohongxuan/obsidian-weread-plugin#26]
VM252:2 [HPM] Proxy created: /  -> https://weread.qq.com
VM252:2 [HPM] Proxy rewrite rule created: "^/refresh" ~> "/"
VM252:2 [HPM] Proxy created: /  -> https://i.weread.qq.com
VM252:2 Start syncing Weread note...
VM252:2 sync notebook:  四大沟通模式 null
VM252:2 Creating 读书/weixin/四大沟通模式.md
VM252:2 sync note book error 四大沟通模式 t {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…s>:2:1058069)\n    at Generator.next (<anonymous>)"}
VM252:2 sync notebook:  孙子兵法 null
VM252:2 Creating 读书/weixin/孙子兵法.md
VM252:2 sync note book error 孙子兵法 Error: File already exists.
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)

**Comment by gongkaizh** [comment]
不止这一本书生成不了，还有几本，都是同样的错，我就没截log过来了。另外只有“孙子兵法”这本书报了 文件已存在的错，其他的生成了的文件都很正常，没报错信息。

**Comment by zhaohongxuan** [comment]
如果是自己上传的书籍，获取元数据会报错，会在下个版本修复

**Comment by gongkaizh** [comment]
这应该不是自己上传的书，因为有几千本书，早就超限了，也上传不了。好像也没在微信读书里面上传过书。

**Comment by gongkaizh** [comment]
微信读书有些书以前有，现在都下架了，只有以前买过的人才能看，其他人都没法看，可能是这样的。我书架就有不少这样的书。

**Comment by gongkaizh** [comment]
我刚都搜了一下日志中报错的书，
共享经济2.0
EXO之我的男神张艺兴
这两本都能在微信读书上搜索到

**Comment by q823049029** [comment]
开发者大大，请问微信读书自己手动上传的书籍的笔记 能否做同步呢  谢谢您！~(*^_^*)
