### ISSUE TITLE
右上角通知提示更新了哪几本书

### ISSUE THREAD

**Issue by ormissia** [zhaohongxuan/obsidian-weread-plugin#260]
期待能在每一本书更新的时候在右上角提示，目前只能看到文档更新数量，只能通过提交git来判断哪些文档有过更新

<img width="353" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/55517494/eee18247-a76f-4651-8428-137a13eff302">

**Comment by zhaohongxuan** [comment]
更新一本书只需要不到1秒，每一本都提示不太可行，而且像我总共四百多本书，如果第一次同步的时候，那提示直接就炸了😂

**Comment by ormissia** [comment]
> 更新一本书只需要不到1秒，每一本都提示不太可行，而且像我总共四百多本书，如果第一次同步的时候，那提示直接就炸了😂

主要是增量时候不知道更新了啥
