### ISSUE TITLE
[BUG]dailynote块引用失败Unable to find section

### ISSUE THREAD

**Issue by asa-world** [zhaohongxuan/obsidian-weread-plugin#261]
dailynote创建的时候UID是错误的，多了一串数字，就导致Unable to find section，希望作者大大修复一下

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/86909426/2e38e899-0e8e-47d1-8d71-f92efac78c9b)

下面是正常的UID
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/86909426/dbefaeed-23f5-4224-8b46-9c4f52569e54)

**Comment by zhaohongxuan** [comment]
你这是自己修改了Temaplete吗？默认的bookmarkId是带bookId的呀

**Comment by asa-world** [comment]
哦哦懂了，我用的维基上的模板也没有带，我自己加上了{{metaData.bookId}}就好了，谢谢作者大大
