### ISSUE TITLE
[Feature]请问是否能同步书架没有笔记的书籍呢，谢谢

### ISSUE THREAD

**Issue by TCM8840** [zhaohongxuan/obsidian-weread-plugin#266]
**您的功能请求是否与问题有关？请描述。
清晰简洁地描述问题所在。

**描述您想要的解决方案**
清晰简洁地描述您想要发生的事情。

**描述您考虑过的替代方案**
清晰简洁地描述您考虑过的任何替代解决方案或功能。

**其他信息**
在此处添加有关新功能的其他信息或屏幕截图。

**Comment by zhaohongxuan** [comment]
这个插件不就是为了同步笔记吗。。没有笔记同步啥呢🤣

**Comment by lisasuosuo** [comment]
可以给一个开关嘛，也不是同步笔记，类似于标记读过的书。
