### ISSUE TITLE
[Feature]笔记内增加链接跳转回原文

### ISSUE THREAD

**Issue by anschein** [zhaohongxuan/obsidian-weread-plugin#267]
不知道微信读书的API是否支持，希望能够增加打开网页跳转至原文和笔记的位置

**Comment by zhaohongxuan** [comment]
API不支持，因为笔记的位置不是普通的HTML href，最多可以定位到网页阅读器的界面。

**Comment by anschein** [comment]
OK那我关闭问题了，希望有一天API能够支持
