### ISSUE TITLE
[BUG] 有些书籍导入报错

### ISSUE THREAD

**Issue by unix2dos** [zhaohongxuan/obsidian-weread-plugin#268]
有些书籍导入报错，无法导出，发现是作者的地方出现问题。

Obsidian 1.5.3
plugin: 0.8.2

**Comment by unix2dos** [comment]
测试了下，应该的特定的某本书无法导出。

**Comment by unix2dos** [comment]
<img width="588" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/22365670/a2a50d96-7947-4659-865d-11dc4f08c028">

**Comment by unix2dos** [comment]
应该是 author 带国家的会报错，可能是多了[ ] 符号，如上面的图。

**Comment by zhaohongxuan** [comment]
YAML语法里`[]` 代表的是数组，这里可能需要做转义，或者替换为中文的中括号`【】`，我更倾向于转换往往中文括号，下个版本里会做个fix~

**Comment by imaskcat** [comment]
我也遇到过，先加个replace替换一下。
`作者: {{metaData.author | replace(" ", "") | replace("[", "【") | replace("]", "】") }}`
