### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by purecritic** [zhaohongxuan/obsidian-weread-plugin#272]
**描述bug **
隔日笔记导入DailyNotes 无法导入，当日导入正常。
例：28日无法同步27日的笔记至27日DailyNotes

**预期行为**
次日能将之前的笔记按照笔记时间同步到DailyNotes

**Comment by zhaohongxuan** [comment]
如果要同步历史的笔记到DailyNotes 需要遍历所有的笔记详情和DailyNotes，相当于每次都全量同步所有笔记，如果数据多的话，可能需要好几分钟，太耗费资源了，而且意义不大，应该不会做。

**Comment by purecritic** [comment]
不知道能不能实现前一天的笔记历史记录导入，缩短遍历时间范围？
如果导入历史纪录必须遍历所有笔记详情确实得不偿失

**Comment by zhaohongxuan** [comment]
repeat with https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/283
