### ISSUE TITLE
[Feature]文件名可以设置为：bookId

### ISSUE THREAD

**Issue by weqoocu** [zhaohongxuan/obsidian-weread-plugin#273]
目前同步到obsidian的标题命名方式是这样的，这样会污染搜索关键词，搜索一些笔记，很多书名会影响搜索结果，我直接把微信读书同步文件夹进行了过滤。  看到豆瓣同步插件支持通过豆瓣ID命名，这个方式很好
<img width="221" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/edbc2765-7bd8-430a-9fe6-4fefc7e672db">
能否增加一个标题命名方式是只有bookid？ 这样书名就不会污染搜索。

<img width="837" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/32a53d47-f2fd-429a-b7c7-f79e24b147c6">

**Comment by zhaohongxuan** [comment]
倒是不难实现，只是比较疑惑上面说的『污染搜索』，能举个例子吗？ 如果只用id的话，你会使用方法来搜索自己想要的书籍笔记？

**Comment by weqoocu** [comment]
比如电影：年会不能停！

我自己会建立一个笔记“年会不能停！”， 然后记录对这个电影的互动记录和感悟，而豆瓣的电影元信息，我可以通过 属性进行检索。 但是搜索的时候不希望有第二个"年会不能停！"的笔记（dataview是一个整理笔记，所有的主题笔记都有）


![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/fd3ec90c-c456-44a0-8183-4a94aff68bc1)


<img width="716" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/35360006/44a00014-7e02-4f08-9f14-3bb356c8b2a5">
