### ISSUE TITLE
[BUG]在obsidian中登录微信读书，会弹出登录无效

### ISSUE THREAD

**Issue by Zhangqiaofeng-98** [zhaohongxuan/obsidian-weread-plugin#274]
**描述bug **
初次使用插件时，微信读书可以正常使用，隔一段时间后，发现在obsidian中微信读书的页面打不开，显示长时间未登录cookie无效，重新登录时，一直返回“加载微信读书登录页面失败”
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/44775951/21e0277d-34dd-4580-b5d9-a733e5b0db1a)

有尝试安装最新版插件、重启电脑、更新obsidian等操作

**Comment by zhaohongxuan** [comment]
这个bug目前我没法重现

**Comment by ddtoys** [comment]
我今天也遇到了一模一样的错误，也是正常使用一段时间，无征兆的出现楼主的报错。重启电脑，重启梯子or不用梯子，更新最新版ob，更新插件，均无果。目前是登录一切正常，只要一同步，就cookie长时间未登录云云，然后再从插件里查看登录状态，又恢复到未登录状态，让点击登录，重复也没用。
哎。。。不知道卡哪里了。
插件已卸载重装也不行

**Comment by ddtoys** [comment]
![Snipaste_2024-03-03_10-45-39](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/101969659/a3a0db7d-408d-4def-bc8d-95066930b6b4)
控制台截图

**Comment by ddtoys** [comment]
https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/101969659/b55375a5-9c57-4af5-a8f4-a0edc2dfe751
这个视频就是大致的报错情况，因为单手操作不容易录制到整体，反正就是：登录，然后推出插件页面，然后点击同步，然后就报错，然后再回到插件页面，就显示的“登录”按钮，即未登录状态

**Comment by ZiGmaX809** [comment]
同样bug，但是我解决了。

我是连点头像都无法点击，所以随便其他界面点进进入以后，可以点击头像退出了，重新登录就好了。

**Comment by yffat** [comment]
我遇到完全相同的问题，也尝试了插件手动重装、Obsidian全新重装、重开机等还是一样的提示“长时间未登入，Cookie已失效，请重新登入”，但是从插件设定页面登入又正常，只要一点选同步就出现上述讯息。

**Comment by thechosenonehaiou** [comment]
> 我遇到完全相同的问题，也尝试了插件手动重装、Obsidian全新重装、重开机等还是一样的提示“长时间未登入，Cookie已失效，请重新登入”，但是从插件设定页面登入又正常，只要一点选同步就出现上述讯息。

请问你解决了吗，我也是这样的问题，插件页面显示登录了，点击同步微信读书笔记，就会显示失败，并且去插件页面看，又要重新登陆了，一直这样循环，始终用不起来。

**Comment by ddtoys** [comment]
没有！哎！后来找了一个chrome插件，叫：微信读书导出。能满族基本需求吧，就是把笔记划线啥的导出，和一些基本数据。就是导出，复制，然后粘贴到ob新建文件里。。。多了几步，算是曲线救国吧

**Comment by BorkenX** [comment]
已经解决了，我也遇到了相同的问题，只要在登陆之后随便点开自已阅读的一本书之后就可以使用了，我想应该是cookie不同步的原因。

**Comment by zhaohongxuan** [comment]
微信读书网页版更新了，之前的登录手段不可以使用了，会在新版本中修复

**Comment by ddtoys** [comment]
辛苦啦！

HankZhao ***@***.***> 于2024年8月5日周一 19:03写道：
