### ISSUE TITLE
[Feature] 模板中，希望将想法中的 #标签 转换为双链， [[标签]] ，模板用这段话，怎么导入obsidian不生效？

### ISSUE THREAD

**Issue by weqoocu** [zhaohongxuan/obsidian-weread-plugin#277]
- {{ review.content | replace(r/#(.*?)[\s\b]/g, "[[\\1]]") }}

**Comment by weqoocu** [comment]
- {{ review.content | replace(r/#(.*?)(\s|$)/g, "[[\\1]]") }}
使用上面的脚本： #道歉  转化为了：[[\1]]   并没有转换为 [[道歉]]  是什么原因，如何修改代码

**Comment by zhaohongxuan** [comment]
你的正则表达式错了，我用下面的表达式可以work，你可以试试

```
- 💭 {{review.content | replace( r/(?<=^|\s)#([^\s]+)/g, '[[$1]]')}}
```

<img width="557" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/6f96567e-3f8b-437e-a979-058ccd803e54">


<img width="1069" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/a7419044-6716-4b16-ad91-72d7bc4937aa">

**Comment by zhaohongxuan** [comment]
same with: https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/215

**Comment by weqoocu** [comment]
太感谢了，解决了自己的问题

**Comment by zhaohongxuan** [comment]
不客气的，enjoy~

> 太感谢了，解决了很久没有搞定的问题， 问了好多人（包括大模型），还是大牛厉害
