### ISSUE TITLE
微信公众号订阅文章

### ISSUE THREAD

**Issue by jimchik** [zhaohongxuan/obsidian-weread-plugin#278]
之前可以保存微信公众号订阅文章的标注内容，近期发现原来好久的都没同步过来了。这个功能是没有了吗？

**Comment by zhaohongxuan** [comment]
之前的某个版本去掉了，后面考虑加一个开关，毕竟很多人不需要这个功能

**Comment by irisfish531** [comment]
这个功能超有用，超爱！

**Comment by jimchik** [comment]
> 之前的某个版本去掉了，后面考虑加一个开关，毕竟很多人不需要这个功能

有考虑恢复吗？这个还比较实用啊
