### ISSUE TITLE
Unable to find section

### ISSUE THREAD

**Issue by ethanchengyu** [zhaohongxuan/obsidian-weread-plugin#279]
**描述bug **
使用插件同步到dailynote时，出现错误无法显示划线想法： Unable to find section #^822995-50-2883-2918 in  明朝那些事儿（全集）

**截图**
![Xnip2024-02-15_13-43-14](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/25861044/259a2a25-de07-4d1a-9a60-a84c527eba55)

**桌面:**
 - 操作系统： [macOS 14.3.1 (23D60)]
 - Obsidian版本：[1.5.3]
 - 插件版本： [0.8.4]

**补充信息**
我实际查找到这个位置应该是ac9d28

**Comment by zhaohongxuan** [comment]
Daily Notes 不支持自定义模板

**Comment by ethanchengyu** [comment]
意思是每个笔记需要同步后手动改块引用位置是吗？有没有别的解决方法呢，感觉这样同步到日记中意义不大了

**Comment by zhaohongxuan** [comment]
现在不支持想法，只支持划线同步，你说的『我实际查找到这个位置应该是ac9d28』这个位置可能是想法？

**Comment by ethanchengyu** [comment]
嗯，是的。懂了，日记中没法同步过来想法
还有就是我的公众号文章划线、想法都没同步过来，公众号也上了我的书架，单独的文章也在收藏文章中，可是就是内容没同步过来

**Comment by zhaohongxuan** [comment]
公众号同步的功能之前有，后来移除了，后面会加回来的
