### ISSUE TITLE
[Feature]高亮划线和读书笔记能不能不分开

### ISSUE THREAD

**Issue by fenghong66** [zhaohongxuan/obsidian-weread-plugin#280]
读书笔记能不能不单独移出来到一个新章节，直接想法下面+引用，这样看着高亮笔记莫名的少了一段，不连贯。比如下面notion的weread插件
![Snipaste_2024-02-21_21-56-28](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/56968140/c974ba75-00d8-4f0b-b1ef-be09a0d2aa31)

或者把划线全部合并到一块。让人整整齐齐看得舒服点

**Comment by zhaohongxuan** [comment]
默认的模板就是支持的，你也可以爬楼找一找其他的模板
<img width="865" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/99f5016e-4241-4c00-b242-843addadd598">

**Comment by fenghong66** [comment]
> 默认的模板就是支持的，你也可以爬楼找一找其他的模板 <img alt="image" width="865" src="https://private-user-images.githubusercontent.com/8613196/306653123-99f5016e-4241-4c00-b242-843addadd598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjY4OTcsIm5iZiI6MTcwODUyNjU5NywicGF0aCI6Ii84NjEzMTk2LzMwNjY1MzEyMy05OWY1MDE2ZS00MjQxLTRjMDAtYjI0Mi04NDNhZGRhZGQ1OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTQ0MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ5NGE4YmM0OGNmYzdjYTRiODIxNWM4NGQ4N2MyYzk4ZDcyYTIzZTQ0M2Q3YjY2N2Y5MDk4OTc1YzE1NjQzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qeFcGa4VajKtaBl0Cb8PWvr3vCs1dzrSKMcPcALSi7U">

感谢，爬到了
