### ISSUE TITLE
求一个能更新并查看读书进度的元数据

### ISSUE THREAD

**Issue by WinHex89** [zhaohongxuan/obsidian-weread-plugin#286]
比如说，current是当前的读书页数，total是总的页数，这两个在同步后都能更新
方便掌握读书进度，同时能在dataview中查看
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/134070684/47ae46b7-a076-4839-a575-836fa3860d63)

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/134070684/d10b0ce4-9206-45de-a20f-7fe0a8c57dd5)

**Comment by WinHex89** [comment]
我刚发现0.7的版本有progress的元数据，但我不知道怎么设置才对
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/134070684/ad4e8a5e-0b41-4c03-ba1b-072c6c9da4aa)

**Comment by zhaohongxuan** [comment]
frontmatter中本来就有， 正文里面，需要自己修改模板。　
<img width="1030" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/47fafb12-9708-4b4d-a968-721e2d2d7805">
