### ISSUE TITLE
求一个关闭笔记划线时间按钮[Feature]

### ISSUE THREAD

**Issue by LEI626** [zhaohongxuan/obsidian-weread-plugin#287]
想让笔记界面更简洁一点，不知道笔记的划线时间是否可以关闭。如果不行的话是否能加入一个关闭的按钮，感谢。

**Comment by zhaohongxuan** [comment]
模板自己可以修改的，在设置里把模板中的时间部分去掉就好了，你也可以在评论区找找其他人的模板。
<img width="1078" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/612288e8-2574-4158-af4d-233ec2f7ae3c">

**Comment by LEI626** [comment]
好的，谢谢

**Comment by LEI626** [comment]
您好，我是编程小白，麻烦再问一下，我已经在设置里删掉了你说的这个时间变量，但是为什么读书笔记里还是有时间呀，删完这里还需要什么操作吗？万分感谢

**Comment by LEI626** [comment]
您好，我是编程小白，麻烦再问一下，我已经在设置里删掉了您说的这个时间变量，但是为什么读书笔记里还是有时间呀，删完这里还需要什么操作吗？万分感谢
