### ISSUE TITLE
[BUG] 当评论中有标签#时，插入今日日志中的格式会出问题

### ISSUE THREAD

**Issue by andytree** [zhaohongxuan/obsidian-weread-plugin#289]
**描述bug **
首先确定bug能稳定复现，对报错信息进行清晰简洁描述，如果描述不清晰，issue将会关闭
微信阅读中的内容
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/b17fe733-7cc6-4d75-a6df-a29fdfd7fe12)
同步的笔记--错位了，不知道是不是换行导致的
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/d03c07ca-f363-4f83-94e1-ef0df40da539)

插入今日文档中的显示
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/0bb13f31-13fd-48ae-9e7e-f4d08733b54e)

**预期行为**
可以正常把笔记引用到今日日记中，另外生成的块标签是有问题的。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）:**
 - 操作系统：win 10
 - Obsidian版本：V1.5.11
 - 插件版本：0.10.0

**移动端（请填写以下信息）:**
 - 设备：[例如 iPhone14]
 - 操作系统：[例如 iOS16]
 - Obsidian版本：[例如 1.5.3]
 - 插件版本：[例如 0.7.1]

**补充信息**
在此处添加有关该问题的任何信息。

**Comment by zhaohongxuan** [comment]
这个是 markdown自己的特性，obsidian中的bullet list不能嵌套换行，可以尝试把评论里的换行去掉。

**Comment by andytree** [comment]
换行那个解释我理解，谢谢，
另外只有一行内容，也插入不了。自动生成的引用ID有问题，无法正常引用，自己修改下ID才行。
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/67ad8f77-da81-43b5-af66-dd3d1f0f7cf9)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/c76b3a0d-3282-44a7-9302-cf549d8196a1)
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/4092785/0ecd3ff0-3b7b-47e6-9ffa-2f7ddfef4143)

**Comment by zhaohongxuan** [comment]
DailyNotes 现在还不支持评论，后面有时间了看怎么加

**Comment by Mdreame** [comment]
我的笔记在导入到ob时`#标签`总是被转换成`[[]]`的格式，这个不知道怎么解决。这个是ob的问题吗？

![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/21331592/9ce90ff8-eb33-4201-9ea7-324f839f66a7)

**Comment by zhaohongxuan** [comment]
> 我的笔记在导入到ob时`#标签`总是被转换成`[[]]`的格式，这个不知道怎么解决。这个是ob的问题吗？
> 是不是开启了这个选项？
> ![image](https://private-user-images.githubusercontent.com/21331592/320279016-9ce90ff8-eb33-4201-9ea7-324f839f66a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTMwNDIsIm5iZiI6MTcxMjU1Mjc0MiwicGF0aCI6Ii8yMTMzMTU5Mi8zMjAyNzkwMTYtOWNlOTBmZjgtZWIzMy00MjAxLTllYTctMzI0ZjgzOWY2NmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ODkzN2U3ZjY2YWM0NDc0OGU0NDYyZjg4N2JmNGE4MmJlOTQxMzJmMjg2YzFlZGZkOWIyYTgzNzA5MWUyNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MWrfITQq0yg34RWknHx6hFVXfTv4AocK_Zz75xyAytM)

<img width="1089" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/237eb00d-c5e1-4dcd-b1d0-c67740b21bf9">

**Comment by Mdreame** [comment]
> > 我的笔记在导入到ob时`#标签`总是被转换成`[[]]`的格式，这个不知道怎么解决。这个是ob的问题吗？
> > 是不是开启了这个选项？
> > ![image](https://private-user-images.githubusercontent.com/21331592/320279016-9ce90ff8-eb33-4201-9ea7-324f839f66a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTMwNDIsIm5iZiI6MTcxMjU1Mjc0MiwicGF0aCI6Ii8yMTMzMTU5Mi8zMjAyNzkwMTYtOWNlOTBmZjgtZWIzMy00MjAxLTllYTctMzI0ZjgzOWY2NmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ODkzN2U3ZjY2YWM0NDc0OGU0NDYyZjg4N2JmNGE4MmJlOTQxMzJmMjg2YzFlZGZkOWIyYTgzNzA5MWUyNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MWrfITQq0yg34RWknHx6hFVXfTv4AocK_Zz75xyAytM)
> 
> <img alt="image" width="1089" src="https://private-user-images.githubusercontent.com/8613196/320359590-237eb00d-c5e1-4dcd-b1d0-c67740b21bf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTQ0NjksIm5iZiI6MTcxMjU1NDE2OSwicGF0aCI6Ii84NjEzMTk2LzMyMDM1OTU5MC0yMzdlYjAwZC1jNWUxLTRkY2QtYjFkMC1jNjc3NDBiMjFiZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDUyOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUyMTRlZGMyNmY4OTI5NGQxY2ZlMWRkOWFkNDQ1N2FlNzQ3ZjVkNmI2NWU2ZjZjMTJkNzM3NTBjNDEzZDc4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FWRmkAuOZrZzt2yi8NTwymwngnoxBPThYRtHtYLqfRg">

原来在这😂，哈哈，我在ob设置里找半天。不过现在已经默认将标签转换成双链了，这样导入到anki中点击链接可以跳转回ob。很方便，感谢🙏。
