### ISSUE TITLE
是否能增加同步笔记图片的功能

### ISSUE THREAD

**Issue by guainanguode** [zhaohongxuan/obsidian-weread-plugin#292]
**描述您想要的解决方案**
增加同步笔记图片的功能

**描述您考虑过的替代方案**
一些浏览器扩展可以实现同步微信读书笔记时附带图片链接，如https://github.com/sancijun/weread-toolbox, 但是对导出模板的编辑功能不足。

**其他信息**
导出笔记时只会显示  [插图]  ，而没有图片链接

**Comment by zhaohongxuan** [comment]
目前没有办法：参考 https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/241
