### ISSUE TITLE
[Feature] 创建一个包含双链的总览页面

### ISSUE THREAD

**Issue by XiaotongChel** [zhaohongxuan/obsidian-weread-plugin#297]
我试图创建一个列表来总览所有书籍，并让这些书在关系图谱中属于一个父节点。
为了达成这一目的，我试图使用Dataview和DataviewJs创建列表，但没有找到好方法来添加双链。因此，尽管我能输出列表，但在关系图谱中每本书依然是孤立点。
是否有人可以帮忙提供可以在关系图谱里整合书籍的方案，或是添加相关新功能？谢谢！

**Comment by zhaohongxuan** [comment]
可以在模板的顶部加上双链指向的笔记，比如我的是【微信读书】，你可以根据自己的需求更改。
<img width="787" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/dbd02d3d-653a-48f1-851e-445a187ca8b2">

效果如下：
<img width="1072" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/80d06e47-8656-465d-8637-7ec2d8adf912">

**Comment by XiaotongChel** [comment]
> 可以在模板的顶部加上双链指向的笔记，比如我的是【微信读书】，你可以根据自己的需求更改。 <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/8613196/324245753-dbd02d3d-653a-48f1-851e-445a187ca8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDc0MjUsIm5iZiI6MTcxMzcwNzEyNSwicGF0aCI6Ii84NjEzMTk2LzMyNDI0NTc1My1kYmQwMmQzZC02NTNhLTQ4ZjEtODUxZS00NDVhMTg3Y2E4YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTM0NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNlMGZlNzQwOWQwNDY2ZTBlOWEyYjcxYjU1NmEwYmIyODU3YmQyMzFlMGQ1ZWI4MmNhYTFiNWI2ZWEwZGQ0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TUV4WHTJKNdP9j8MTAbbIz6gSHEVZ9vB9Pkx5vWkDv4">
> 
> 效果如下： <img alt="image" width="1072" src="https://private-user-images.githubusercontent.com/8613196/324245581-80d06e47-8656-465d-8637-7ec2d8adf912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDc0MjUsIm5iZiI6MTcxMzcwNzEyNSwicGF0aCI6Ii84NjEzMTk2LzMyNDI0NTU4MS04MGQwNmU0Ny04NjU2LTQ2NWQtODYzNy03ZWMyZDhhZGY5MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTM0NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZlOGIyODVhOWFiOTFkYTY1MjEyOTgwMmY3ZWY2YzkyYThjZTNjM2FlODI1MWZiM2EwNWQxZWQ3OTc3NDhhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CVRwoa9SjnS2UEsFR6XZzgtlqTu59Kij6alyiKhJIAk">

成功了！谢谢！！
