### ISSUE TITLE
[BUG]如果高亮划线有多行的话，无法显示在一个块中

### ISSUE THREAD

**Issue by zfeny** [zhaohongxuan/obsidian-weread-plugin#302]
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/110285698/c3c24d95-2a1a-40d2-b3ac-92834cb14960)

猜测是highlight.content的问题，怎么处理呀？

**Comment by zhaohongxuan** [comment]
markdown格式的话，如果是多行的话确实是不算同一个block的，除非去掉换行
