### ISSUE TITLE
[Feature] 请问在生成内容的时候，如何不生成属性信息呢？

### ISSUE THREAD

**Issue by i-iooi-i** [zhaohongxuan/obsidian-weread-plugin#307]
![image](https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/1827701/d1eb46b5-03be-4b85-a161-bf5233e9f32a)

请问在生成内容的时候，如何不生成属性信息呢？ 这部分没有找到可以自定义的区域。

**Comment by lisasuosuo** [comment]
怎么解决的呢

**Comment by i-iooi-i** [comment]
> 怎么解决的呢

没有解决。
因为发现了一款很强大的Components插件，可以用来做书库，而做书库刚好可以用到这些属性信息。
就干脆不解决了。 

https://www.bilibili.com/video/BV1AF4m1T79g/?spm_id_from=333.337.search-card.all.click&vd_source=c817e4f9bbdff10c17a3f375f2c87de5
