### ISSUE TITLE
元数据readingTime与dataview搭配时显示问题

### ISSUE THREAD

**Issue by littleyz** [zhaohongxuan/obsidian-weread-plugin#313]
目前阅读时长的元数据readingTime显示的值是x小时x分钟。
采用这个元数据 用dataview 排序时，显示有点问题，只能显示10小时以下的。比如9小时29分钟能显示，11小时22分钟的就不能显示，似乎与dataview有点冲突。不知问题出在哪。

能否将readingTime的值修改成分钟。xx分钟，不要小时。
readingTime：618分钟
而不用 readingTime：10小时18分钟

**Comment by zhaohongxuan** [comment]
readingTime这个字段应该不会改了，后面会再加一个字段

**Comment by zhaohongxuan** [comment]
现在metaData.readInfo中已经有readingTime了，这个字段是以秒展示的，可以使用过滤器转换一下：
`{{(metaData.readInfo.readingTime/60) | round}}`

**Comment by littleyz** [comment]
> 看了下代码，不需要增加字段了，现在metaData.readInfo中已经有readingTime了，这个字段是以秒展示的，可以使用过滤器转换成分钟： `{{(metaData.readInfo.readingTime/60) | round}}`，你可以试试

可行。非常感谢！
