### ISSUE TITLE
[BUG]微信本地导入的图书同步之后readingStatus有错误

### ISSUE THREAD

**Issue by purecritic** [zhaohongxuan/obsidian-weread-plugin#317]
**描述bug **
微信本地导入的图书同步之后readingStatus有错误，显示为"readingStatus: 未标记“，微信平台的图书同步没有问题。

**重现步骤**
重现错误的步骤：
1.  本地导入书籍
2. 微信读书划线
3.  点击”同步”
4. readingStatus有错误，显示为"readingStatus: 未标记“

**不便之处**
这个字段错误导致每次同步要手动去修改字段值，修改后才能使用dataview展示在读书籍

**截图**
<img width="759" alt="Screenshot 2024-06-07 at 21 56 01" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/107492378/9526fac4-8bb6-44f7-9615-d25a77f27fad">

**Comment by zhaohongxuan** [comment]
readingStatus 默认就是没有值的，书城的书籍微信读书会根据进度更改状态。

**Comment by purecritic** [comment]
感谢回复，我看了一下微信读书外部导入的书籍确实没有在读状态。
