### ISSUE TITLE
同步至日记中有问题

### ISSUE THREAD

**Issue by jun47444** [zhaohongxuan/obsidian-weread-plugin#323]
**描述bug**
## 不知道是不是这里的问题，有没有什么解决办法。

**截图**
# 正常应该是这样的。
![image](https://github.com/user-attachments/assets/801ff550-38e2-46f1-a9aa-b2364807d454)

# 这是今天出现问题的情况。
![image](https://github.com/user-attachments/assets/bbf4b218-88db-4b58-929f-f2354199555e)
这是今天出现问题的情况。

![image](https://github.com/user-attachments/assets/41368534-b84e-475e-8069-877df051f993)

**重现步骤**
重现错误的步骤：
1.  点击左边的插件的图标
2. 出现保存笔记到daily notes的错误

**桌面（请填写以下信息）:**
 - 操作系统： 例如 Windows 11
 - Obsidian版本： v1.6.1
 - 插件版本： 0.11.0

**Comment by zhaohongxuan** [comment]
公众号还没时间做适配。。

**Comment by jun47444** [comment]
> 公众号还没时间做适配。。

希望作者大大可以安排一下，之前我用微信读书看公众号的时候都是将一些有灵感的句子复制粘贴到ob，步骤比较多。但是前段时间看到这个插件有这个功能感觉自动同步会方便很多。

**Comment by zhaohongxuan** [comment]
> > 公众号还没时间做适配。。
> 
> 希望作者大大可以安排一下，之前我用微信读书看公众号的时候都是将一些有灵感的句子复制粘贴到ob，步骤比较多。但是前段时间看到这个插件有这个功能感觉自动同步会方便很多。

已经修复了，重新同步就可以了
