### ISSUE TITLE
[BUG] 无法登录

### ISSUE THREAD

**Issue by kinxuchen** [zhaohongxuan/obsidian-weread-plugin#324]
**描述bug **
无法登录
**重现步骤**
重现错误的步骤：
1.  点击登录
2.  弹出网页后登录微信读书
3.  插件登录状态不更新

**预期行为**
登录后插件状态还是未登录

**截图**
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/af199634-9c2d-459b-98f7-00340b964248">

**桌面（请填写以下信息）:**
 - 操作系统：MacOS 14.3.1
 - Obsidian版本：1.6.7
 - 插件版本： 0.11.0

**移动端（请填写以下信息）:**
 - 设备：[例如 iPhone14]
 - 操作系统：[例如 iOS16]
 - Obsidian版本：[例如 1.5.3]
 - 插件版本：[例如 0.7.1]

**补充信息**
在此处添加有关该问题的任何信息。

**Comment by Wjiajie** [comment]
我也遇到类似的问题，但我这边，点击书架中任意一本书，就能正确刷出登陆状态了

**Comment by realfash** [comment]
> 我也遇到类似的问题，但我这边，点击书架中任意一本书，就能正确刷出登陆状态了

感谢，我弄了几天，终于可以同步了

**Comment by zhaohongxuan** [comment]
感谢反馈，确实是微信读书升级了，首页登录成功之后不会获取用户信息了，所以无法拦截请求拿到cookie了，点击进入书架就可以了，点任意一本书也可以，我先看下修复的方案。
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/e14f577f-5596-47ab-b2ef-09934479d012">
