### ISSUE TITLE
[BUG]同步微信读书笔记异常 

### ISSUE THREAD

**Issue by mars704** [zhaohongxuan/obsidian-weread-plugin#346]
**描述bug**
最近几周一直无法同步微信读书笔记，也重新登录过账号，还是不行，报错如下：
同步微信读书笔记异常 Error: get weread note book error after retry
    at L.eval (plugin:obsidian-weread-plugin:2:394479)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-weread-plugin:2:373182)

**截图**
![image](https://github.com/user-attachments/assets/d468a96d-6d7e-4da9-a54c-a68e4b87797a)

**桌面（请填写以下信息）:**
 - 操作系统： macOS Sonoma 14.7
 - Obsidian版本：1.7.7
 - 插件版本： 0.11.2

**Comment by Fanduzi** [comment]
same issue

**Comment by lxiiiixi** [comment]
同样遇到了这个问题，也无法正常登陆。

**Comment by Enoch2090** [comment]
same issue

**Comment by luozhaohui** [comment]
碰到同样的问题，可能是因为多设备登录导致的。以下是我的解决办法：

1. 登录：先插件的点击登录，扫码登录。（如果已经登录忽略此步骤）
2. 登出：在登录后的微信读书弹出界面中点击个人头像，选择退出（以清除 cookie）。
3. 再登录：再次点击插件的登录按钮，扫码登录即可。

To log out and then log back in using the plugin, follow these steps:

1. Initial Login: Use the plugin to click login or scan the code to log in.
2. Log Out: After logging in, when the WeChat Reader pop-up interface appears, click on your profile avatar. Select "Logout" to clear the cookies.
3. Re-login: Once logged out, click the login button on the plugin again. Use the scan code method to log back in.

This process ensures that you completely log out (clearing any saved session data) before attempting to log in again, which can be useful for switching accounts or troubleshooting login issues.

**Comment by mars704** [comment]
> 碰到同样的问题，可能是因为多设备登录导致的。以下是我的解决办法：
> 
> 1. 登录：先插件的点击登录，扫码登录。（如果已经登录忽略此步骤）
> 2. 登出：在登录后的微信读书弹出界面中点击个人头像，选择退出（以清除 cookie）。
> 3. 再登录：再次点击插件的登录按钮，扫码登录即可。
> 
> To log out and then log back in using the plugin, follow these steps:
> 
> 1. Initial Login: Use the plugin to click login or scan the code to log in.
> 2. Log Out: After logging in, when the WeChat Reader pop-up interface appears, click on your profile avatar. Select "Logout" to clear the cookies.
> 3. Re-login: Once logged out, click the login button on the plugin again. Use the scan code method to log back in.
> 
> This process ensures that you completely log out (clearing any saved session data) before attempting to log in again, which can be useful for switching accounts or troubleshooting login issues.

我按您的方法尝试了，解决了我的问题，多谢分享！
