### ISSUE TITLE
安装插件后，无法登录微信读书

### ISSUE THREAD

**Issue by Tong-fr** [zhaohongxuan/obsidian-weread-plugin#36]
请问下，在Obsidian的插件中登录“微信读书”，但是扫描二维码后，会直接退出Obsidian，这是怎么情况？

**Comment by zhaohongxuan** [comment]
@Tong-fr 打开控制台把报错的日志贴出来

**Comment by bujibuji6666** [comment]
我也是，登录就闪退

**Comment by bujibuji6666** [comment]
控制台在哪里呀

**Comment by fpk7660837** [comment]
在obsidian的顶部菜单中 View-> Toggle Developer Tools
<img width="239" alt="image" src="https://user-images.githubusercontent.com/7249798/169938965-f0626abe-d86a-4aa2-90cc-ef47b6822dae.png">

**Comment by Tong-fr** [comment]
我这版本是不是有问题，
看不到顶部的菜单....


这个截图是我ob的左侧部分：

这是顶部的截屏:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaohongxuan/obsidian-weread-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)





 
在obsidian的顶部菜单中 View-&gt; Toggle Developer Tools

**Comment by zhaohongxuan** [comment]
@Tong-fr 图没贴上来啊😢

**Comment by Tong-fr** [comment]
Obsidian v0.14.6


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaohongxuan/obsidian-weread-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)





 
@Tong-fr 图没贴上来啊😢

**Comment by bujibuji6666** [comment]
![Quicker_20220524_113936](https://user-images.githubusercontent.com/105926665/169966003-c46ddb46-527d-4c95-a2cb-5f6219531fff.png)
然后在哪里找到呀

**Comment by bujibuji6666** [comment]
> Obsidian v0.14.6
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhaohongxuan/obsidian-weread-plugin" ***@***.***&gt;; 发送时间:&nbsp;2022年5月24日(星期二) 中午11:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36) @Tong-fr 图没贴上来啊😢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

不是软件里找，是插件登录的页面左上角

**Comment by bujibuji6666** [comment]
我有尝试看是不是别的插件影响的原因，新建了一个库，只放了这个插件结果还是闪退

**Comment by zhaohongxuan** [comment]
@bujibuji6666 console里面
<img width="475" alt="image" src="https://user-images.githubusercontent.com/8613196/169973226-a325c04e-bf23-40a6-8130-4f70006657ae.png">

**Comment by Tong-fr** [comment]
Console里面没东西。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaohongxuan/obsidian-weread-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)





 
@bujibuji6666 console里面

**Comment by bujibuji6666** [comment]
> Console里面没东西。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhaohongxuan/obsidian-weread-plugin" ***@***.***&gt;; 发送时间:&nbsp;2022年5月24日(星期二) 下午3:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36) @bujibuji6666 console里面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我也是，然后想是不是因为是重新打开的obsidian没有留下来失败的记录，就打开着console登录了一次，结果现在连二维码还没蹦出来，就已经闪退出去了，console也没办法打开了，接下来靠你了 @Tong-fr

**Comment by Tong-fr** [comment]
我晕，控制台又出现信息了，，，，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "105577946"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午3:31
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)






Console里面没东西。。。



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhaohongxuan/obsidian-weread-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)





 
@bujibuji6666 console里面

**Comment by zhaohongxuan** [comment]
打开一个新的vault，只安装weread插件试试

**Comment by Tong-fr** [comment]
从新打开了一个vault，还是闪退；
这次我在控制台上，找到这个信息，请参考。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaohongxuan/obsidian-weread-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)





 
打开一个新的vault，只安装weread插件试试

**Comment by zhaohongxuan** [comment]
图一直都没贴成功过🤨

**Comment by zhaohongxuan** [comment]
首页有我邮箱，直接我发

**Comment by scottzhangzxy** [comment]
同样遇到了这个问题，扫码之后obsidian就闪退，请问这个问题现在解决了吗？

**Comment by zhaohongxuan** [comment]
> 同样遇到了这个问题，扫码之后obsidian就闪退，请问这个问题现在解决了吗？
是什么系统？win11？

**Comment by Tong-fr** [comment]
控制台在哪里？帮忙截个图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月22日(周日) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaohongxuan/obsidian-weread-plugin] 安装插件后，无法登录微信读书 (Issue #36)




 
@Tong-fr 打开控制台把报错的日志贴出来
