### ISSUE TITLE
每本书的编号可选

### ISSUE THREAD

**Issue by SeyeeL** [zhaohongxuan/obsidian-weread-plugin#38]
现在是为了避免书名重复吗？可不可以设置成新建页面有存在这个书名时才加上编号，我几乎没有同名的书，全是编号好难受。
要是可以设置书名重复是加上作者名而不是编号区分就更好了。

**Comment by 7enChan** [comment]
同感，建议可以自定义书名，比如我一般会在书名前加上 emoji 和笔记中其他同名文件做区分，书名本身有重复的可以再加其他信息补充。

**Comment by zhaohongxuan** [comment]
@7enChan @SeyeeL 后面会做文件名模板
