### ISSUE TITLE
请问是否可以支持公众号文章阅读标注的同步？

### ISSUE THREAD

**Issue by mengtanx** [zhaohongxuan/obsidian-weread-plugin#41]
如题，不知道微信读书API是否提供了这个接口。

**Comment by zhaohongxuan** [comment]
> 如题，不知道微信读书API是否提供了这个接口。

有接口，现在也可以同步，只是公众号内没有按照文章进行group，所以看上去有点乱，后面需要理一下接口，重新写公众号的实现。
