### ISSUE TITLE
手机端插件无法打开

### ISSUE THREAD

**Issue by shanyang121** [zhaohongxuan/obsidian-weread-plugin#45]
我是用的iphone ，电脑端的插件可以打开，手机端的可以被OBsidian识别，但是无法打开，点击那个打开插件的按钮，没有反应。不知道有没有适配移动端，哈哈。感觉手机端能用的话会方便很多。希望作者考虑适配手机端

**Comment by zhaohongxuan** [comment]
> 我是用的iphone ，电脑端的插件可以打开，手机端的可以被OBsidian识别，但是无法打开，点击那个打开插件的按钮，没有反应。不知道有没有适配移动端，哈哈。感觉手机端能用的话会方便很多。希望作者考虑适配手机端

我在mobile端禁用了，因为使用electron库来支持扫码登录，所以没法在mobile端使用，现在还没找到合适的办法在mobile端实现这个功能。 后面再研究一下有没有替代方案。

**Comment by zhaohongxuan** [comment]
> 你好，请问扫码登录是用来获取用户信息的么？如果这样的话，现在很多用户都会用到同步功能，在未登录的情况下，可不可以让移动端显示类似“请使用桌面端登录”这种的提示，桌面端登录后直接同步桌面端的用户信息？
这个思路不错👍🏻，我思考下解决方案。
