### ISSUE TITLE
微信读书内更改后的"划线评论"无法同步更新

### ISSUE THREAD

**Issue by kitaev-chen** [zhaohongxuan/obsidian-weread-plugin#46]
微信读书网页版无法编辑评论，一个变通的方法是，删除评论，同时在原文相同处划线后再重新评论，这样的更改目前插件还无法同步更新，显示的还是旧评论。

**Comment by zhaohongxuan** [comment]
@kitaev-chen 你好，同步的逻辑是header中`reviewCount`和`noteCount`变化才会触发，你删除了一条重新添加reviewCount和noteCount就还是原来的值，所以不会更新，最简单的方案是，再划线一个地方，或者在obsidian里修改front matter里的reviewCount然后重新同步就有了。
<img width="896" alt="image" src="https://user-images.githubusercontent.com/8613196/172135310-712942b5-26c5-410c-87c6-fb6cbd37928d.png">
