### ISSUE TITLE
0.2.3 使用只能同步最新的一本书籍，0.2.2正常

### ISSUE THREAD

**Issue by shen-qs** [zhaohongxuan/obsidian-weread-plugin#48]
如题。

**Comment by zhaohongxuan** [comment]
我这边测试没问题，你修改header里的noteCount试试看能同步成功不

**Comment by shen-qs** [comment]
> 

因为我不太懂 JS， 看起来费劲，所以只是定位了一下报错。

export const parseHighlights = (highlightData: any, reviewData: any): Highlight[] => {
//应该是这句
const chapters: [] = highlightData['chapters'].length ===0 ? highlightData["refMpInfos"] : highlightData['chapters'];
//看了下历史，改回0.2.2版本的 const chapters: [] = highlightData['chapters'];  就没问题了。
......
}

具体报错信息是：
`TypeError: Cannot read properties of undefined (reading 'map')`

可能的复现：
我的微信读书最近一本书，只做了高亮划线，没有做一条笔记。
同步的时候这本（只有划线的书），是可以down 下来的。

**Comment by zhaohongxuan** [comment]
好的，感谢提供信息~

**Comment by zhaohongxuan** [comment]
最小划线调整到无限制之后重现了。
