### ISSUE TITLE
使用体验

### ISSUE THREAD

**Issue by luojiadream** [zhaohongxuan/obsidian-weread-plugin#49]
请问能不能把“划线评论”和“高亮划线”的内容合并，这样的话相同章节的内容会放到一块，避免分成两部分，产生割裂感觉。

**Comment by SeyeeL** [comment]
https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/56#issue-1281552886
可以参考下我的模板

**Comment by luojiadream** [comment]
您的邮件我已收到，祝您工作顺利！

**Comment by luojiadream** [comment]
您的邮件我已收到，祝您工作顺利！
