### ISSUE TITLE
高亮划线的块引用有问题

### ISSUE THREAD

**Issue by Abandon339** [zhaohongxuan/obsidian-weread-plugin#59]
![image](https://user-images.githubusercontent.com/47665382/176477386-00bd8cc8-6bad-49b1-a96f-99bee771278b.png)
块引用的id出现了下划线，可能不符合id命名的规范

**Comment by zhaohongxuan** [comment]
> ![image](https://user-images.githubusercontent.com/47665382/176477386-00bd8cc8-6bad-49b1-a96f-99bee771278b.png) 块引用的id出现了下划线，可能不符合id命名的规范
下个版本修复一下，目前可以自己手动改一下模板，把下划线改成dash符号

**Comment by AndyLiu9** [comment]
不好意思，我更新到最新版之后，高亮id的下划线还是没有被替换成-，能麻烦再帮忙看一下不

**Comment by wenlzhang** [comment]
> 不好意思，我更新到最新版之后，高亮id的下划线还是没有被替换成-，能麻烦再帮忙看一下不

@AndyLiu9 另外一个解决方案是修改模板，可以把包含 `Id` 的部分稍作调整。比如，`^{{review.reviewId}}` 可以替换成 `^{{review.reviewId | replace("_", "-")}}`。

**Comment by AndyLiu9** [comment]
谢谢！我刚刚发现原来我得把之前的笔记删掉、重新同步才能体现出来id的变化，不过两种方法都好用！

**Comment by zhaohongxuan** [comment]
> 谢谢！我刚刚发现原来我得把之前的笔记删掉、重新同步才能体现出来id的变化，不过两种方法都好用！

新版本增加了一个强制同步的功能，可以试一下，不需要删掉笔记，因为笔记的frontmatter里可能记录有自定义的内容，直接强制同步就可以了。
