### ISSUE TITLE
obsidian 微信读书模板

### ISSUE THREAD

**Issue by smallSpoon** [zhaohongxuan/obsidian-weread-plugin#60]
---
isbn: {{metaData.isbn}}
category: {{metaData.category}}
---
## Meta
> [!abstract] {{metaData.title}}
> - ![ {{metaData.title}}|200]({{metaData.cover}})
> - 书名： {{metaData.title}}
> - 作者： {{metaData.author}}
> - 简介： {{metaData.intro}}
> - 出版时间 {{metaData.publishTime}}
> - ISBN： {{metaData.isbn}}
> - 分类： {{metaData.category}}
> - 出版社： {{metaData.publisher}}

{% if bookReview.bookReviews %}{% for bookReview in bookReview.bookReviews %}
{% if loop.first %}{% if bookReview.mdContent.length %}#本书评论{% endif %}{% endif %}
{% if bookReview.mdContent.length %}- {{bookReview.mdContent}} ^{{bookReview.reviewId}}
[[{{bookReview.createTime.slice(0, 10)}}]]{{bookReview.createTime.slice(10, 16)}}
{% endif %}{% endfor%}{% endif %}

{% for chapter in bookReview.chapterReviews %}{% if chapter.reviews or chapter.chapterReview %}{% if  chapter.chapterReviews %}{% for chapterReview in chapter.chapterReviews %}- {{chapterReview.content}} ^{{chapterReview.reviewId}}
[[{{chapterReview.createTime.slice(0, 10)}}]]{{chapterReview.createTime.slice(10, 16)}} 
{% endfor%}
{%endif %}{% if chapter.reviews %}{%for review in chapter.reviews %}
{% endfor %} {%endif %} {% endif %} {% endfor %}

{% for chapter in chapterHighlights %}{% if loop.first %}## highlights{% endif %}
### {{chapter.chapterTitle}}
{% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
- {{ highlight.markText |trim }} — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}}  ^{{highlight.chapterUid}}-{{highlight.range}}
{% set regExp = r/\#/g %}{% if regExp.test(highlight.reviewContent) === false %}#读书笔记{% endif %} {{highlight.reviewContent}}
{% else %}
- {{ highlight.markText |trim }}  — created on [[{{highlight.createTime.slice(0, 10)}}]]{{highlight.createTime.slice(10, 16)}}  ^{{highlight.chapterUid}}-{{highlight.range}}
{% endif %} {% endfor %}{% endfor %}

**Comment by zhaohongxuan** [comment]
migrate to discussion
