### ISSUE TITLE
在哪修改模板以及同步之后更新模板如何同步

### ISSUE THREAD

**Issue by liheyuting** [zhaohongxuan/obsidian-weread-plugin#65]
1. 修改了 data.json 里面的template，但没起效
2. 更新了template，重新加载可以直接更新之前已有的读书笔记模板吗？

**Comment by zhaohongxuan** [comment]
@liheyuting 直接在设置界面的模板界面里修改就可以了，保证模板是有效的（无效的模板边框会变成红色提示的）

**Comment by liheyuting** [comment]
> @liheyuting 直接在设置界面的模板界面里修改就可以了，保证模板是有效的（无效的模板边框会变成红色提示的）

您好，dataview的按照说明增加了，但显示不对，可以帮我看下吗？

![image](https://user-images.githubusercontent.com/25094288/177723245-c995725a-4004-4ee3-8faf-067fa86561b0.png)


显示如下：
![image](https://user-images.githubusercontent.com/25094288/177723295-4807d714-12a4-474f-a372-ac94417b0e2d.png)
![image](https://user-images.githubusercontent.com/25094288/177723336-892bc3f5-5338-4412-b7b9-18d10fe38962.png)

**Comment by zhaohongxuan** [comment]
这个需要使用minimal主题的

**Comment by liheyuting** [comment]
非常感谢，我已经搞定了
