### ISSUE TITLE
0.3.0版有几个bug

### ISSUE THREAD

**Issue by tmdt5217** [zhaohongxuan/obsidian-weread-plugin#67]
0.3.0版有几个bug：

1. 电脑端已登录，但移动端一直显示未登录，ob同步完成后依然如此。电脑端重新登陆后，移动端插件可以成功登陆了，但是无法同步笔记。
2. 电脑端同步读书笔记时好时坏。
3. 移动端各种问题，同步未成功过。其中一个错误提示：Cookie 已过期，尝试刷新 Cookie 成功。另一个错误提示：同步微信读书笔记异常，请使用电脑端打开控制台查看详情 TypeError: undefined is not an object (evaluating 'e.map')。

**Comment by visiki** [comment]
我的也是这样 手机端不能用，显示要打开电脑控制台

**Comment by zhaohongxuan** [comment]
@tmdt5217 @visiki 使用什么同步的？我用icloud同步目前没有问题。必须要等到云盘同步完成之后才可以，有时候网络的原因，在电脑上修改的配置在手机端要好久才能展示出来。

如果实在不行，可以在电脑上卸载（如果有模板记得备份），然后看手机上是不是会自动卸载，卸载完成之后再重新安装一遍。

**Comment by visiki** [comment]
onedrive手动备份的，卸载后重新安装手机端登录成功了，手机使用时候还是有错误提示：
同步微信读书笔记异常,请使用电脑端打开控制台 
查看详情SyntaxError: Unexpected token  in 
JSON at position 0

**Comment by zhaohongxuan** [comment]
是用windows+android然后onedrive同步对吧？ 我这边没有测试，android同步感觉不是很友好，我后面研究一下。

**Comment by tmdt5217** [comment]
> @tmdt5217 @visiki 使用什么同步的？我用icloud同步目前没有问题。必须要等到云盘同步完成之后才可以，有时候网络的原因，在电脑上修改的配置在手机端要好久才能展示出来。
> 
> 如果实在不行，可以在电脑上卸载（如果有模板记得备份），然后看手机上是不是会自动卸载，卸载完成之后再重新安装一遍。

我用的官方同步，我试试看吧，谢谢

**Comment by tmdt5217** [comment]
> @tmdt5217 @visiki 使用什么同步的？我用icloud同步目前没有问题。必须要等到云盘同步完成之后才可以，有时候网络的原因，在电脑上修改的配置在手机端要好久才能展示出来。
> 
> 如果实在不行，可以在电脑上卸载（如果有模板记得备份），然后看手机上是不是会自动卸载，卸载完成之后再重新安装一遍。

已重新安装，手机始终无法成功

**Comment by zhaohongxuan** [comment]
> > @tmdt5217 @visiki 使用什么同步的？我用icloud同步目前没有问题。必须要等到云盘同步完成之后才可以，有时候网络的原因，在电脑上修改的配置在手机端要好久才能展示出来。
> > 如果实在不行，可以在电脑上卸载（如果有模板记得备份），然后看手机上是不是会自动卸载，卸载完成之后再重新安装一遍。
> 
> 已重新安装，手机始终无法成功

我没有使用官方的同步功能，不知道是不是可以同步配置文件，你可以检查下看看 sync的设置是不是有问题：https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync

**Comment by tmdt5217** [comment]
> 

已开启所有同步选项，目前的错误代码是：同步微信读书笔记异常，请使用电脑端打开控制台查看详情 TypeError: undefined is not an object (evaluating 'e.map')

控制台里的信息看不懂-_-||

**Comment by zhaohongxuan** [comment]
自己找了一个安卓手机，使用onedrive进行同步，也发现了同步错误的消息，能够看到cookie什么的都是同步成功，但是查询API的时候失败了。

我打开USB调试模式连接到电脑，然后尝试用电脑上的req在安卓手机上进行同步，然后发现同样的request 数据在电脑端可以同步成功，但是在安卓端就是会报错。

这个图是电脑端同步成功的例子：
![image](https://user-images.githubusercontent.com/8613196/179393529-c37a2a0e-aa61-433d-9215-2a21123816f6.png)

这个图是安卓端同步失败的例子：
![image](https://user-images.githubusercontent.com/8613196/179393784-a3c8b7b5-895d-4242-8a04-a4e7ff2cbf33.png)

应该是安卓端和电脑端library不一致导致的。
