### ISSUE TITLE
2天的微信读书（省略）和weread plugin的体验

### ISSUE THREAD

**Issue by foolmos** [zhaohongxuan/obsidian-weread-plugin#68]
weread plugin（仅记录短暂体验到的）
亮点：
① 最大闪光点当然是能连结并导入obsidian啦:partying_face:
② 带自定义模板的导入
③ 即使把整篇读书笔记挪到别的文件夹，改了笔记名字，从云端拉取新条目，追加的依旧能准确投放到原笔记（只要yaml的bookId不变）。颇有点儿追着喂饭，死活把食儿送到嘴边的意思:sweat_smile:
④ 开发大佬原话：初次使用，如果笔记数量较多，更新会比较慢，后面再去更新的时候只会更新划线数量或者笔记数量有变化的书籍，一般速度很快。（注意和“暗点”④比较异同）

暗点：
① 不能设定锚点，跳转原文（刚用，没弄明白，或许可以，还没找到机关在哪儿）
② 自定义模板涉及js，上手改写有难度（不懂js，purely my bad​）
③ 高亮没写笔记的和划线已写笔记的导出不在同一章节内，高亮被单独拎到一个块儿里放着。目前权宜之计：没有笔记的条目全部加上同一个emoji，只要是非空就能被识别当作笔记处理，等导入ob后再全体替换为空
④ 一本书内的笔记非增量同步，只要本地笔记（在ob里修改过）和云端笔记有差异，则以云端为高优先级，overwrite本地:expressionless:
⑤ 一个章节内的笔记是按添加时间线倒序排序的

最希望大佬能改善①③④⑤哈哈有点贪🤣

自定义模板输出成品
![20220705145700](http://tvax2.sinaimg.cn/large/008aPxHsgy1h40oeav55pj30xs1trqaa.jpg)

顺道祝贺大佬上了官方roundup的headsup！
[🌠 Dashboards & Tips for Students, Studying & Sales](https://www.obsidianroundup.org/2022-07-09/)

**Comment by foolmos** [comment]
忘了@zhaohongxuan

**Comment by zhaohongxuan** [comment]
@foolmos 写的好用心呀，
1. 跳转原文之前研究过，比较难实现，网页端没有锚点，而且bookid是加密的，现在还没有解码的方法。
3. 这个挺多人反馈了，我后面考虑把高亮和书评放在一起。
4. 增量同步这个应该是不会做，因为我现在没有办法判断哪一个block同步过了哪一个没同步，尽量把关键信息放在frontmatter的yaml文件里。
5. 后续应该会后续应该会设置一个开关，正序还是倒序。
对了，你的笔记好漂亮...  是什么主题？😆

**Comment by foolmos** [comment]
@zhaohongxuan 节选片段只是冰山一角😅看到全文恐怕要吃鲸🐋
[微信读书和weread plugin无聊初体验 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/8737)

不能原文跳转是最大的pity😣
关于③，目前采用迂回战术，改bookId（去掉最末一个字母），骗云端重新拉回整篇笔记，再把增量部分搬到改id的那篇里😋

主题是改到见不到一丁点儿原色的blue topaz🤣
想不到大佬对小女生的审美感兴趣😆

自改weread模板

![image](https://user-images.githubusercontent.com/78858135/178128020-9b4de786-98b1-4833-9a27-2792a0a17572.png)

**Comment by foolmos** [comment]
@zhaohongxuan 呼唤大佬~
ob更新0.15.6，weread不适配shiny feature：popup window呃..('､3_ヽ)_
求大佬速配 🥰

**Comment by zhaohongxuan** [comment]
> @zhaohongxuan 呼唤大佬~ ob更新0.15.6，weread不适配shiny feature：popup window呃..('､3_ヽ)_ 求大佬速配 🥰
这是什么feature呀？ 展开讲讲🥹

**Comment by foolmos** [comment]
@zhaohongxuan 大佬俺姗姗来迟抱歉抱歉
最新版feature
![image](https://user-images.githubusercontent.com/78858135/180146901-caab83ec-0c3c-4805-9cd0-e0ee1187acf0.png)
[Obsidian Roadmap | Trello](https://trello.com/b/Psqfqp7I/obsidian-roadmap)

上次在这个帖子里瞄到大佬放出一张很貌美的笔记截图，现在怎么没了，上次忘了收藏了😑
[Feature Request：以笔记生成时间戳为过滤条件导出笔记 · Issue #69 · zhaohongxuan/obsidian-weread-plugin](https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/69)

**Comment by lifesign** [comment]
> @zhaohongxuan 节选片段只是冰山一角😅看到全文恐怕要吃鲸🐋 [微信读书和weread plugin无聊初体验 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/8737)
> 
> 不能原文跳转是最大的pity😣 关于③，目前采用迂回战术，改bookId（去掉最末一个字母），骗云端重新拉回整篇笔记，再把增量部分搬到改id的那篇里划线写笔记😋
> 
> 主题是改到见不到一丁点儿原色的blue topaz🤣 想不到大佬会对小女生的审美感兴趣😆
> 
> 自改weread模板
> 
> ![image](https://user-images.githubusercontent.com/78858135/178128020-9b4de786-98b1-4833-9a27-2792a0a17572.png)

请问能提供一下代码版本吗~ 感谢

**Comment by lalaniu85** [comment]
> @zhaohongxuan 节选片段只是冰山一角😅看到全文恐怕要吃鲸🐋 [微信读书和weread plugin无聊初体验 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/8737)
> 
> 不能原文跳转是最大的pity😣 关于③，目前采用迂回战术，改bookId（去掉最末一个字母），骗云端重新拉回整篇笔记，再把增量部分搬到改id的那篇里划线写笔记😋
> 
> 主题是改到见不到一丁点儿原色的blue topaz🤣 想不到大佬会对小女生的审美感兴趣😆
> 
> 自改weread模板
> 
> ![image](https://user-images.githubusercontent.com/78858135/178128020-9b4de786-98b1-4833-9a27-2792a0a17572.png)

我问一下，为什么有的字号可以显示（时间字号变小、颜色变灰）但是有的就不能显示呢？特指上标（top05）。我觉得好奇怪啊。

**Comment by foolmos** [comment]
> > @zhaohongxuan 节选片段只是冰山一角😅看到全文恐怕要吃鲸🐋 [微信读书和weread plugin无聊初体验 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/8737)
> > 不能原文跳转是最大的pity😣 关于③，目前采用迂回战术，改bookId（去掉最末一个字母），骗云端重新拉回整篇笔记，再把增量部分搬到改id的那篇里划线写笔记😋
> > 主题是改到见不到一丁点儿原色的blue topaz🤣 想不到大佬会对小女生的审美感兴趣😆
> > 自改weread模板
> > ![image](https://user-images.githubusercontent.com/78858135/178128020-9b4de786-98b1-4833-9a27-2792a0a17572.png)
> 
> 请问能提供一下代码版本吗~ 感谢

主要是这里有一些自定义的css片段，光是给模板，也没用🙄

**Comment by foolmos** [comment]
> > @zhaohongxuan 节选片段只是冰山一角😅看到全文恐怕要吃鲸🐋 [微信读书和weread plugin无聊初体验 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/8737)
> > 不能原文跳转是最大的pity😣 关于③，目前采用迂回战术，改bookId（去掉最末一个字母），骗云端重新拉回整篇笔记，再把增量部分搬到改id的那篇里划线写笔记😋
> > 主题是改到见不到一丁点儿原色的blue topaz🤣 想不到大佬会对小女生的审美感兴趣😆
> > 自改weread模板
> > ![image](https://user-images.githubusercontent.com/78858135/178128020-9b4de786-98b1-4833-9a27-2792a0a17572.png)
> 
> 我问一下，为什么有的字号可以显示（时间字号变小、颜色变灰）但是有的就不能显示呢？特指上标（top05）。我觉得好奇怪啊。

有图有真相，请友友上看图说话😋

**Comment by foolmos** [comment]
@lifesign 主要是这里有一些自定义的css片段，光是给模板，也没用🙄

**Comment by foolmos** [comment]
@lalaniu85 有图有真相，请友友上看图说话😋

**Comment by lalaniu85** [comment]
> @lalaniu85 有图有真相，请友友上看图说话😋

来了
<img width="1104" alt="截屏2022-07-28 12 04 30" src="https://user-images.githubusercontent.com/103034960/181417898-20ff7192-0dbc-4752-8fd2-2dc4a0ab1046.png">

就是特别奇怪，时间字号有变小、颜色变灰。但是后面那个上标，一点变化没有。

**Comment by lifesign** [comment]
> @lifesign 主要是这里有一些自定义的css片段，光是给模板，也没用🙄

看模板里像是都是行内样式呢，自定义的样式是体现在哪里哇

**Comment by foolmos** [comment]
> > @lalaniu85 有图有真相，请友友上看图说话😋
> 
> 来了 <img alt="截屏2022-07-28 12 04 30" width="1104" src="https://user-images.githubusercontent.com/103034960/181417898-20ff7192-0dbc-4752-8fd2-2dc4a0ab1046.png">
> 
> 就是特别奇怪，时间字号有变小、颜色变灰。但是后面那个上标，一点变化没有。

哈哈大佬，俺都还没分享<span class="top05">的css样式咧😂
这就来哈~

`.top05 {
  background-color: #a15d4e;
  color: rgb(231, 231, 231);
  vertical-align: top;
  border-radius: 3px;
  padding: 1px 6px;
  font-size: 8px;
  height: 14px;
  line-height: 14px;
  text-decoration:none;
  /* font-weight: 600; */
  letter-spacing: .1em;
}`

**Comment by foolmos** [comment]
> > @lifesign 主要是这里有一些自定义的css片段，光是给模板，也没用🙄
> 
> 看模板里像是都是行内样式呢，自定义的样式是体现在哪里哇

像<span class="top05">
还有，开头拿来放置书封面图的callout，遇到alt属性是cover的图片，就套用某css样式
像这些，我都另写到一个css文件存放，这样模板里的代码会简洁些😋
