### ISSUE TITLE
Feature Request：以笔记生成时间戳为过滤条件导出笔记

### ISSUE THREAD

**Issue by jarodise** [zhaohongxuan/obsidian-weread-plugin#69]
目前市面上所有的微信读书导出服务都是以书名作为基本分类，但是如果我们在研究某一个课题，同时阅读好几本书，或者就是完全不相关的几本书同时按照不同的进度来阅读，这时候用这种基于书名的全覆盖式导出可能就不是很方便。

举例来说，我一天看了三本不同的书，每一本书都读了几页，做了一些笔记，到晚上我希望只导入今天我阅读和做笔记的部分，并存入今天的daily journal里面，这时候我希望以时间戳为过滤条件，只导出今天内读到的内容，并保存到我今天的DailyJournal，而不重复导入我以前做过的笔记。

我看到插件目前导出的每一条高亮和笔记都是默认标记生成时间戳的，所以实现这个功能应该不难。

目前主流的PKM工具，例如Roam，Obsidian, Logseq都是以Daily Journal作为主要信息入口，所以我认为这样的导出逻辑可以更好地契合这类工具，希望能够考虑。

**Comment by zhaohongxuan** [comment]
这个idea很好，未来应该会实现，但是应该还是基于现有的book name存储笔记内容，会在Journal中增加今日读书的block reference，这样方便能在Journal看到今天读了哪些书，做了哪些标记，效果应该如下：
<img width="873" alt="image" src="https://user-images.githubusercontent.com/8613196/178706868-2e5c0582-96c2-4bc3-a321-9e95074f0cab.png">
但是Journal是插件支持的，我需要研究一下可行性，很多人使用Obsidian是research用途的，可能不用Journal，这个可能会在设置里增加一些额外的设置项。

**Comment by jarodise** [comment]
在该功能正式推出之前，我研究出来一个临时的解决方案： 

1.安装Obsidian和第三方插件微信读书插件Weread。

2. 修改Weread插件的输出模板： 
```
	  {% for chapter in chapterHighlights %}{% if loop.first %}## Highlights{% endif %}
	  ### {{chapter.chapterTitle}}
	  {% for highlight in chapter.highlights %}{% if highlight.reviewContent %}
	  - {{ highlight.markText |trim }}  🗓 [[{{highlight.createTime.slice(0, 10)}}]] [[inbox]] [[读书笔记]]
	  {% set regExp = r/\#/g %}{% if regExp.test(highlight.reviewContent) === false %}#阅读随想💡{% endif %} {{highlight.reviewContent}}
	  {% else %}
	  - {{ highlight.markText |trim }}  🗓 [[{{highlight.createTime.slice(0, 10)}}]] [[inbox]] [[读书笔记]]
	  {% endif %} {% endfor %}{% endfor %}
```
此模板在 https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/56 的基础上简化修改而成
主要目的在于将笔记生成的时间戳的日期部分加上[[]], 从而实现每条笔记在阅读当日的Daily Journal的反链。
除了日期外，我还在每条笔记后面默认加上了inbox和读书笔记这两个标签，作为后面继续在logseq中进行分类处理的过滤标记，如果你不需要后续处理或者有其它的tagging方式，也可以删掉这两个tag或者自行设定。
注：Daily Journal日期格式需要设定为YYYY-MM-DD

3.如果你主力使用Obsidian的话，经过上面的设定，你的每一条读书笔记都会自带一个笔记创建日期的反链。你只需要在Obsidian通过Caldenar里打开当日的Daily Note，就能在backlink面板看到当日的所有读书笔记，不论是一本书还是多本书。

4.如果你像我一样主力使用logseq的话，那么还需要多一步设置。我的做法是在Obsidian创建一个新的Vault，这个Vault的文件夹存在于logseq的pages文件夹下面，然后在这个新的Vault里面安装Weread和Calendar这两个插件。然后按照上面提示修改好模板并进行读书笔记导入操作即可。

**Comment by jarodise** [comment]
另外，真的很希望开发者有余力的话，也能为我们主力使用logseq的小伙伴们做一个logseq版的Weread插件

**Comment by zhaohongxuan** [comment]
> 另外，真的很希望开发者有余力的话，也能为我们主力使用logseq的小伙伴们做一个logseq版的Weread插件
logseq的逻辑和obsidian差别还是挺大的，未来有时间研究一下。
