### ISSUE TITLE
0.4.0移动端依然无法使用

### ISSUE THREAD

**Issue by tmdt5217** [zhaohongxuan/obsidian-weread-plugin#71]
0.4.0和0.3.0一样，移动端（手机端和iPad）点击这个插件同步读书笔记后，提示笔记已更新，更新1本书。然而打开这本书的笔记，并没有同步成功。（我Obsidian同步用的是官方同步，且设置里选择的是同步所有类型的数据。）

在移动端的插件上从来没有成功同步过一次笔记，Mac上正常使用。太喜欢这个插件了，希望改进，谢谢谢谢！

**Comment by zhaohongxuan** [comment]
> 0.4.0和0.3.0一样，移动端（手机端和iPad）点击这个插件同步读书笔记后，提示笔记已更新，更新1本书。然而打开这本书的笔记，并没有同步成功。（我Obsidian同步用的是官方同步，且设置里选择的是同步所有类型的数据。）
> 
> 在移动端的插件上从来没有成功同步过一次笔记，Mac上正常使用。太喜欢这个插件了，希望改进，谢谢谢谢！

这个问题我没法复现，我没有官方同步服务，现在需要排查是什么问题导致的。
1. 手机或者ipad端点击weread plugin的设置界面看看是不是所有的设置项都适合电脑端是一致的，如果都是初始值，那说明设置没同步，或者至少没同步成功，下面是我的iphone上的设置面板：
![IMG_7277](https://user-images.githubusercontent.com/8613196/179389203-123e9f57-7593-452b-969a-3ffa9a7619e2.PNG)
2. 可以创建一个新的vault，使用iCloud试试，看能否正常

**Comment by zhaohongxuan** [comment]
@tmdt5217 其他第三方的插件设置能否正常同步？
iPad可以使用FE文件管理器挂载你的Obsidian所在的文件夹看看是不是有对应的.obsidian配置文件。

**Comment by zhaohongxuan** [comment]
> 0.4.0和0.3.0一样，移动端（手机端和iPad）点击这个插件同步读书笔记后，提示笔记已更新，更新1本书。然而打开这本书的笔记，并没有同步成功。（我Obsidian同步用的是官方同步，且设置里选择的是同步所有类型的数据。）
> 
> 在移动端的插件上从来没有成功同步过一次笔记，Mac上正常使用。太喜欢这个插件了，希望改进，谢谢谢谢！

你试着删掉这本书然后同步看能否同步成功？

**Comment by tmdt5217** [comment]
> > 0.4.0和0.3.0一样，移动端（手机端和iPad）点击这个插件同步读书笔记后，提示笔记已更新，更新1本书。然而打开这本书的笔记，并没有同步成功。（我Obsidian同步用的是官方同步，且设置里选择的是同步所有类型的数据。）
> > 在移动端的插件上从来没有成功同步过一次笔记，Mac上正常使用。太喜欢这个插件了，希望改进，谢谢谢谢！
> 
> 这个问题我没法复现，我没有官方同步服务，现在需要排查是什么问题导致的。
> 
> 1. 手机或者ipad端点击weread plugin的设置界面看看是不是所有的设置项都适合电脑端是一致的，如果都是初始值，那说明设置没同步，或者至少没同步成功，下面是我的iphone上的设置面板：
>    ![IMG_7277](https://user-images.githubusercontent.com/8613196/179389203-123e9f57-7593-452b-969a-3ffa9a7619e2.PNG)
> 2. 可以创建一个新的vault，使用iCloud试试，看能否正常

1. 刚才试了下所有设置项都一致的，还是无法成功。后来我改了存放微信读书笔记的文件夹，设置同步很慢，还是失败
2. iCloud同步的也不行，电脑端都无法同步，提示：同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-weread-plugin:2:498362)
    at b.eval (plugin:obsidian-weread-plugin:2:498928)
    at Generator.next (<anonymous>)
    at o (plugin:obsidian-weread-plugin:2:487165)
eval @ plugin:obsidian-weread-plugin:2

**Comment by tmdt5217** [comment]
> > 0.4.0和0.3.0一样，移动端（手机端和iPad）点击这个插件同步读书笔记后，提示笔记已更新，更新1本书。然而打开这本书的笔记，并没有同步成功。（我Obsidian同步用的是官方同步，且设置里选择的是同步所有类型的数据。）
> > 在移动端的插件上从来没有成功同步过一次笔记，Mac上正常使用。太喜欢这个插件了，希望改进，谢谢谢谢！
> 
> 你试着删掉这本书然后同步看能否同步成功？

删了一本，依然电脑端可以同步，手机端不行

**Comment by zhaohongxuan** [comment]
@tmdt5217 更新了0.4.1修复了一个小问题，试试看~

**Comment by tmdt5217** [comment]
> 2\. 创建一个新的vault，使用iCloud试试

仍然是电脑端可以同步，手机端不行。

**Comment by zhaohongxuan** [comment]
> 同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'length')

还是这个错？

**Comment by tmdt5217** [comment]
> > 同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'length')
> 
> 还是这个错？

不是了，现在电脑端可以同步无报错，手机端也没有报错，如图：
![D477E469-EF54-4F2A-B67A-8EB2EC7E1871_1_101_o](https://user-images.githubusercontent.com/19581451/179448240-1fe6a653-6fdd-4aa5-802d-6f7291b1c9f6.jpeg)
然而尽管手机端提示这个，但笔记内容不增加。

**Comment by zhaohongxuan** [comment]
> > > 同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'length')
> > 
> > 
> > 还是这个错？
> 
> 不是了，现在电脑端可以同步无报错，手机端也没有报错，如图： ![D477E469-EF54-4F2A-B67A-8EB2EC7E1871_1_101_o](https://user-images.githubusercontent.com/19581451/179448240-1fe6a653-6fdd-4aa5-802d-6f7291b1c9f6.jpeg) 然而尽管手机端提示这个，但笔记内容不增加。

手机端删掉重新同步，文件会重新创建吗？

**Comment by wuyueshiwo** [comment]
我也出现了这种情况，我是iPad端的，也是电脑可以同步，但是手机和iPad都不能同步。我尝试过下列操作都不行：
1. 删除iPad端的插件，然后重新安装，提示让我现在电脑前登陆，然后我把电脑上的文件插件文件拷过来替换上，就出现上面他截图的这种
2. 直接通过第三方插件Remotely Save，同步配置文件夹，然后也是不行和上面情况一样。
3. 删除原笔记，并更改文件生成位置。结果一样。
4. 尝试使用Weread：Force Sync Weread Notes命令。结果一样

**Comment by zhaohongxuan** [comment]
使用icloud同步可能会有点慢，一定要等同步完成了之后才能使用。Remotely Save我在安卓端测试过可以正常同步

**Comment by wuyueshiwo** [comment]
我的电脑是Linux的系统，所以用不了iCloud。手机也不是安卓设备。所以也不好测试你说的情况。
