### ISSUE TITLE
Obsidian Highlight能否不显示注释部分

### ISSUE THREAD

**Issue by luojiadream** [zhaohongxuan/obsidian-weread-plugin#74]
原文中有很多注释（如下图所示），画线后会在Obsidian中引入[ ]，这样看着不规范。请问时候有方法处理一下细节？
![image](https://user-images.githubusercontent.com/44284319/179722321-d52b35d7-9879-4d07-b191-d44e8a159144.png)

**Comment by zhaohongxuan** [comment]
@luojiadream 
请参考模板语法：https://mozilla.github.io/nunjucks/templating.html#regular-expressions，将[0-9]替换掉即可。

**Comment by luojiadream** [comment]
谢谢，我摸索一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月19日(周二) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaohongxuan/obsidian-weread-plugin] Obsidian Highlight能否不显示注释部分 (Issue #74)




 
@luojiadream
 请参考模板语法：https://mozilla.github.io/nunjucks/templating.html#regular-expressions，将[0-9]替换掉即可。

**Comment by luojiadream** [comment]
您的邮件我已收到，祝您工作顺利！
