### ISSUE TITLE
401同步异常

### ISSUE THREAD

**Issue by wenlzhang** [zhaohongxuan/obsidian-weread-plugin#75]
这两天频繁出现同步异常的情况。昨天重新安装插件并且重新登录后解决了这个问题，但是今天又出现了相同的问题。

当前在用 Obsidian 0.15.7 和插件 0.4.1。

具体错误提示如下：
```
同步微信读书笔记异常 Error: Request failed, status 401
    at new t (app.js:1:1454570)
    at UN (app.js:1:1454725)
    at app.js:1:1455402
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
eval	@	plugin:obsidian-weread-plugin:2

```

**Comment by kiwiflydream** [comment]
一样的问题

**Comment by zhaohongxuan** [comment]
我这边没法重现这个错误，你确定一下是不是在其他浏览器里重新登录了微信读书，如果登录过，可能会导致插件里的cookie失效且无法正常刷新。

**Comment by wenlzhang** [comment]
> 我这边没法重现这个错误，你确定一下是不是在其他浏览器里重新登录了微信读书，如果登录过，可能会导致插件里的cookie失效且无法正常刷新。

最近都没有在其他浏览器登录，只在用微信读书手机客户端。

**Comment by wenlzhang** [comment]
这两天还是频繁出现这个问题。还注意到，只是电脑休眠后重新开启，就会发现插件无法同步内容；需要退出账号并重新登录后才能使用。

**Comment by q823049029** [comment]
重新退出。然后再登录我的就变好了

**Comment by liruiqiang** [comment]
我也遇到了同样的问题，注销登录后能好一会儿，但是下午再打开电脑就又显示“同步微信笔记异常“

**Comment by zhaohongxuan** [comment]
@liruiqiang 我自己测试了一下，隔了一个周末再次同步也不会报错🥹，你可以试试手动下载 0.3.0版本的插件看看

**Comment by liruiqiang** [comment]
每次重新打开电脑就需要重新登录一次，要不然就显示同步异常，郁闷了。

**Comment by laybxc** [comment]
我也有类似的问题，过一会又异常了

**Comment by liamtao** [comment]
我也是，注销了再登录还是异常。。。

**Comment by liruiqiang** [comment]
> @liruiqiang 我自己测试了一下，隔了一个周末再次同步也不会报错🥹，你可以试试手动下载 0.3.0版本的插件看看

试了3.0版本，还是一样的问题。

**Comment by spencer924** [comment]
+1，求助解决

**Comment by jarodise** [comment]
同样的问题，每次都是需要注销再次登录才能正常使用。报错信息如下方截图：
![CleanShot 2022-07-29 at 22 06 15@2x](https://user-images.githubusercontent.com/15899808/181827827-84ef1676-1dca-41f2-aef6-f6d3cef5c386.png)

**Comment by zhaohongxuan** [comment]
终于重现了这个问题，重现步骤是，在其他网页端登录浏览器上的微信读书，会导致cookie 过期，正常来说，请求会返回401的response，但是好像新版的obsidian requestUrl接口返回的是ERROR，没有正常handle，现在本地已经测试完成了，准备release了
