### ISSUE TITLE
电脑端登录之后，手机端还是没有登录，无法使用，如图

### ISSUE THREAD

**Issue by liruiqiang** [zhaohongxuan/obsidian-weread-plugin#78]
![截屏2022-07-26 14 07 11](https://user-images.githubusercontent.com/18613550/180935298-a452270d-cc13-4b40-851c-81f6605a1e71.png)
![WechatIMG905](https://user-images.githubusercontent.com/18613550/180935416-5e742341-48df-4665-91d8-f9dc1d31fd5d.jpeg)

**Comment by zhaohongxuan** [comment]
你使用什么同步服务？

**Comment by liruiqiang** [comment]
> 

用的Obsidian自带的同步

**Comment by zhaohongxuan** [comment]
@liruiqiang obsidian官方同步服务我这边没法测试，测试iCloud和Onedrive是没问题的

**Comment by liuzhiyuana** [comment]
> @liruiqiang obsidian官方同步服务我这边没法测试，测试iCloud和Onedrive是没问题的

请问用Remotely Save能同步登陆状态吗

**Comment by zhaohongxuan** [comment]
> > @liruiqiang obsidian官方同步服务我这边没法测试，测试iCloud和Onedrive是没问题的
> 
> 请问用Remotely Save能同步登陆状态吗

我之前试过，是可以的，得勾选同步配置文件。
