### ISSUE TITLE
只能同步书架中微信读书有的书

### ISSUE THREAD

**Issue by gkjj** [zhaohongxuan/obsidian-weread-plugin#79]
书架上我自己上传的书不能同步有点难受，是因为技术原因做不了吗，难受。:broken_heart:

**Comment by zhaohongxuan** [comment]
> 书架上我自己上传的书不能同步有点难受，是因为技术原因做不了吗，难受。💔

可以同步自己上传的书，在未分类文件夹中。

**Comment by gkjj** [comment]
> > 书架上我自己上传的书不能同步有点难受，是因为技术原因做不了吗，难受。💔
> 
> 可以同步自己上传的书，在未分类文件夹中。

🆗
