### ISSUE TITLE
笔记排列顺序

### ISSUE THREAD

**Issue by spencer924** [zhaohongxuan/obsidian-weread-plugin#82]
目前笔记是按照添加时间顺序倒序排列的，可以倒过来吗？或者按照原文排版顺序排列？

**Comment by zhaohongxuan** [comment]
> 目前笔记是按照添加时间顺序倒序排列的，可以倒过来吗？或者按照原文排版顺序排列？

在模板里可以做一个排序。

**Comment by zhaohongxuan** [comment]
@spencer924 参考这里：https://mozilla.github.io/nunjucks/templating.html#sort-arr-reverse-casesens-attr

**Comment by palwoo** [comment]
非常感谢 @zhaohongxuan 的插件，这是我从用了一年多的logseq转回到obsidian的主要原因中的第一个原因。我也感觉按照原文排版顺序排列会更有利于把握原文的逻辑脉络。您提供了排序的线索，但对于不懂编程语言的笔记使用者来说，这个线索还是如同天书一般，不知道如何修改后添加到模板中。不知道您可否提供直接可用的代码？
