### ISSUE TITLE
如何删除创建时间的block?

### ISSUE THREAD

**Issue by Samuelxiaozhuofeng** [zhaohongxuan/obsidian-weread-plugin#88]
在导入笔记时候，尝试在模板里删除 creation-time，但是会显示红框红色导致模板无法使用，要如何解决？

**Comment by zhaohongxuan** [comment]
> 在导入笔记时候，尝试在模板里删除 creation-time，但是会显示红框红色导致模板无法使用，要如何解决？

红色框表示模板有错误，看下是不是语法错误
