### ISSUE TITLE
关于自定义模板的问题

### ISSUE THREAD

**Issue by gavincrown** [zhaohongxuan/obsidian-weread-plugin#89]
**第一：能否按书籍章节归类划线和想法？**

现在划线和想法是分开成两个模块，并且各自都按章节划分，能否合并在一起？
![186096069-09305a93-a749-4d20-bf3b-2819eaa21](https://user-images.githubusercontent.com/110040980/186096541-a9f3ce99-cc34-47d7-a189-1a12b3e4d9c0.png)

**第二：划线和想法都是倒序的**

数据显示到笔记里是倒过来的，就是如下这样的，如何设置成正序的？
+ 第一章
  + 第4个想法
  + 第3个想法
  + 第2个想法
  + 第1个想法

**第三：划线数据能否区分类型**

目前是有三种划线类型：荧光笔，波浪线、直线

**Comment by zhaohongxuan** [comment]
参考一下： https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/49

**Comment by gavincrown** [comment]
> 参考一下： #49

emmm...好像不太符合我的需求😂算了，不折腾了
