### ISSUE TITLE
请问能不能自定义不导入某些书的笔记？

### ISSUE THREAD

**Issue by TtlyLynzie** [zhaohongxuan/obsidian-weread-plugin#92]
可不可以自己输入不想被导入批注的书籍名字，这样在每次的更新中就自动跳过这些书籍

**Comment by zhaohongxuan** [comment]
等有空了安排一下。

**Comment by milla** [comment]
可以通过一些更简便的、自定义的方式支持吗？这样不需要每次修改插件config
比如，我在书籍评论中增加 #ignored 的内容 (configurable)，就自动屏蔽？
