### ISSUE TITLE
40000+划线笔记无法同步

### ISSUE THREAD

**Issue by Rnzi** [zhaohongxuan/obsidian-weread-plugin#96]
您好，我将您开发的插件推荐给朋友，她的笔记量实在太多，光划线就40000+条，排除了网络问题，同步失败。报错提示如下图
请问有什么办法解决呢？
![IMG_2115](https://user-images.githubusercontent.com/32623006/188500375-bdc960c0-be95-45b3-929a-0ded032175fc.PNG)
![IMG_2114](https://user-images.githubusercontent.com/32623006/188500381-b4fb76fe-dbec-46cb-923d-ce5a8c7d18ad.PNG)

**Comment by zhaohongxuan** [comment]
这个我也无法重现，可以提供下 详细报错日志吗？

**Comment by Rnzi** [comment]
来了来了，是这样么？打开控制台后看这里的信息。
![image](https://user-images.githubusercontent.com/32623006/190333732-c2d0b87d-cc05-4aff-b0b0-0402cd29ebf0.png)

**Comment by Rnzi** [comment]
解决了，系统是macos11，默认开了VPN，也不用关，只需要点击同步后什么操作都不要做，两根烟的功夫就同步成功了。
同步时候OB后台并没有别的显示，但可以从mac的性能监视器里看到网络接收中的obsidian helper是有数据增加的。
