### ISSUE TITLE
保存笔记到Daily Notes 功能报错

### ISSUE THREAD

**Issue by hadwinn** [zhaohongxuan/obsidian-weread-plugin#97]
如图，左侧日记页面无法显示，应该是块引用多出了一部分。请问如何解决？
![image](https://user-images.githubusercontent.com/73227570/189088078-88d6d47d-be99-466c-8e14-0743d3a0bdb4.png)

**Comment by zhaohongxuan** [comment]
你是不是修改了模板了？

**Comment by hadwinn** [comment]
> 你是不是修改了模板了？

没有。

**Comment by Mingmingshuai** [comment]
和你一样的问题

**Comment by Mingmingshuai** [comment]
![image](https://user-images.githubusercontent.com/76103984/203492938-17900686-3921-47fd-b0dc-2e60ac452796.png)

**Comment by silentsky2billten** [comment]
我也这个问题。

**Comment by zkyken** [comment]
我也是。插入daily note时多了一个bookId。模板的{{bookId}}无法抓取，因此没办法弄成一致。

**Comment by zhaohongxuan** [comment]
https://github.com/zhaohongxuan/obsidian-weread-plugin/issues/117
